erDiagram
    ACCOUNT {
        Identifier Account_Id "PK"
        Number Account_Num ""
        Name Account_Name ""
        Date Account_Open_Dt ""
        Date Account_Close_Dt ""
        string more "8 more"
    }
    ACCOUNTING_CURRENCY {
        Identifier Business_Unit_Party_Id "PK"
        Code Accounting_Type_Cd "PK"
        Datetime Accounting_Currency_Start_Dttm "PK"
        Code Accounting_Currency_Cd "PK"
        Datetime Accounting_Currency_End_Dttm ""
    }
    ACCOUNTING_TYPE {
        Code Accounting_Type_Cd "PK"
        Description Accounting_Type_Desc ""
    }
    ACCOUNT_INVOLVEMENT_SUBTYPE {
        Code Account_Involvement_Subtype_Cd "PK"
        Description Account_Involvement_Subtype_Desc ""
    }
    ACCOUNT_METRIC {
        Identifier Account_Id "PK"
        Code Account_Metric_Type_Cd "PK"
        Datetime Account_Metric_Dttm "PK"
        Amount Account_Metric_Amt ""
        Count Account_Metric_Cnt ""
        string more "3 more"
    }
    ACCOUNT_METRIC_TYPE {
        Code Account_Metric_Type_Cd "PK"
        Description Account_Metric_Type_Desc ""
    }
    ACCOUNT_PURPOSE_SUBTYPE {
        Code Account_Purpose_Subtype_Cd "PK"
        Description Account_Purpose_Subtype_Desc ""
    }
    ACCOUNT_RENEWAL {
        Identifier Account_Id "PK"
        Datetime Account_Renewal_Planned_Start_Dttm "PK"
        Datetime Account_Renewal_Actual_Start_Dttm ""
        Datetime Account_Renewal_Planned_Expiration_Dttm ""
        Datetime Account_Renewal_Actual_Expiration_Dttm ""
    }
    ACCOUNT_TYPE {
        Code Account_Type_Cd "PK"
        Description Account_Type_Desc ""
    }
    AGENCY_CREDIT_REPORT {
        Name Obligor_First_Name ""
        Name Obligor_Middle_Name ""
        Name Obligor_Last_Name ""
        Number Obligor_Street_Num ""
        Name Obligor_Street_Name ""
        string more "11 more"
    }
    AGENT_BROKER_AGREEMENT_DETAIL {
        Code Commission_Type_Cd ""
        Rate Commission_Rate ""
    }
    AGREEMENT {
        Identifier Agreement_Id "PK"
        Code Agreement_Subtype_Cd "PK"
        Number Host_Agreement_Num ""
        Name Agreement_Name ""
        Name Alternate_Agreement_Name ""
        string more "17 more"
    }
    AGREEMENT_ABUSE {
        Identifier Agreement_Id "PK"
        Code System_Abuse_Type_Cd "PK"
        Date Agreement_Abuse_Dt "PK"
        Amount Abuse_Occurred_Currency_Amt ""
        Amount Agreement_Abuse_Amt ""
        string more "2 more"
    }
    AGREEMENT_ACCESS_DEVICE {
        Identifier Agreement_Id "PK"
        Code Agreement_Access_Device_Type_Cd "PK"
        Date Agreement_Access_Device_Start_Dt "PK"
        Identifier Access_Device_Id "PK"
        Date Agreement_Access_Device_End_Dt ""
    }
    AGREEMENT_ACCESS_DEVICE_FEATURE {
        Identifier Agreement_Id "PK"
        Code Agreement_Access_Device_Type_Cd "PK"
        Date Agreement_Access_Device_Start_Dt "PK"
        Identifier Access_Device_Id "PK"
        Identifier Feature_Id "PK"
        string more "2 more"
    }
    AGREEMENT_ACCESS_DEVICE_TYPE {
        Code Agreement_Access_Device_Type_Cd "PK"
        Description Agreement_Access_Device_Desc ""
    }
    AGREEMENT_AGREEMENT_CLASS_XREF {
        Identifier Agreement_Id "PK"
        Code Agreement_Class_Cd "PK"
        Date Agreement_Class_Start_Dt "PK"
        Code Agreement_Class_Value_Cd "PK"
        Date Agreement_Class_End_Dt ""
    }
    AGREEMENT_AGREEMENT_GROUP {
        Identifier Agreement_Id "PK"
        Identifier Agreement_Group_Id "PK"
        Date Agreement_Agreement_Group_Start_Dt "PK"
        Date Agreement_Agreement_Group_End_Dt ""
        Code Agreement_Agreement_Group_Subtype_Cd ""
    }
    AGREEMENT_AGREEMENT_GROUP_SUBTYPE {
        Code Agreement_Agreement_Group_Subtype_Cd "PK"
        Description Agreement_Agreement_Group_Subtype_Desc ""
    }
    AGREEMENT_APPLICATION {
        Identifier Application_Id "PK"
        Identifier Agreement_Id "PK"
        Code Agreement_Application_Role_Cd "PK"
        Date Agreement_Application_Start_Dt "PK"
        Date Agreement_Application_End_Dt ""
    }
    AGREEMENT_APPLICATION_ROLE {
        Code Agreement_Application_Role_Cd "PK"
        Description Agreement_Application_Role_Desc ""
    }
    AGREEMENT_ASSET {
        Identifier Agreement_Id "PK"
        Identifier Party_Asset_Id "PK"
        Code Agreement_Asset_Role_Subtype_Cd "PK"
        Date Agreement_Asset_Start_Dt "PK"
        Date Agreement_Asset_End_Dt ""
    }
    AGREEMENT_ASSET_ROLE_SUBTYPE {
        Code Agreement_Asset_Role_Subtype_Cd "PK"
        Description Agreement_Asset_Role_Subtype_Desc ""
    }
    AGREEMENT_BALANCE_TYPE_METRIC {
        Identifier Agreement_Id "PK"
        Code Balance_Category_Type_Cd "PK"
        Code Agreement_Metric_Type_Cd "PK"
        Datetime Agreement_Balance_Type_Metric_End_Dttm "PK"
        Datetime Agreement_Balance_Type_Metric_Start_Dttm "PK"
        string more "6 more"
    }
    AGREEMENT_CASE {
        Identifier Case_Id "PK"
        Identifier Agreement_Id "PK"
    }
    AGREEMENT_CHANNEL {
        Code Agreement_Channel_Role_Type_Cd "PK"
        Identifier Channel_Instance_Id "PK"
        Identifier Agreement_Id "PK"
        Date Agreement_Channel_Start_Dt "PK"
        Percent Agreement_Channel_Allocation_Pct ""
        string more "2 more"
    }
    AGREEMENT_CHANNEL_ROLE_TYPE {
        Code Agreement_Channel_Role_Type_Cd "PK"
        Description Agreement_Channel_Role_Type_Desc ""
    }
    AGREEMENT_CHANNEL_TYPE {
        Identifier Agreement_Id "PK"
        Code Channel_Type_Cd "PK"
        Code Agreement_Channel_Role_Type_Cd "PK"
        Date Agreement_Channel_Type_Start_Dt "PK"
        Date Agreement_Channel_Type_End_Dt ""
    }
    AGREEMENT_CHART_OF_ACCOUNTS {
        Identifier Agreement_Id "PK"
        Identifier COA_Code_Id "PK"
        Code Set_Of_Books_Cd "PK"
        Date Agreement_Chart_Of_Accounts_Start_Dt "PK"
        Date Agreement_Chart_Of_Accounts_End_Dt ""
    }
    AGREEMENT_CLAIM {
        Identifier Agreement_Id "PK"
        Identifier Claim_Id "PK"
        Code Agreement_Claim_Relationship_Type_Cd "PK"
        Date Agreement_Claim_Relationship_Start_Dt "PK"
        Date Agreement_Claim_Relationship_End_Dt ""
    }
    AGREEMENT_CLAIM_RELATIONSHIP_TYPE {
        Code Agreement_Claim_Relationship_Type_Cd "PK"
        Description Agreement_Claim_Relationship_Type_Desc ""
    }
    AGREEMENT_CLASS_ADJUSTMENT_PARAMETER {
        Code Agreement_Class_Value_Cd "PK"
        Code Agreement_Class_Cd "PK"
        Code Risk_Adjustment_Metric_Type_Cd "PK"
        Datetime Agreement_Class_Adjustment_Start_Dttm "PK"
        Datetime Agreement_Class_Adjustment_End_Dttm ""
        string more "1 more"
    }
    AGREEMENT_CLASS_RISK_GRADE {
        Code Agreement_Class_Value_Cd "PK"
        Code Agreement_Class_Cd "PK"
        Identifier Risk_Grade_Scheme_Id "PK"
        Datetime Agreement_Class_Risk_Start_Dttm "PK"
        Identifier Risk_Grade_Id "PK"
        string more "2 more"
    }
    AGREEMENT_CLASS_SCHEME_TYPE {
        Code Agreement_Class_Cd "PK"
        Description Agreement_Class_Desc ""
        Code Parent_Agreement_Class_Cd ""
        Datetime Agreement_Class_Scheme_Start_Dttm ""
        Datetime Agreement_Class_Scheme_End_Dttm ""
    }
    AGREEMENT_CLASS_SUBJECT {
        Code Agreement_Class_Value_Cd "PK"
        Code Agreement_Class_Cd "PK"
    }
    AGREEMENT_CLASS_VALUE {
        Code Agreement_Class_Value_Cd "PK"
        Code Agreement_Class_Cd "PK"
        Code Parent_Agreement_Class_Value_Cd ""
        Description Agreement_Class_Value_Desc ""
        Measure Agreement_Class_From_Meas ""
        string more "5 more"
    }
    AGREEMENT_COLLATERAL_ITEM {
        Identifier Collateral_Item_Id "PK"
        Identifier Agreement_Id "PK"
        Date Agreement_Collateral_Item_Start_Dt "PK"
        Date Agreement_Collateral_Item_End_Dt ""
        Code Asset_Collateral_Role_Type_Cd ""
    }
    AGREEMENT_COLLECTION_STATUS {
        Identifier Agreement_Id "PK"
        Code Collection_Status_Type_Cd "PK"
        Code Past_Due_Amount_Type_Cd "PK"
        Datetime Collection_Status_Start_Dttm "PK"
        Datetime Collection_Status_End_Dttm ""
        string more "3 more"
    }
    AGREEMENT_COST {
        Identifier Agreement_Id "PK"
        Code Cost_Type_Cd "PK"
        Datetime Agreement_Cost_Start_Dttm "PK"
        Datetime Agreement_Cost_End_Dttm ""
        Code Agreement_Cost_Time_Period_Cd "PK"
        string more "2 more"
    }
    AGREEMENT_COVERAGE_EVENT {
        Identifier Agreement_Id "PK"
        Identifier Insurable_Interest_Id "PK"
        Code Policy_Insurable_Interest_Role_Cd "PK"
        Datetime Policy_Insurable_Interest_Start_Dttm "PK"
        Datetime Insurable_Coverage_Start_Dttm "PK"
        string more "4 more"
    }
    AGREEMENT_COVERAGE_EVENT_BASE_TYPE {
        Code Agreement_Coverage_Event_Base_Cd "PK"
        Description Agreement_Coverage_Event_Base_Desc ""
    }
    AGREEMENT_COVERAGE_EVENT_CATEGORY {
        Code Agreement_Coverage_Event_Category_Cd "PK"
        Description Agreement_Coverage_Event_Category_Desc ""
    }
    AGREEMENT_COVERAGE_EVENT_TYPE {
        Code Agreement_Coverage_Event_Type_Cd "PK"
        Description Agreement_Coverage_Event_Type_Desc ""
    }
    AGREEMENT_CREDIT_REPORT {
        Identifier Reporting_Party_Id "PK"
        Identifier Obligor_Party_Id "PK"
        Datetime Credit_Report_Dttm "PK"
        Identifier Agreement_Id "PK"
        Code Credit_Report_Role_Type_Cd "PK"
    }
    AGREEMENT_CREDIT_RISK_TYPE_METRIC {
        Identifier Agreement_Id "PK"
        Identifier Risk_Scenario_Id "PK"
        Code Risk_Metric_Type_Cd "PK"
        Amount Agreement_Credit_Risk_Metric_Amt ""
        Rate Agreement_Credit_Risk_Metric_Rate ""
        string more "2 more"
    }
    AGREEMENT_CURRENCY {
        Code Currency_Use_Cd "PK"
        Identifier Agreement_Id "PK"
        Date Agreement_Currency_Start_Dt "PK"
        Code Agreement_Currency_Cd "PK"
        Date Agreement_Currency_End_Dt ""
    }
    AGREEMENT_DATE {
        Identifier Agreement_Id "PK"
        Code Agreement_Date_Type_Cd "PK"
        Date Agreement_Date_Change_Dt "PK"
        Date Agreement_Dt ""
    }
    AGREEMENT_DATE_TYPE {
        Code Agreement_Date_Type_Cd "PK"
        Description Agreement_Date_Type_Desc ""
    }
    AGREEMENT_DIRECT_EXPENSE {
        Code Unit_Cost_Type_Cd "PK"
        Identifier Agreement_Id "PK"
        Amount Direct_Expense_Amt ""
    }
    AGREEMENT_DOCUMENT {
        Identifier Document_Id "PK"
        Identifier Agreement_Id "PK"
    }
    AGREEMENT_EVENT {
        Identifier Agreement_Id "PK"
        Code Agreement_Event_Type_Cd "PK"
        Indicator Reward_Event_Ind ""
    }
    AGREEMENT_EVENT_TYPE {
        Code Agreement_Event_Type_Cd "PK"
        Description Agreement_Event_Type_Desc ""
    }
    AGREEMENT_FEATURE {
        Identifier Agreement_Id "PK"
        Identifier Feature_Id "PK"
        Code Agreement_Feature_Role_Cd "PK"
        Datetime Agreement_Feature_Start_Dttm "PK"
        Datetime Agreement_Feature_End_Dttm ""
        string more "11 more"
    }
    AGREEMENT_FEATURE_GROUP {
        Identifier Agreement_Id "PK"
        Identifier Feature_Group_Id "PK"
        Code Agreement_Feature_Group_Role_Cd "PK"
        Date Agreement_Feature_Group_Role_Start_Dt "PK"
        Date Agreement_Feature_Group_Role_End_Dt ""
    }
    AGREEMENT_FEATURE_GROUP_ROLE {
        Code Agreement_Feature_Group_Role_Cd "PK"
        Description Agreement_Feature_Group_Role_Desc ""
    }
    ACCOUNT ||--o{ PAYMENT_INSTRUCTION_ACCOUNT : ""
    ACCOUNT ||--o{ ACCOUNT_METRIC : ""
    ACCOUNT ||--o{ ACCOUNT_RENEWAL : ""
    ACCOUNT_INVOLVEMENT_SUBTYPE ||--o{ ACCOUNT : ""
    ACCOUNT_METRIC_TYPE ||--o{ ACCOUNT_METRIC : ""
    ACCOUNT_PURPOSE_SUBTYPE ||--o{ ACCOUNT : ""
    ACCOUNT_TYPE ||--o{ ACCOUNT : ""
    ACCOUNTING_TYPE ||--o{ ACCOUNTING_CURRENCY : ""
    ACCOUNTS_PAYABLE ||--o{ DEPRECIABLE_ASSET_ACCOUNT_PAYABLE : ""
    AGREEMENT ||--o{ AGREEMENT_METRIC : ""
    AGREEMENT ||--o{ AGREEMENT_SUMMARY : ""
    AGREEMENT ||--o{ AGREEMENT_TEXT : ""
    AGREEMENT ||--o{ INVESTMENT_AGREEMENT_ALLOCATION : ""
    AGREEMENT ||--o{ AGREEMENT_BALANCE_TYPE_METRIC : ""
    AGREEMENT ||--o{ AGREEMENT_COLLECTION_STATUS : ""
    AGREEMENT ||--o{ AGREEMENT_RENEWAL : ""
    AGREEMENT ||--o{ AGREEMENT_CREDIT_REPORT : ""
    AGREEMENT ||--o{ AGREEMENT_DATE : ""
    AGREEMENT ||--o{ AGREEMENT_METRIC_PROJECTION : ""
    AGREEMENT ||--o{ AGREEMENT_TAX_RULE : ""
    AGREEMENT ||--o{ AGREEMENT_PORTFOLIO_EVENT : ""
    AGREEMENT ||--o{ AGREEMENT_CHANNEL_TYPE : ""
    AGREEMENT ||--o{ ACCOUNT : ""
    AGREEMENT ||--o{ ALERT_SETUP_FOR_AGREEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_PROJECT : ""
    AGREEMENT ||--o{ AGREEMENT_FUNDING_SOURCE : ""
    AGREEMENT ||--o{ AGREEMENT_DOCUMENT : ""
    AGREEMENT ||--o{ PAYMENT_INSTRUCTION_AGREEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_FEATURE_GROUP : ""
    AGREEMENT ||--o{ AGREEMENT_SUBJECT : ""
    AGREEMENT ||--o{ AGREEMENT_FINANCIAL_RULE : ""
    AGREEMENT ||--o{ AGREEMENT_COLLATERAL_ITEM : ""
    AGREEMENT ||--o{ CELL_TARGET_AGREEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_CASE : ""
    AGREEMENT ||--o{ AGREEMENT_PROMOTION_OFFER : ""
    AGREEMENT ||--o{ PROPOSAL_AGREEMENT : ""
    AGREEMENT ||--o{ OPPORTUNITY_AGREEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_IVR_STEP_TRANSACTION : ""
    AGREEMENT ||--o{ AGREEMENT_AGREEMENT_GROUP : ""
    AGREEMENT ||--o{ CAMPAIGN_AGREEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_ABUSE : ""
    AGREEMENT ||--o{ TARGET_PROMOTION_AGREEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_LEGAL_ACTION : ""
    AGREEMENT ||--o{ AGREEMENT_RATE : ""
    AGREEMENT ||--o{ AGREEMENT_RISK_GRADE : ""
    AGREEMENT ||--o{ AGREEMENT_AGREEMENT_CLASS_XREF : ""
    AGREEMENT ||--o{ AGREEMENT_CHART_OF_ACCOUNTS : ""
    AGREEMENT ||--o{ AGREEMENT_PRIVACY_PREFERENCE : ""
    AGREEMENT ||--o{ AGREEMENT_PROFIT_COMPONENT : ""
    AGREEMENT ||--o{ AGREEMENT_FEATURE : ""
    AGREEMENT ||--o{ AGREEMENT_INDIRECT_EXPENSE : ""
    AGREEMENT ||--o{ AGREEMENT_DIRECT_EXPENSE : ""
    AGREEMENT ||--o{ AGREEMENT_EVENT : ""
    AGREEMENT ||--o{ AGREEMENT_ASSET : ""
    AGREEMENT ||--o{ QUOTATION_AGREEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_CURRENCY : ""
    AGREEMENT ||--o{ AGREEMENT_CHANNEL : ""
    AGREEMENT ||--o{ AGREEMENT_SURVEY_RESPONSE : ""
    AGREEMENT ||--o{ AGREEMENT_APPLICATION : ""
    AGREEMENT ||--o{ AGREEMENT_REVENUE : ""
    AGREEMENT ||--o{ AGREEMENT_STATEMENT : ""
    AGREEMENT ||--o{ AGREEMENT_PAYMENT_OPTION : ""
    AGREEMENT ||--o{ AGREEMENT_SCORE : ""
    AGREEMENT ||--o{ AGREEMENT_PROFIT : ""
    AGREEMENT ||--o{ AGREEMENT_PRODUCT : ""
    AGREEMENT ||--o{ AGREEMENT_REMEDIATION_PLAN : ""
    AGREEMENT ||--o{ AGREEMENT_PROVISION : ""
    AGREEMENT ||--o{ AGREEMENT_ACCESS_DEVICE : ""
    AGREEMENT ||--o{ AGREEMENT_COST : ""
    AGREEMENT ||--o{ AGREEMENT_STATUS : ""
    AGREEMENT ||--o{ AGREEMENT_PORTFOLIO : ""
    AGREEMENT ||--o{ AGREEMENT_INSURANCE_RISK_CATEGORY : ""
    AGREEMENT_ACCESS_DEVICE ||--o{ AGREEMENT_ACCESS_DEVICE_FEATURE : ""
    AGREEMENT_ACCESS_DEVICE_TYPE ||--o{ AGREEMENT_ACCESS_DEVICE : ""
    AGREEMENT_AGREEMENT_GROUP_SUBTYPE ||--o{ AGREEMENT_AGREEMENT_GROUP : ""
    AGREEMENT_APPLICATION_ROLE ||--o{ AGREEMENT_APPLICATION : ""
    AGREEMENT_ASSET_ROLE_SUBTYPE ||--o{ AGREEMENT_ASSET : ""
    AGREEMENT_CHANNEL_ROLE_TYPE ||--o{ AGREEMENT_CHANNEL_TYPE : ""
    AGREEMENT_CHANNEL_ROLE_TYPE ||--o{ AGREEMENT_CHANNEL : ""
    AGREEMENT_CLAIM_RELATIONSHIP_TYPE ||--o{ AGREEMENT_CLAIM : ""
    AGREEMENT_CLASS_SCHEME_TYPE ||--o{ PRODUCT_TO_AGREEMENT_CLASS_VALUE : ""
    AGREEMENT_CLASS_SCHEME_TYPE ||--o{ AGREEMENT_AGREEMENT_CLASS_XREF : ""
    AGREEMENT_CLASS_SCHEME_TYPE ||--o{ AGREEMENT_CLASS_VALUE : ""
    AGREEMENT_CLASS_SCHEME_TYPE ||--o{ AGREEMENT_CLASS_SCHEME_TYPE : ""
    AGREEMENT_CLASS_VALUE ||--o{ BASEL_II_LGD_NO_COLLATERAL_PARAMETER : ""
    AGREEMENT_CLASS_VALUE ||--o{ PRODUCT_TO_AGREEMENT_CLASS_VALUE : ""
    AGREEMENT_CLASS_VALUE ||--o{ AGREEMENT_CLASS_SUBJECT : ""
    AGREEMENT_CLASS_VALUE ||--o{ AGREEMENT_AGREEMENT_CLASS_XREF : ""
    AGREEMENT_CLASS_VALUE ||--o{ AGREEMENT_CLASS_RISK_GRADE : ""
    AGREEMENT_CLASS_VALUE ||--o{ AGREEMENT_CLASS_ADJUSTMENT_PARAMETER : ""
    AGREEMENT_CLASS_VALUE ||--o{ AGREEMENT_CLASS_VALUE : ""
    AGREEMENT_COVERAGE_EVENT_BASE_TYPE ||--o{ AGREEMENT_COVERAGE_EVENT : ""
    AGREEMENT_COVERAGE_EVENT_CATEGORY ||--o{ AGREEMENT_COVERAGE_EVENT : ""
    AGREEMENT_COVERAGE_EVENT_TYPE ||--o{ AGREEMENT_COVERAGE_EVENT : ""
    AGREEMENT_DATE_TYPE ||--o{ AGREEMENT_DATE : ""
    AGREEMENT_EVENT_TYPE ||--o{ AGREEMENT_EVENT : ""
    AGREEMENT_FEATURE ||--o{ AGREEMENT_FEATURE_METRIC : ""
    AGREEMENT_FEATURE ||--o{ AGREEMENT_FEATURE_RELATED : ""
    AGREEMENT_FEATURE_GROUP_ROLE ||--o{ AGREEMENT_FEATURE_GROUP : ""
    AGREEMENT_FEATURE_METRIC_TYPE ||--o{ AGREEMENT_FEATURE_METRIC : ""
    AGREEMENT_FEATURE_ROLE_TYPE ||--o{ AGREEMENT_PRODUCT_FEATURE : ""
    AGREEMENT_FEATURE_ROLE_TYPE ||--o{ AGREEMENT_FEATURE : ""
    AGREEMENT_FEATURE_ROLE_TYPE ||--o{ AGREEMENT_FEATURE_RELATED : ""
    AGREEMENT_FEATURE_ROLE_TYPE ||--o{ AGREEMENT_PRODUCT_FEATURE_RELATED : ""
    AGREEMENT_FORMAT_TYPE ||--o{ AGREEMENT : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_TEXT : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_SUBJECT : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_CHART_OF_ACCOUNTS : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_METRIC : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_RISK_TYPE_METRIC : ""
    AGREEMENT_GROUP ||--o{ STRESS_TEST_AGREEMENT_GROUP : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_LIMIT : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_RISK_GRADE : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_SCORE : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_TYPE_XREF : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_BALANCE : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_CRITERION : ""
    AGREEMENT_GROUP ||--o{ TARGET_PROMOTION_AGREEMENT_GROUP : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_FEATURE : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_AGREEMENT_GROUP : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_EVENT : ""
    AGREEMENT_GROUP ||--o{ AGREEMENT_GROUP_RISK : ""
    AGREEMENT_GROUP_FEATURE_ROLE ||--o{ AGREEMENT_GROUP_FEATURE : ""
    AGREEMENT_GROUP_METRIC_TYPE ||--o{ AGREEMENT_GROUP_RELATED_METRIC : ""
    AGREEMENT_GROUP_METRIC_TYPE ||--o{ AGREEMENT_GROUP_METRIC : ""
    AGREEMENT_GROUP_REASON_TYPE ||--o{ AGREEMENT_GROUP : ""
    AGREEMENT_GROUP_RELATED ||--o{ AGREEMENT_GROUP_RELATED_METRIC : ""
    AGREEMENT_GROUP_RELATED_ROLE ||--o{ AGREEMENT_GROUP_RELATED : ""
    AGREEMENT_GROUP_TYPE ||--o{ AGREEMENT_GROUP_TYPE_XREF : ""
    AGREEMENT_ID_TYPE_JAPAN ||--o{ FINANCIAL_AGREEMENT_JAPAN : ""
    AGREEMENT_INSURED_ASSET ||--o{ AGREEMENT_INSURED_ASSET_FEATURE : ""
    AGREEMENT_INSURED_ASSET ||--o{ AGREEMENT_INSURED_ASSET_COST : ""
    AGREEMENT_INSURED_ASSET_FEATURE ||--o{ AGREEMENT_INSURED_ASSET_FEATURE_RELATED : ""
    AGREEMENT_LIMIT ||--o{ AGREEMENT_LIMIT_METRIC : ""
    AGREEMENT_METRIC_TYPE ||--o{ AGREEMENT_METRIC : ""
    AGREEMENT_METRIC_TYPE ||--o{ AGREEMENT_METRIC_PROJECTION : ""
    AGREEMENT_METRIC_TYPE ||--o{ AGREEMENT_BALANCE_TYPE_METRIC : ""
    AGREEMENT_OBJECTIVE_TYPE ||--o{ AGREEMENT : ""
    AGREEMENT_OBTAINED_TYPE ||--o{ AGREEMENT : ""
    AGREEMENT_PORTFOLIO ||--o{ PORTFOLIO_PRODUCT_AGREEMENT_HOLDING : ""
    AGREEMENT_PORTFOLIO_RELATIONSHIP_TYPE ||--o{ AGREEMENT_PORTFOLIO : ""
    AGREEMENT_PRODUCT ||--o{ AGREEMENT_PRODUCT_FEATURE : ""
    AGREEMENT_PRODUCT_FEATURE ||--o{ AGREEMENT_PRODUCT_FEATURE_RELATED : ""
    AGREEMENT_PRODUCT_ROLE_TYPE ||--o{ AGREEMENT_PRODUCT : ""
    AGREEMENT_PROJECT_ROLE ||--o{ AGREEMENT_PROJECT : ""
    AGREEMENT_PROMOTION_OFFER_ROLE_TYPE ||--o{ AGREEMENT_PROMOTION_OFFER : ""
    AGREEMENT_QUOTATION_ROLE ||--o{ QUOTATION_AGREEMENT : ""
    AGREEMENT_RELATED_REASON ||--o{ AGREEMENT_RELATED : ""
    AGREEMENT_REMEDIATION_PLAN ||--o{ AGREEMENT_REMEDIATION_STATUS : ""
    AGREEMENT_REMEDIATION_PLAN ||--o{ LOAN_RESTRUCTURE : ""
    AGREEMENT_REMEDIATION_PLAN ||--o{ LOAN_MODIFICATION : ""
    AGREEMENT_STATEMENT ||--o{ AGREEMENT_STATEMENT_METRIC : ""
    AGREEMENT_STATEMENT ||--o{ AGREEMENT_STATEMENT_LINE_ITEM : ""
    AGREEMENT_STATEMENT_LINE_AMOUNT_TYPE ||--o{ AGREEMENT_STATEMENT_LINE_ITEM : ""
    AGREEMENT_STATEMENT_LINE_ITEM ||--o{ AGREEMENT_STATEMENT_LINE_METRIC : ""
    AGREEMENT_STATEMENT_LINE_ITEM_SUBTYPE ||--o{ AGREEMENT_STATEMENT_LINE_ITEM : ""
    AGREEMENT_STATUS_REASON_TYPE ||--o{ AGREEMENT_STATUS : ""
    AGREEMENT_STATUS_SCHEME_TYPE ||--o{ AGREEMENT_STATUS : ""
    AGREEMENT_STATUS_SCHEME_TYPE ||--o{ AGREEMENT_STATUS_TYPE : ""
    AGREEMENT_STATUS_TYPE ||--o{ AGREEMENT_STATUS : ""
    AGREEMENT_SUBTYPE ||--o{ AGREEMENT : ""
    AGREEMENT_TEXT ||--o{ AGREEMENT_TEXT_SECTION : ""
    AGREEMENT_TYPE ||--o{ AGREEMENT : ""
    ASSET_ACCOUNT_SUBTYPE ||--o{ ASSET_ACCOUNT : ""
    ASSET_COLLATERAL_ROLE_TYPE ||--o{ AGREEMENT_COLLATERAL_ITEM : ""
    ASSET_COLLATERAL_ROLE_TYPE ||--o{ PORTFOLIO_COLLATERAL_ITEM : ""
    ASSET_COLLATERAL_ROLE_TYPE ||--o{ ASSET_COLLATERAL_ITEM : ""
    BALANCE_SHEET_GL_MAIN_ACCOUNT_TYPE ||--o{ BALANCE_SHEET_GL_MAIN_ACCOUNT : ""
    CAMPAIGN_AGREEMENT_ROLE_TYPE ||--o{ CAMPAIGN_AGREEMENT : ""
    CHART_OF_ACCOUNTS_CODE ||--o{ CHART_OF_ACCOUNTS_CODE_TO_SEGMENT : ""
    CHART_OF_ACCOUNTS_CODE ||--o{ PROJECT_TASK_CHART_OF_ACCOUNTS : ""
    CHART_OF_ACCOUNTS_CODE ||--o{ AGREEMENT_GROUP_CHART_OF_ACCOUNTS : ""
    CHART_OF_ACCOUNTS_CODE ||--o{ AGREEMENT_CHART_OF_ACCOUNTS : ""
    COLLATERAL_AGREEMENT_TYPE ||--o{ COLLATERAL_AGREEMENT : ""
    COLLATERAL_ITEM ||--o{ AGREEMENT_COLLATERAL_ITEM : ""
    COLLATERAL_ITEM ||--o{ ASSET_COLLATERAL_ITEM : ""
    COLLATERAL_ITEM ||--o{ PORTFOLIO_COLLATERAL_ITEM : ""
    COLLATERAL_ITEM ||--o{ COLLATERAL_ITEM_STATUS : ""
    COLLATERAL_ITEM ||--o{ COLLATERAL_ITEM_GROUPED : ""
    COLLATERAL_ITEM ||--o{ COLLATERAL_ITEM_RISK_METRIC : ""
    COLLATERAL_ITEM ||--o{ RISK_MITIGANT_AGREEMENT_ITEM : ""
    COLLATERAL_ITEM ||--o{ EXPOSURE_AGREEMENT_COLLATERAL_ITEM : ""
    COLLATERAL_ITEM ||--o{ COLLATERAL_ITEM_CLASS_XREF : ""
    COLLATERAL_ITEM ||--o{ COLLATERAL_ITEM_VALUE : ""
    COLLATERAL_ITEM_GROUP ||--o{ COLLATERAL_ITEM_GROUPED : ""
    COLLATERAL_ITEM_STATUS_TYPE ||--o{ COLLATERAL_ITEM_STATUS : ""
    COLLATERAL_ITEM_TYPE ||--o{ COLLATERAL_ITEM : ""
    COLLATERAL_ITEM_VALUE ||--o{ COLLATERAL_ITEM_ADJUSTMENT : ""
    COLLATERALIZED_EXPOSURE ||--o{ COLLATERALIZED_EXPOSURE_ADJUSTMENT : ""
    COMMON_STOCK_ACCOUNT_TYPE ||--o{ COMMON_STOCK_ACCOUNT : ""
    COMMUNICATION_COLLATERAL ||--o{ CAMPAIGN_COLLATERAL : ""
    COMMUNICATION_COLLATERAL ||--o{ PROMOTION_COLLATERAL : ""
    COMMUNICATION_COLLATERAL ||--o{ OFFER_COLLATERAL : ""
    COMMUNICATION_COLLATERAL_TYPE ||--o{ COMMUNICATION_COLLATERAL : ""
    CONSUMER_SERVICE_AGREEMENT_TYPE ||--o{ CONSUMER_SERVICE_AGREEMENT : ""
    CONTRACT_SETTLEMENT_TYPE ||--o{ CREDIT_DEFAULT_SWAP : ""
    CONTRACT_SETTLEMENT_TYPE ||--o{ FUTURES_AGREEMENT : ""
    CONTRACT_SETTLEMENT_TYPE ||--o{ FORWARD_CONTRACT : ""
    CREDIT_AGREEMENT ||--o{ LOAN_RESTRUCTURE : ""
    CREDIT_AGREEMENT ||--o{ LOAN_REVIEW : ""
    CREDIT_AGREEMENT ||--o{ LOAN_MODIFICATION : ""
    CREDIT_AGREEMENT ||--o{ CREDIT_AGREEMENT_SECONDARY_MARKET_STATUS : ""
    CREDIT_AGREEMENT_SUBTYPE ||--o{ CREDIT_AGREEMENT : ""
    CREDIT_APPLICATION ||--o{ CREDIT_APPLICATION_PRECREDIT_CHARGE : ""
    CREDIT_CARD_AGREEMENT_SUBTYPE ||--o{ CREDIT_CARD_AGREEMENT : ""
    CREDIT_CARD_SUBTYPE ||--o{ CREDIT_CARD : ""
    CREDIT_DERIVATIVE_SUBTYPE ||--o{ CREDIT_DERIVATIVE_PRODUCT : ""
    CREDIT_DERIVATIVE_SUBTYPE ||--o{ CREDIT_DERIVATIVE_AGREEMENT : ""
    CREDIT_EVENT_TYPE ||--o{ CREDIT_DEFAULT_SWAP : ""
    CREDIT_REPORT_ROLE_TYPE ||--o{ APPLICATION_CREDIT_REPORT : ""
    CREDIT_REPORT_ROLE_TYPE ||--o{ AGREEMENT_CREDIT_REPORT : ""
    CURRENT_ASSET_ACCOUNT_SUBTYPE ||--o{ CURRENT_ASSET_ACCOUNT : ""
    CURRENT_LIABILITY_ACCOUNT_TYPE ||--o{ CURRENT_LIABILITY_ACCOUNT : ""
    DEBT_RECEIVABLE_AGREEMENT_TYPE ||--o{ PURCHASED_RECEIVABLE_ISSUER_AGREEMENT : ""
    DEPOSIT_BOX_SIZE_TYPE ||--o{ SAFE_DEPOSIT_AGREEMENT : ""
    DEPOSIT_MATURITY_SUBTYPE ||--o{ DEPOSIT_AGREEMENT : ""
    DEPOSIT_OWNERSHIP_TYPE ||--o{ DEPOSIT_AGREEMENT : ""
    DEPOSIT_SLIP_TRANSACTION_TYPE ||--o{ DEPOSIT_SLIP : ""
    DEPRECIABLE_ASSET_ACCOUNT ||--o{ DEPRECIABLE_ASSET_ACCOUNT_PAYABLE : ""
    DIVIDEND_EQUITY_ACCOUNT_TYPE ||--o{ DIVIDEND_EQUITY_ACCOUNT : ""
    EQUITY_ACCOUNT_TYPE ||--o{ EQUITY_ACCOUNT : ""
    EXPENSE_ACCOUNT ||--o{ EXPENSE_ACCOUNT_COST_TYPE_XREF : ""
    EXPENSE_ACCOUNT_SUBTYPE ||--o{ EXPENSE_ACCOUNT : ""
    EXPOSURE_AGREEMENT_ASSET_VALUE ||--o{ EXPOSURE_AGREEMENT_ASSET_VALUE_ADJUSTMENT : ""
    EXPOSURE_AGREEMENT_COLLATERAL_ITEM ||--o{ EXPOSURE_AGREEMENT_ASSET_VALUE : ""
    EXPOSURE_AGREEMENT_RISK_MITIGANT_AGREEMENT ||--o{ COLLATERALIZED_EXPOSURE : ""
    EXTERNAL_AGREEMENT_TYPE ||--o{ EXTERNAL_AGREEMENT : ""
    FINANCE_EXPOSURE_AGREEMENT ||--o{ EXPOSURE_AGREEMENT_COLLATERAL_ITEM : ""
    FINANCIAL_AGREEMENT ||--o{ TRANCHE_TO_AGREEMENT : ""
    FINANCIAL_AGREEMENT ||--o{ AGREEMENT_MARKET_RISK_TYPE : ""
    FINANCIAL_AGREEMENT ||--o{ AGREEMENT_MARKET_RISK_FACTOR : ""
    FINANCIAL_AGREEMENT ||--o{ FINANCIAL_AGREEMENT_PASSBOOK : ""
    FINANCIAL_AGREEMENT ||--o{ AGREEMENT_CREDIT_RISK_TYPE_METRIC : ""
    FINANCIAL_AGREEMENT ||--o{ AGREEMENT_RISK_METRIC : ""
    FINANCIAL_AGREEMENT ||--o{ FINANCIAL_AGREEMENT_ADJUSTMENT : ""
    FINANCIAL_AGREEMENT ||--o{ AGREEMENT_LIMIT : ""
    FINANCIAL_AGREEMENT ||--o{ FINANCIAL_AGREEMENT_BASEL_II_APPROACH : ""
    FINANCIAL_AGREEMENT_SUBTYPE ||--o{ FINANCIAL_AGREEMENT : ""
    FINANCIAL_AGREEMENT_TYPE ||--o{ FINANCIAL_AGREEMENT : ""
    FINANCIAL_AGREEMENT_TYPE_JAPAN ||--o{ FINANCIAL_AGREEMENT_JAPAN : ""
    FIXED_ASSET_ACCOUNT_SUBTYPE ||--o{ FIXED_ASSET_ACCOUNT : ""
    FX_AGREEMENT_TYPE ||--o{ FOREIGN_EXCHANGE_AGREEMENT : ""
    GL_MAIN_ACCOUNT ||--o{ GL_MAIN_ACCOUNT_CLASS_XREF : ""
    GL_MAIN_ACCOUNT ||--o{ GL_ACCOUNT_COA_CODE_SEGMENT : ""
    GL_MAIN_ACCOUNT ||--o{ GL_MAIN_ACCOUNT_STATUS : ""
    GL_MAIN_ACCOUNT ||--o{ GL_MAIN_ACCOUNT : ""
    GL_MAIN_ACCOUNT ||--o{ GL_MAIN_ACCOUNT_SET_OF_BOOKS_XREF : ""
    GL_MAIN_ACCOUNT_CATEGORY ||--o{ GL_MAIN_ACCOUNT : ""
    GL_MAIN_ACCOUNT_CLASS_VALUE ||--o{ GL_MAIN_ACCOUNT_CLASS_XREF : ""
    GL_MAIN_ACCOUNT_CLASS_VALUE ||--o{ GL_MAIN_ACCOUNT_CLASS_VALUE : ""
    GL_MAIN_ACCOUNT_SCHEME_TYPE ||--o{ GL_MAIN_ACCOUNT_SCHEME_TYPE : ""
    GL_MAIN_ACCOUNT_SCHEME_TYPE ||--o{ GL_MAIN_ACCOUNT_CLASS_XREF : ""
    GL_MAIN_ACCOUNT_SCHEME_TYPE ||--o{ GL_MAIN_ACCOUNT_CLASS_VALUE : ""
    GL_MAIN_ACCOUNT_SEGMENT ||--o{ AGREEMENT_BALANCE_TYPE_METRIC : ""
    GL_MAIN_ACCOUNT_SEGMENT ||--o{ AGREEMENT_METRIC : ""
    GL_MAIN_ACCOUNT_STATUS_TYPE ||--o{ GL_MAIN_ACCOUNT_STATUS : ""
    INCOME_STATEMENT_GL_MAIN_ACCOUNT_TYPE ||--o{ INCOME_STATEMENT_GL_MAIN_ACCOUNT : ""
    INSURANCE_AGREEMENT ||--o{ AGREEMENT_CLAIM : ""
    INSURANCE_AGREEMENT_SUBTYPE ||--o{ INSURANCE_AGREEMENT : ""
    INSURANCE_AGREEMENT_TYPE ||--o{ INSURANCE_AGREEMENT : ""
    INTANGIBLE_ASSET_ACCOUNT_SUBTYPE ||--o{ INTANGIBLE_ASSET_ACCOUNT : ""
    INVESTMENT_AGREEMENT ||--o{ TRADE_SETTLEMENT_INSTRUCTION : ""
    INVESTMENT_AGREEMENT ||--o{ TRADE_SETTLEMENT_PRODUCT_GROUP : ""
    LABOR_AGREEMENT ||--o{ POSITION_LABOR_AGREEMENT : ""
    LEASE_TYPE ||--o{ LEASE_AGREEMENT : ""
    LIABILITY_ACCOUNT_SUBTYPE ||--o{ LIABILITY_ACCOUNT : ""
    LOAN_AGREEMENT ||--o{ WORK_PROCESS_LOAN : ""
    LOAN_CHANGE_REASON ||--o{ LOAN_RESTRUCTURE : ""
    LOAN_CHANGE_REASON ||--o{ LOAN_MODIFICATION : ""
    LOAN_MATURITY_SUBTYPE ||--o{ LOAN_AGREEMENT : ""
    LOAN_MODIFICATION_TYPE ||--o{ LOAN_MODIFICATION : ""
    LOAN_PROVISION_BALANCE ||--o{ LOAN_PROVISION_CHANGE : ""
    LOAN_REVIEW_RESULT_TYPE ||--o{ LOAN_REVIEW : ""
    LOAN_REVIEW_TYPE ||--o{ LOAN_REVIEW : ""
    LOAN_TERM_SUBTYPE ||--o{ LOAN_TERM_AGREEMENT : ""
    LOAN_TRANSACTION_SUBTYPE ||--o{ LOAN_TRANSACTION_AGREEMENT : ""
    LOYALTY_ACCOUNT_EARNING_TYPE ||--o{ LOYALTY_ACCOUNT_EARNING : ""
    LOYALTY_AGREEMENT ||--o{ LOYALTY_AGREEMENT_LEVEL : ""
    MORTGAGE_TYPE ||--o{ MORTGAGE_AGREEMENT : ""
    NETTING_AGREEMENT_TYPE ||--o{ NETTING_AGREEMENT : ""
    NETWORK_SERVICE_AGREEMENT_SUBTYPE ||--o{ NETWORK_SERVICE_AGREEMENT : ""
    NONCURRENT_LIABILITY_ACCOUNT_SUBTYPE ||--o{ NONCURRENT_LIABILITY_ACCOUNT : ""
    NONDIVIDEND_EQUITY_ACCOUNT_TYPE ||--o{ NONDIVIDEND_EQUITY_ACCOUNT : ""
    OFF_BALANCE_SHEET_SECURITIZATION_TYPE ||--o{ SECURITIZATION_POOL : ""
    OPERATING_EXPENSE_ACCOUNT_SUBTYPE ||--o{ OPERATING_EXPENSE_ACCOUNT : ""
    OTHER_ASSET_ACCOUNT_SUBTYPE ||--o{ OTHER_ASSET_ACCOUNT : ""
    OTHER_EXPENSE_ACCOUNT_SUBTYPE ||--o{ OTHER_EXPENSE_ACCOUNT : ""
    OTHER_LIABILITY_ACCOUNT_SUBTYPE ||--o{ OTHER_LIABILITY_ACCOUNT : ""
    PAYMENT_INSTRUCTION_AGREEMENT_ROLE ||--o{ PAYMENT_INSTRUCTION_ACCOUNT : ""
    PAYMENT_INSTRUCTION_AGREEMENT_ROLE ||--o{ PAYMENT_INSTRUCTION_AGREEMENT : ""
    PO_DELIVERY_RELEASE ||--o{ PO_DELIVERY_RELEASE_LINE_ITEM : ""
    PO_DELIVERY_RELEASE_LINE_ITEM ||--o{ PO_DELIVERY_RELEASE_STATUS : ""
    PO_DELIVERY_RELEASE_LINE_ITEM ||--o{ PO_LINE_DELIVERY_RELEASE_LINE : ""
    PO_RELEASE_STATUS_REASON_TYPE ||--o{ PO_DELIVERY_RELEASE_STATUS : ""
    PO_RELEASE_STATUS_TYPE ||--o{ PO_DELIVERY_RELEASE_STATUS : ""
    PORTFOLIO_PRODUCT_AGREEMENT_HOLDING ||--o{ PORTFOLIO_COLLATERAL_ITEM : ""
    PORTFOLIO_PRODUCT_AGREEMENT_HOLDING ||--o{ PORTFOLIO_PRODUCT_AGREEMENT_HOLDING_QUANTITY : ""
    PORTFOLIO_PRODUCT_AGREEMENT_HOLDING ||--o{ PORTFOLIO_PRODUCT_AGREEMENT_HOLDING_VALUE : ""
    PRECREDIT_TYPE ||--o{ CREDIT_APPLICATION_PRECREDIT_CHARGE : ""
    PURCHASED_RECEIVABLE_ISSUER_AGREEMENT ||--o{ PURCHASED_RECEIVABLE_ISSUER_DEBTOR_AGREEMENT : ""
    REINSURANCE_AGREEMENT ||--o{ REINSURANCE_AGREEMENT_RESTRICTION : ""
    REINSURANCE_CONTRACT_TYPE ||--o{ REINSURANCE_AGREEMENT : ""
    RELEASE_TYPE ||--o{ PO_DELIVERY_RELEASE : ""
    REPURCHASE_AGREEMENT_TYPE ||--o{ REPURCHASE_AGREEMENT : ""
    REVENUE_ACCOUNT ||--o{ REVENUE_ACCOUNT_REVENUE_TYPE_XREF : ""
    REVENUE_ACCOUNT_SUBTYPE ||--o{ REVENUE_ACCOUNT : ""
    RISK_MITIGANT_AGREEMENT ||--o{ RISK_MITIGANT_AGREEMENT_ITEM : ""
    RISK_MITIGANT_AGREEMENT_ITEM ||--o{ COLLATERAL_AGREEMENT_COVERAGE : ""
    RISK_MITIGANT_AGREEMENT_RELATED ||--o{ RISK_MITIGANT_AGREEMENT_SENIORITY : ""
    RISK_MITIGANT_AGREEMENT_SUBTYPE ||--o{ RISK_MITIGANT_AGREEMENT : ""
    SEARCH_ENGINE_SYSTEM_ACCOUNT ||--o{ SEARCH_ENGINE_ACCOUNT_CAMPAIGN_XREF : ""
    SECURITIZATION_CLEAN_UP_CALL_TYPE ||--o{ SECURITIZATION_SELL_AGREEMENT : ""
    SECURITIZATION_POOL ||--o{ SECURITIZATION_POOL_OBLIGOR_METRIC : ""
    SECURITIZATION_POOL ||--o{ SECURITIZATION_POOL_RISK : ""
    SECURITIZATION_POOL_STRUCTURE_TYPE ||--o{ SECURITIZATION_POOL : ""
    SECURITIZATION_ROLE ||--o{ SECURITIZATION_EXPOSURE : ""
    SECURITIZATION_TYPE ||--o{ SECURITIZATION_POOL : ""
    SETTLEMENT_DELIVERY_TYPE ||--o{ TRADE_SETTLEMENT_INSTRUCTION : ""
    SETTLEMENT_DELIVERY_TYPE ||--o{ TRADE_SETTLEMENT_PRODUCT_GROUP : ""
    SETTLEMENT_DIRECTION_TYPE ||--o{ TRADE_SETTLEMENT_PRODUCT_GROUP : ""
    SETTLEMENT_DIRECTION_TYPE ||--o{ TRADE_SETTLEMENT_INSTRUCTION : ""
    SETTLEMENT_PRODUCT_REASON_TYPE ||--o{ TRADE_SETTLEMENT_PRODUCT_GROUP : ""
    SPLIT_SETTLEMENT_TYPE ||--o{ TRADE_SETTLEMENT_INSTRUCTION : ""
    SPLIT_SETTLEMENT_TYPE ||--o{ TRADE_SETTLEMENT_PRODUCT_GROUP : ""
    SWAP_AGREEMENT ||--o{ SWAP_AGREEMENT_LEG : ""
    SWAP_AGREEMENT_LEG ||--o{ SWAP_AGREEMENT_LEG_METRIC : ""
    SWAP_AGREEMENT_LEG ||--o{ SWAP_LEG_AGREEMENT_EVENT : ""
    TRANCHE_TO_AGREEMENT_ROLE_TYPE ||--o{ TRANCHE_TO_AGREEMENT : ""
    TRANSACTION_ACCOUNT_TYPE ||--o{ TRANSACTION_ACCOUNT : ""
    CURRENT_LIABILITY_ACCOUNT ||--|| ACCOUNTS_PAYABLE : "inherits"
    CURRENT_ASSET_ACCOUNT ||--|| ACCOUNTS_RECEIVABLE : "inherits"
    CURRENT_LIABILITY_ACCOUNT ||--|| ACCRUED_LIABILITY_ACCOUNT : "inherits"
    AGREEMENT_ASSET ||--|| AGREEMENT_INSURED_ASSET : "inherits"
    AGREEMENT_ASSET ||--|| AGREEMENT_LEASING_ASSET : "inherits"
    AGREEMENT_RISK_METRIC ||--|| AGREEMENT_RISK_METRIC_INTERNAL_INVESTMENT : "inherits"
    AGREEMENT_RISK_METRIC ||--|| AGREEMENT_RISK_METRIC_OFF_BALANCE_SHEET : "inherits"
    AGREEMENT_RISK_METRIC ||--|| AGREEMENT_RISK_METRIC_OTC_DERIVATIVE : "inherits"
    AGREEMENT_RISK_METRIC ||--|| AGREEMENT_RISK_METRIC_PURCHASED_RECEIVABLE : "inherits"
    AGREEMENT_RISK_METRIC ||--|| AGREEMENT_RISK_METRIC_SECURITIZATION : "inherits"
    AGREEMENT_AGREEMENT_GROUP ||--|| AGREEMENT_TO_AGREEMENT_GROUP_OTHER : "inherits"
    AGREEMENT_AGREEMENT_GROUP ||--|| AGREEMENT_TO_SECURITIZATION_POOL : "inherits"
    ASSET_ACCOUNT ||--|| ALLOWANCE_FOR_LOAN_LOSS_ACCOUNT : "inherits"
    BALANCE_SHEET_GL_MAIN_ACCOUNT ||--|| ASSET_ACCOUNT : "inherits"
    CURRENT_ASSET_ACCOUNT ||--|| AVAILABLE_CASH_ACCOUNT : "inherits"
    GL_MAIN_ACCOUNT ||--|| BALANCE_SHEET_GL_MAIN_ACCOUNT : "inherits"
    OPTION_AGREEMENT ||--|| BARRIER_OPTION_AGREEMENT : "inherits"
    TRADE_SETTLEMENT_INSTRUCTION ||--|| CASH_SETTLEMENT : "inherits"
    CURRENT_LIABILITY_ACCOUNT ||--|| CHANGED_UNEARNED_PREMIUM_RESERVE_ACCOUNT : "inherits"
    RISK_MITIGANT_AGREEMENT ||--|| COLLATERAL_AGREEMENT : "inherits"
    AGREEMENT ||--|| COLLECTION_PAYMENT_AGREEMENT : "inherits"
    DERIVATIVE_AGREEMENT ||--|| COMMODITY_AGREEMENT : "inherits"
    DIVIDEND_EQUITY_ACCOUNT ||--|| COMMON_STOCK_ACCOUNT : "inherits"
    LOAN_TERM_AGREEMENT ||--|| CONSTRUCTION_LOAN : "inherits"
    EXPENSE_ACCOUNT ||--|| COST_OF_SALES_ACCOUNT : "inherits"
    FINANCIAL_AGREEMENT ||--|| CREDIT_AGREEMENT : "inherits"
    LOAN_TRANSACTION_AGREEMENT ||--|| CREDIT_CARD_AGREEMENT : "inherits"
    CREDIT_DERIVATIVE_AGREEMENT ||--|| CREDIT_DEFAULT_SWAP : "inherits"
    RISK_MITIGANT_AGREEMENT ||--|| CREDIT_DERIVATIVE_AGREEMENT : "inherits"
    CREDIT_DERIVATIVE_AGREEMENT ||--|| CREDIT_LINKED_NOTE : "inherits"
    CREDIT_AGREEMENT ||--|| CURRENT_AGREEMENT : "inherits"
    ASSET_ACCOUNT ||--|| CURRENT_ASSET_ACCOUNT : "inherits"
    LIABILITY_ACCOUNT ||--|| CURRENT_LIABILITY_ACCOUNT : "inherits"
    CURRENT_LIABILITY_ACCOUNT ||--|| CURRENT_LONG_TERM_DEBT_ACCOUNT : "inherits"
    OTHER_ASSET_ACCOUNT ||--|| DEFERRED_CHARGE_ACCOUNT : "inherits"
    NONCURRENT_LIABILITY_ACCOUNT ||--|| DEFERRED_INCOME_TAX_ACCOUNT : "inherits"
    CURRENT_LIABILITY_ACCOUNT ||--|| DEFERRED_REVENUE_ACCOUNT : "inherits"
    LIABILITY_ACCOUNT ||--|| DEPOSIT_GL_ACCOUNT : "inherits"
    DEPOSIT_AGREEMENT ||--|| DEPOSIT_TERM_AGREEMENT : "inherits"
    DEPOSIT_AGREEMENT ||--|| DEPOSIT_TRANSACTION_AGREEMENT : "inherits"
    FIXED_ASSET_ACCOUNT ||--|| DEPRECIABLE_ASSET_ACCOUNT : "inherits"
    INVESTMENT_AGREEMENT ||--|| DERIVATIVE_AGREEMENT : "inherits"
    EQUITY_ACCOUNT ||--|| DIVIDEND_EQUITY_ACCOUNT : "inherits"
    REVENUE_ACCOUNT ||--|| EARNED_PREMIUM_ACCOUNT : "inherits"
    BALANCE_SHEET_GL_MAIN_ACCOUNT ||--|| EQUITY_ACCOUNT : "inherits"
    EQUITY_ACCOUNT ||--|| EQUITY_SURPLUS_ACCOUNT : "inherits"
    INCOME_STATEMENT_GL_MAIN_ACCOUNT ||--|| EXPENSE_ACCOUNT : "inherits"
    AGREEMENT_RELATED ||--|| EXPOSURE_AGREEMENT_RISK_MITIGANT_AGREEMENT : "inherits"
    ACCOUNT ||--|| EXTERNAL_ACCOUNT : "inherits"
    AGREEMENT ||--|| EXTERNAL_AGREEMENT : "inherits"
    INVESTMENT_AGREEMENT ||--|| EXTERNAL_MARGIN_AGREEMENT : "inherits"
    CREDIT_AGREEMENT ||--|| FACILITY_AGREEMENT : "inherits"
    OPERATING_EXPENSE_ACCOUNT ||--|| FACILITY_OPERATING_EXPENSE_ACCOUNT : "inherits"
    FINANCIAL_AGREEMENT ||--|| FINANCE_EXPOSURE_AGREEMENT : "inherits"
    AGREEMENT ||--|| FINANCIAL_AGREEMENT : "inherits"
    AGREEMENT ||--|| FINANCIAL_AGREEMENT_JAPAN : "inherits"
    ASSET_ACCOUNT ||--|| FIXED_ASSET_ACCOUNT : "inherits"
    NONDIVIDEND_EQUITY_ACCOUNT ||--|| FOREIGN_CURRENCY_ADJUSTMENT_ACCOUNT : "inherits"
    INVESTMENT_AGREEMENT ||--|| FOREIGN_EXCHANGE_AGREEMENT : "inherits"
    DERIVATIVE_AGREEMENT ||--|| FORWARD_CONTRACT : "inherits"
    DERIVATIVE_AGREEMENT ||--|| FORWARD_RATE_AGREEMENT : "inherits"
    DERIVATIVE_AGREEMENT ||--|| FUTURES_AGREEMENT : "inherits"
    OPERATING_EXPENSE_ACCOUNT ||--|| GENERAL_AND_ADMINISTRATIVE_ACCOUNT : "inherits"
    INTANGIBLE_ASSET_ACCOUNT ||--|| GOODWILL_ACCOUNT : "inherits"
    LOAN_TRANSACTION_AGREEMENT ||--|| HOME_EQUITY_LINE_OF_CREDIT_AGREEMENT : "inherits"
    GL_MAIN_ACCOUNT ||--|| INCOME_STATEMENT_GL_MAIN_ACCOUNT : "inherits"
    EXPENSE_ACCOUNT ||--|| INCOME_TAX_ACCOUNT : "inherits"
    CURRENT_LIABILITY_ACCOUNT ||--|| INCOME_TAX_PAYABLE_ACCOUNT : "inherits"
    AGREEMENT ||--|| INSURANCE_AGREEMENT : "inherits"
    OTHER_ASSET_ACCOUNT ||--|| INTANGIBLE_ASSET_ACCOUNT : "inherits"
    FINANCIAL_AGREEMENT ||--|| INTEREST_BASED_AGREEMENT : "inherits"
    EXPENSE_ACCOUNT ||--|| INTEREST_EXPENSE_ACCOUNT : "inherits"
    REVENUE_ACCOUNT ||--|| INTEREST_INCOME_ACCOUNT : "inherits"
    ACCOUNT ||--|| INTERNAL_ACCOUNT : "inherits"
    FINANCIAL_AGREEMENT ||--|| INVESTMENT_AGREEMENT : "inherits"
    OTHER_ASSET_ACCOUNT ||--|| INVESTMENT_ASSET_ACCOUNT : "inherits"
    AGREEMENT ||--|| LABOR_AGREEMENT : "inherits"
    LOAN_TERM_AGREEMENT ||--|| LEASE_AGREEMENT : "inherits"
    CREDIT_AGREEMENT ||--|| LETTER_OF_CREDIT_AGREEMENT : "inherits"
    BALANCE_SHEET_GL_MAIN_ACCOUNT ||--|| LIABILITY_ACCOUNT : "inherits"
    INSURANCE_AGREEMENT ||--|| LIFE_LINE_AGREEMENT : "inherits"
    CREDIT_AGREEMENT ||--|| LOAN_AGREEMENT : "inherits"
    ASSET_ACCOUNT ||--|| LOAN_GL_ACCOUNT : "inherits"
    LOAN_AGREEMENT ||--|| LOAN_TERM_AGREEMENT : "inherits"
    LOAN_AGREEMENT ||--|| LOAN_TRANSACTION_AGREEMENT : "inherits"
    NONCURRENT_LIABILITY_ACCOUNT ||--|| LONG_TERM_DEBT_ACCOUNT : "inherits"
    OTHER_EXPENSE_ACCOUNT ||--|| LOSS_ADJUSTED_EXPENSE_ACCOUNT : "inherits"
    OTHER_LIABILITY_ACCOUNT ||--|| LOSS_ADJUSTED_RESERVE_ACCOUNT : "inherits"
    AGREEMENT ||--|| LOYALTY_AGREEMENT : "inherits"
    LOAN_TRANSACTION_AGREEMENT ||--|| MARGIN_AGREEMENT : "inherits"
    OPERATING_EXPENSE_ACCOUNT ||--|| MARKETING_EXPENSE_ACCOUNT : "inherits"
    NETWORK_SERVICE_AGREEMENT ||--|| MERCHANT_SERVICE_AGREEMENT : "inherits"
    LOAN_TERM_AGREEMENT ||--|| MORTGAGE_AGREEMENT : "inherits"
    LOAN_TERM_AGREEMENT ||--|| MOTOR_VEHICLE_LOAN_AGREEMENT : "inherits"
    INVESTMENT_AGREEMENT ||--|| NEGOTIABLE_CERTIFICATE_OF_DEPOSIT : "inherits"
    RISK_MITIGANT_AGREEMENT ||--|| NETTING_AGREEMENT : "inherits"
    NETWORK_SERVICE_AGREEMENT ||--|| NETWORK_PARTNER_AGREEMENT : "inherits"
    AGREEMENT ||--|| NETWORK_SERVICE_AGREEMENT : "inherits"
    LIABILITY_ACCOUNT ||--|| NONCURRENT_LIABILITY_ACCOUNT : "inherits"
    FIXED_ASSET_ACCOUNT ||--|| NONDEPRECIABLE_ASSET_ACCOUNT : "inherits"
    EQUITY_ACCOUNT ||--|| NONDIVIDEND_EQUITY_ACCOUNT : "inherits"
    EXPENSE_ACCOUNT ||--|| NONINTEREST_EXPENSE_ACCOUNT : "inherits"
    REVENUE_ACCOUNT ||--|| NONINTEREST_INCOME_ACCOUNT : "inherits"
    COMMON_STOCK_ACCOUNT ||--|| NONVOTING_STOCK_ACCOUNT : "inherits"
    EXPENSE_ACCOUNT ||--|| OPERATING_EXPENSE_ACCOUNT : "inherits"
    DERIVATIVE_AGREEMENT ||--|| OPTION_AGREEMENT : "inherits"
    ASSET_ACCOUNT ||--|| OTHER_ASSET_ACCOUNT : "inherits"
    CURRENT_ASSET_ACCOUNT ||--|| OTHER_CURRENT_ASSET_ACCOUNT : "inherits"
    EXPENSE_ACCOUNT ||--|| OTHER_EXPENSE_ACCOUNT : "inherits"
    LIABILITY_ACCOUNT ||--|| OTHER_LIABILITY_ACCOUNT : "inherits"
    OPERATING_EXPENSE_ACCOUNT ||--|| OTHER_OPERATING_EXPENSE_ACCOUNT : "inherits"
    REVENUE_ACCOUNT ||--|| OTHER_REVENUE_ACCOUNT : "inherits"
    INTANGIBLE_ASSET_ACCOUNT ||--|| PATENTS_ACCOUNT : "inherits"
    OTHER_LIABILITY_ACCOUNT ||--|| POLICY_HOLDER_FUND_ACCOUNT : "inherits"
    DIVIDEND_EQUITY_ACCOUNT ||--|| PREFERRED_STOCK_ACCOUNT : "inherits"
    REVENUE_ACCOUNT ||--|| PREMIUM_WRITTEN_ACCOUNT : "inherits"
    CURRENT_ASSET_ACCOUNT ||--|| PREPAID_EXPENSE_ACCOUNT : "inherits"
    INSURANCE_AGREEMENT ||--|| PROPERTY_CASUALTY_AGREEMENT : "inherits"
    OTHER_EXPENSE_ACCOUNT ||--|| PROVISION_FOR_LOAN_LOSS_ACCOUNT : "inherits"
    CREDIT_CARD_AGREEMENT ||--|| PURCHASE_TRANSACTION_AGREEMENT : "inherits"
    INSURANCE_AGREEMENT ||--|| REINSURANCE_AGREEMENT : "inherits"
    INVESTMENT_AGREEMENT ||--|| REPURCHASE_AGREEMENT : "inherits"
    OPERATING_EXPENSE_ACCOUNT ||--|| RESEARCH_DEVELOPMENT_EXPENSE_ACCOUNT : "inherits"
    NONCURRENT_LIABILITY_ACCOUNT ||--|| RESERVES_ACCOUNT : "inherits"
    NONDIVIDEND_EQUITY_ACCOUNT ||--|| RETAINED_EARNING_ACCOUNT : "inherits"
    INCOME_STATEMENT_GL_MAIN_ACCOUNT ||--|| REVENUE_ACCOUNT : "inherits"
    FINANCIAL_AGREEMENT ||--|| RISK_MITIGANT_AGREEMENT : "inherits"
    AGREEMENT_RELATED ||--|| RISK_MITIGANT_AGREEMENT_RELATED : "inherits"
    REVENUE_ACCOUNT ||--|| SALES_REVENUE_ACCOUNT : "inherits"
    CURRENT_ASSET_ACCOUNT ||--|| SECURITIES_ACCOUNT : "inherits"
    AGREEMENT_AGREEMENT_GROUP ||--|| SECURITIZATION_AGREEMENT_TO_SECURITIZATION_POOL : "inherits"
    AGREEMENT_GROUP ||--|| SECURITIZATION_POOL : "inherits"
    RISK_MITIGANT_AGREEMENT ||--|| SECURITIZATION_SELL_AGREEMENT : "inherits"
    OPERATING_EXPENSE_ACCOUNT ||--|| SELLING_EXPENSE_ACCOUNT : "inherits"
    CURRENT_LIABILITY_ACCOUNT ||--|| SHORT_TERM_DEBT_ACCOUNT : "inherits"
    DERIVATIVE_AGREEMENT ||--|| SWAP_AGREEMENT : "inherits"
    ACCOUNT ||--|| TRANSACTION_ACCOUNT : "inherits"
    NONDIVIDEND_EQUITY_ACCOUNT ||--|| TREASURY_STOCK_ACCOUNT : "inherits"
    OTHER_EXPENSE_ACCOUNT ||--|| UNDERWRITING_EXPENSE_ACCOUNT : "inherits"
    OTHER_LIABILITY_ACCOUNT ||--|| UNEARNED_PREMIUM_RESERVE_ACCOUNT : "inherits"
    CURRENT_LIABILITY_ACCOUNT ||--|| UNPAID_CLAIM_ACCOUNT : "inherits"
    COMMON_STOCK_ACCOUNT ||--|| VOTING_STOCK_ACCOUNT : "inherits"
    AGREEMENT ||--|| WEB_AD_PLACEMENT_CONTRACT : "inherits"