erDiagram
    ACCESS_DEVICE {
        Identifier Access_Device_Id "PK"
        Code Access_Device_Subtype_Cd "PK"
        Value Access_Device_Val ""
        Code Access_Medium_Type_Cd ""
    }
    ACCESS_DEVICE_LIMIT {
        Code Limit_Type_Cd "PK"
        Identifier Access_Device_Id "PK"
        Date Access_Device_Limit_Start_Dt "PK"
        Date Access_Device_Limit_End_Dt ""
        Value Access_Device_Limit_Val ""
        string more "3 more"
    }
    ACCESS_DEVICE_METHOD_TYPE {
        Code Access_Device_Method_Type_Cd "PK"
        Description Access_Device_Method_Type_Desc ""
    }
    ACCESS_DEVICE_PIN {
        Identifier Access_Device_Id "PK"
        Datetime Access_Device_PIN_Issue_Dttm "PK"
        Number Access_Device_PIN_Num "PK"
        Datetime Access_Device_PIN_Mailing_Dttm ""
        Code Access_Device_PIN_Reason_Cd ""
        string more "1 more"
    }
    ACCESS_DEVICE_PIN_REASON_TYPE {
        Code Access_Device_PIN_Reason_Cd "PK"
        Description Access_Device_PIN_Reason_Desc ""
    }
    ACCESS_DEVICE_REASON_TYPE {
        Code Access_Device_Reason_Cd "PK"
        Description Access_Device_Reason_Desc ""
    }
    ACCESS_DEVICE_RELATED {
        Identifier Access_Device_Id "PK"
        Identifier Related_Access_Device_Id "PK"
        Code Access_Device_Related_Type_Cd "PK"
        Date Access_Device_Related_Start_Dt "PK"
        Date Access_Device_Related_End_Dt ""
    }
    ACCESS_DEVICE_RELATED_TYPE {
        Code Access_Device_Related_Type_Cd "PK"
        Description Access_Device_Relate_Type_Desc ""
    }
    ACCESS_DEVICE_STATUS {
        Identifier Access_Device_Id "PK"
        Datetime Access_Device_Status_Dttm "PK"
        Code Access_Device_Status_Cd "PK"
        Code Access_Device_Reason_Cd ""
    }
    ACCESS_DEVICE_STATUS_TYPE {
        Code Access_Device_Status_Cd "PK"
        Description Access_Device_Status_Desc ""
    }
    ACCESS_DEVICE_SUBTYPE {
        Code Access_Device_Subtype_Cd "PK"
        Description Access_Device_Subtype_Desc ""
    }
    ACCESS_DEVICE_VERIFICATION_RESPONSE_TYPE {
        Code Access_Device_Verification_Response_Type_Cd "PK"
        Description Access_Device_Verification_Response_Type_Desc ""
    }
    ACCESS_DEVICE_VERIFY_TYPE {
        Code Access_Device_Verify_Type_Cd "PK"
        Description Access_Device_Verify_Type_Desc ""
    }
    ACCESS_MEDIUM_TYPE {
        Code Access_Medium_Type_Cd "PK"
        Description Access_Medium_Type_Desc ""
    }
    ACCIDENT_TYPE {
        Code Accident_Type_Cd "PK"
        Code Parent_Accident_Type_Cd ""
        Description Accident_Type_Desc ""
    }
    ACTIVE_INGREDIENT {
        Identifier Chemical_Id "PK"
        Identifier Pharmaceutical_Drug_Id "PK"
        Value Active_Ingredient_Strength_Val ""
        Code Unit_Of_Measure_Cd ""
    }
    ACTIVITY_ACTIVITY_GROUP {
        Code Event_Activity_Type_Cd "PK"
        Code Activity_Group_Cd "PK"
    }
    ACTIVITY_GROUP {
        Code Activity_Group_Cd "PK"
        Code Parent_Activity_Group_Cd ""
        Description Activity_Group_Desc ""
        Identifier Responsible_Internal_Organization_Party_Id ""
    }
    ACTUAL_IMPACT_AREA {
        Identifier Geographical_Area_Id "PK"
        Identifier Source_Party_Id "PK"
        Datetime Severity_Start_Dttm "PK"
        Identifier Causal_Event_Id "PK"
        Datetime Severity_End_Dttm ""
        string more "2 more"
    }
    ACTUAL_IMPACT_AREA_METRIC {
        Datetime Severity_Start_Dttm "PK"
        Identifier Geographical_Area_Id "PK"
        Identifier Source_Party_Id "PK"
        Code Causal_Event_Metric_Type_Cd "PK"
        Date Actual_Impact_Area_Metric_Start_Dt "PK"
        string more "7 more"
    }
    AD {
        Identifier Ad_Id "PK"
        Description Ad_Desc ""
        Amount Ad_Cost_Amt ""
        Identifier Promotion_Id ""
        Identifier Ad_Agency_Party_Id ""
        string more "4 more"
    }
    ADD_ON_FACTOR_PARAMETER {
        Identifier Add_On_Factor_Id "PK"
        Date Add_On_Factor_Start_Dt "PK"
        Date Add_On_Factor_End_Dt ""
        Code Credit_Derivative_Subtype_Cd ""
        Code Protection_Party_Type_Cd ""
        string more "2 more"
    }
    ADJUSTMENT_REASON_TYPE {
        Code Adjustment_Reason_Type_Cd "PK"
        Description Adjustment_Reason_Type_Desc ""
    }
    ADJUSTMENT_TYPE {
        Code Adjustment_Type_Cd "PK"
        Description Adjustment_Type_Desc ""
    }
    ADMINISTRATION_ROUTE_TYPE {
        Code Administration_Route_Cd "PK"
        Description Administration_Route_Desc ""
    }
    ADMINISTRATIVE_ALERT {
        Datetime Alert_Estimated_Issuance_Dttm ""
    }
    ADMISSION_AUTHORIZATION {
        Code Admission_Source_Cd ""
        Date Authorization_Admission_Dt ""
        Date Authorization_Discharge_Dt ""
        Date Authorization_Surgery_Dt ""
        Code Admission_Type_Cd ""
    }
    ADMISSION_SOURCE_TYPE {
        Code Admission_Source_Cd "PK"
        Description Admission_Source_Desc ""
    }
    ADMISSION_TYPE {
        Code Admission_Type_Cd "PK"
        Description Admission_Type_Desc ""
    }
    AGENT_APPLICATION_DETAIL {
        Code Agent_Commission_Option_Cd ""
        Code Agent_Participation_Type_Cd ""
        Percent Commission_Share_Pct ""
        Indicator Agent_Report_Ind ""
    }
    AGENT_INDEPENDENCE_TYPE {
        Code Agent_Independence_Type_Cd "PK"
        Description Agent_Independence_Type_Desc ""
    }
    AGENT_PARTICIPATION_TYPE {
        Code Agent_Participation_Type_Cd "PK"
        Description Agent_Participation_Type_Desc ""
    }
    AGENT_REPORT {
        Code Regular_Premium_Period_Cd ""
        Code Underwrite_Class_Cd ""
        Code Payment_Mode_Cd ""
        Amount Premium_Amt ""
        Number Regular_Premium_Period_Num ""
        string more "7 more"
    }
    AGE_DETERMINATION_TYPE {
        Code Age_Determination_Type_Cd "PK"
        Description Age_Determination_Type_Desc ""
    }
    ALARM_TYPE {
        Code Alarm_Type_Cd "PK"
        Description Alarm_Type_Desc ""
    }
    ALERT_PRIORITY_TYPE {
        Code Alert_Priority_Cd "PK"
        Description Alert_Priority_Desc ""
    }
    ALERT_RESOLUTION_TEXT {
        Count Alert_Resolution_Text_Sequence_Cnt "PK"
        Identifier Alert_Event_Id "PK"
        Datetime Alert_Text_Dttm ""
        Text Alert_Resolution_Txt ""
        Identifier Alert_Resolution_Text_Source_Party_Id ""
    }
    ALERT_SETUP {
        Identifier Alert_Setup_Id "PK"
        Name Alert_Setup_Name ""
        Quantity Alert_Setup_Time_Delay_Qty ""
        Code Alert_Setup_Time_Delay_Unit_Of_Measure_Cd ""
        Code Alert_Setup_Priority_Cd ""
        string more "1 more"
    }
    ALERT_SETUP_COMMENT {
        Identifier Alert_Setup_Id "PK"
        Identifier Standard_Comment_Id "PK"
    }
    ALERT_SETUP_CONDITION {
        Identifier Alert_Setup_Id "PK"
        Datetime Alert_Setup_Condition_Start_Dttm "PK"
        Datetime Alert_Setup_Condition_End_Dttm ""
        Text Alert_Setup_Condition_Template_SQL_Txt ""
        Description Alert_Setup_Condition_Desc ""
        string more "2 more"
    }
    ALERT_SETUP_NOTIFICATION_LEVEL_TYPE {
        Code Alert_Setup_Notification_Level_Cd "PK"
        Description Alert_Setup_Notification_Level_Desc ""
    }
    ALERT_STANDARD_TRIGGER {
        Identifier Trigger_Alert_Standard_Id ""
    }
    ALERT_TRIGGER_SUBTYPE {
        Code Alert_Trigger_Subtype_Cd "PK"
        Description Alert_Trigger_Subtype_Desc ""
    }
    ALERT_TYPE {
        Code Alert_Type_Cd "PK"
        Description Alert_Type_Desc ""
    }
    ALERT_WEIGHTING_VALUE_TYPE {
        Code Alert_Weighting_Value_Type_Cd "PK"
        Description Alert_Weighting_Value_Type_Desc ""
    }
    AMBULATORY_PATIENT_GROUP_TYPE {
        Code Ambulatory_Patient_Group_Cd "PK"
        Description Ambulatory_Patient_Group_Desc ""
    }
    AMORTIZATION_METHOD_TYPE {
        Code Amortization_Method_Cd "PK"
        Description Amortization_Method_Desc "PK"
    }
    ANALYTICAL_MODEL {
        Identifier Model_Id "PK"
        Name Model_Name ""
        Description Model_Desc ""
        Number Model_Version_Num ""
        Code Model_Type_Cd ""
        string more "11 more"
    }
    ANALYTICAL_MODEL_DOCUMENT {
        Identifier Model_Id "PK"
        Identifier Document_Id "PK"
        Date Analytical_Model_Document_Start_Dt "PK"
        Date Analytical_Model_Document_End_Dt ""
    }
    ANALYTICAL_MODEL_GROUP {
        Identifier Analytical_Model_Group_Id "PK"
        Description Analytical_Model_Group_Desc ""
    }
    ANALYTICAL_MODEL_RUN_REVIEW {
        Identifier Analytical_Model_Id "PK"
        Identifier Model_Run_Id "PK"
        Date Analytical_Model_Review_Dt "PK"
        Code Model_Review_Finding_Cd ""
        Identifier Reviewer_Party_Id ""
    }
    ANALYTICAL_MODEL_STATUS {
        Identifier Model_Id "PK"
        Date Model_Status_Dt "PK"
        Code Model_Status_Cd "PK"
    }
    ANALYTICAL_MODEL_TO_GROUP {
        Identifier Analytical_Model_Group_Id "PK"
        Identifier Model_Id "PK"
        Datetime Model_To_Group_Start_Dttm "PK"
        Datetime Model_To_Group_End_Dttm ""
    }
    ANALYTICAL_MODEL_VALUE {
        Identifier Model_Id "PK"
        Identifier Analytical_Model_Value_Id "PK"
        Datetime Analytical_Model_Start_Dttm "PK"
        Datetime Analytical_Model_End_Dttm ""
        Description Analytical_Model_Value_Desc ""
        string more "6 more"
    }
    ANIMAL {
        Code Animal_Breed_Type_Cd ""
        Code Animal_Type_Cd ""
        Date Animal_Birth_Dt ""
        Date Animal_Death_Dt ""
        Code Gender_Type_Cd "PK"
    }
    ANIMAL_BREED_TYPE {
        Code Animal_Breed_Type_Cd "PK"
        Description Animal_Breed_Desc ""
    }
    ANIMAL_TYPE {
        Code Animal_Type_Cd "PK"
        Description Animal_Type_Desc ""
    }
    ACCESS_DEVICE ||--o{ ACCESS_DEVICE_PIN : ""
    ACCESS_DEVICE ||--o{ ACCESS_DEVICE_LIMIT : ""
    ACCESS_DEVICE ||--o{ ACCESS_DEVICE_STATUS : ""
    ACCESS_DEVICE ||--o{ CELL_TARGET_ACCESS_DEVICE : ""
    ACCESS_DEVICE ||--o{ INTERACTIVE_DEVICE : ""
    ACCESS_DEVICE_PIN_REASON_TYPE ||--o{ ACCESS_DEVICE_PIN : ""
    ACCESS_DEVICE_REASON_TYPE ||--o{ ACCESS_DEVICE_STATUS : ""
    ACCESS_DEVICE_RELATED_TYPE ||--o{ ACCESS_DEVICE_RELATED : ""
    ACCESS_DEVICE_STATUS_TYPE ||--o{ ACCESS_DEVICE_STATUS : ""
    ACCESS_DEVICE_SUBTYPE ||--o{ ACCESS_DEVICE : ""
    ACCESS_MEDIUM_TYPE ||--o{ ACCESS_DEVICE : ""
    ACCIDENT_TYPE ||--o{ ACCIDENT_TYPE : ""
    ACTIVITY_GROUP ||--o{ ACTIVITY_GROUP : ""
    ACTIVITY_GROUP ||--o{ ACTIVITY_ACTIVITY_GROUP : ""
    ACTUAL_IMPACT_AREA ||--o{ ACTUAL_IMPACT_AREA_METRIC : ""
    AD ||--o{ CONTENT_DELIVERY_XREF : ""
    AD ||--o{ APPLICATION_SECOND_SOURCE_XREF : ""
    AD ||--o{ DIGITAL_PLACEMENT_XREF : ""
    ADMINISTRATION_ROUTE_TYPE ||--o{ DRUG_NDC__GEO : ""
    ADMISSION_SOURCE_TYPE ||--o{ ADMISSION_AUTHORIZATION : ""
    ADMISSION_TYPE ||--o{ ADMISSION_AUTHORIZATION : ""
    AGENT_INDEPENDENCE_TYPE ||--o{ INSURANCE_AGENT : ""
    AGENT_PARTICIPATION_TYPE ||--o{ AGENT_APPLICATION_DETAIL : ""
    ALERT_PRIORITY_TYPE ||--o{ ALERT_SETUP : ""
    ALERT_SETUP ||--o{ ALERT_SETUP_CONDITION : ""
    ALERT_SETUP ||--o{ ALERT_SETUP_COMMENT : ""
    ALERT_SETUP ||--o{ ALERT_STANDARD_TRIGGER : ""
    ALERT_SETUP_CONDITION ||--o{ ALERT_SETUP_CONDITION : ""
    ALERT_TYPE ||--o{ ALERT_SETUP : ""
    AMBULATORY_PATIENT_GROUP_TYPE ||--o{ PROCEDURE_CODE : ""
    ANALYTICAL_MODEL ||--o{ ANALYTICAL_MODEL_STATUS : ""
    ANALYTICAL_MODEL ||--o{ POLICY_METRIC : ""
    ANALYTICAL_MODEL ||--o{ ASSUMPTION_SET : ""
    ANALYTICAL_MODEL ||--o{ DERIVED_WEATHER : ""
    ANALYTICAL_MODEL ||--o{ MODEL_RUN : ""
    ANALYTICAL_MODEL ||--o{ ANALYTICAL_MODEL_TO_GROUP : ""
    ANALYTICAL_MODEL ||--o{ ANALYTICAL_MODEL_DOCUMENT : ""
    ANALYTICAL_MODEL ||--o{ ANALYTICAL_MODEL_VALUE : ""
    ANALYTICAL_MODEL ||--o{ MODEL_CALCULATION_CRITERIA : ""
    ANALYTICAL_MODEL_GROUP ||--o{ ANALYTICAL_MODEL_TO_GROUP : ""
    ANIMAL_BREED_TYPE ||--o{ ANIMAL : ""
    ANIMAL_TYPE ||--o{ ANIMAL : ""
    APPLICATION ||--o{ APPLICATION_CHECKLIST : ""
    APPLICATION ||--o{ APPLICATION_DOCUMENT : ""
    APPLICATION ||--o{ APPLICATION_QUESTION_RESPONSE : ""
    APPLICATION ||--o{ APPLICATION_METRIC : ""
    APPLICATION ||--o{ APPLICATION_TEXT : ""
    APPLICATION ||--o{ APPLICATION_FRAUD_CASE : ""
    APPLICATION ||--o{ APPLICATION_SCORE : ""
    APPLICATION ||--o{ APPLICATION_STATUS : ""
    APPLICATION ||--o{ APPLICATION_ACTIVITY : ""
    APPLICATION ||--o{ APPLICATION_UNDERWRITE_REQUIREMENT : ""
    APPLICATION ||--o{ APPLICATION_UNDERWRITE_EXCEPTION : ""
    APPLICATION_ACTIVITY_TYPE ||--o{ APPLICATION_ACTIVITY : ""
    APPLICATION_CHECKLIST_ITEM_TYPE ||--o{ APPLICATION_CHECKLIST : ""
    APPLICATION_CHECKLIST_STATUS_TYPE ||--o{ APPLICATION_CHECKLIST : ""
    APPLICATION_FORM ||--o{ APPLICATION_FORM_QUESTION : ""
    APPLICATION_FORM ||--o{ APPLICATION_FORM_QUESTION_TYPE : ""
    APPLICATION_FORM ||--o{ APPLICATION : ""
    APPLICATION_FORM_QUESTION ||--o{ APPLICATION_QUESTION_RESPONSE : ""
    APPLICATION_FRAUD_TYPE ||--o{ APPLICATION_FRAUD_CASE : ""
    APPLICATION_METRIC_TYPE ||--o{ APPLICATION_METRIC : ""
    APPLICATION_QUESTION_TYPE ||--o{ APPLICATION_FORM_QUESTION_TYPE : ""
    APPLICATION_RELATIONSHIP_TYPE ||--o{ APPLICATION_RELATED : ""
    APPLICATION_REVIEW_METHOD_TYPE ||--o{ APPLICATION : ""
    APPLICATION_STATUS_REASON_TYPE ||--o{ APPLICATION_STATUS : ""
    APPLICATION_STATUS_TYPE ||--o{ APPLICATION_STATUS : ""
    APPLICATION_TYPE ||--o{ APPLICATION : ""
    APPLICATION_UNDERWRITE_REQUIREMENT ||--o{ APPLICATION_UNDERWRITE_REQUIREMENT_STATUS : ""
    APPLICATION_UNDERWRITE_REQUIREMENT ||--o{ APPLICATION_UNDERWRITE_REQUIREMENT_TEXT : ""
    AR_COLLECTION_ACTIVITY_TYPE ||--o{ AR_COLLECTION_ACTIVITY : ""
    AREA_JAPAN ||--o{ PREFECTURE_JAPAN : ""
    ASSOCIATION_TYPE ||--o{ ASSOCIATION : ""
    AUDIO_PLAY ||--o{ AUDIO_PLAY_TRACK : ""
    AUDIO_PLAY ||--o{ AUDIO_PLAY_RADIO_STATION_XREF : ""
    BALANCE_CATEGORY_USE_TYPE ||--o{ BALANCE_CATEGORY_TYPE : ""
    BREAK_TYPE ||--o{ TRADITIONAL_PLACEMENT : ""
    CARD ||--o{ TRAVEL_PLAN_CARD : ""
    CARD_ASSOCIATION_TYPE ||--o{ CARD : ""
    CARD_SUBTYPE ||--o{ CARD : ""
    CART_ACTION_TYPE ||--o{ SHOPPING_CART : ""
    CASE_AMOUNT_TYPE ||--o{ CASE_AMOUNT : ""
    CASE_CATEGORY_TYPE ||--o{ CASE_DETAIL : ""
    CASE_DETAIL ||--o{ CASE_DOCUMENT : ""
    CASE_DETAIL ||--o{ CASE_AMOUNT : ""
    CASE_DETAIL ||--o{ CASE_STATUS : ""
    CASE_DETAIL ||--o{ CASE_TEXT : ""
    CASE_DETAIL ||--o{ CASE_SCORE : ""
    CASE_RESOLUTION_TYPE ||--o{ CASE_DETAIL : ""
    CASE_STATUS_TYPE ||--o{ CASE_STATUS : ""
    CASE_TYPE ||--o{ CASE_DETAIL : ""
    CASH_FLOW_AMOUNT_TYPE ||--o{ PROJECTED_CASH_FLOW : ""
    CASH_MANAGEMENT_SUBTYPE ||--o{ CASH_MANAGEMENT : ""
    CCF_BAND_PARAMETER ||--o{ CCF_BAND_PARAMETER : ""
    CENSUS_BLOCK_GROUP__GEO ||--o{ CENSUS_BLOCK__GEO : ""
    CENSUS_TRACT__GEO ||--o{ CENSUS_BLOCK_GROUP__GEO : ""
    CERTIFICATION ||--o{ CERTIFICATION_GEOGRAPHICAL_AREA : ""
    CERTIFICATION ||--o{ COURSE_COMPLETED_CERTIFICATION : ""
    CERTIFICATION_OF_MEDICAL_NECESSITY_TYPE ||--o{ CERTIFICATION_OF_MEDICAL_NECESSITY : ""
    CERTIFICATION_TYPE ||--o{ CERTIFICATION : ""
    CHARGE_GROUP_TYPE ||--o{ CHARGE_TYPE : ""
    CHECK_BOOK ||--o{ CHECK_BOOK_METRIC : ""
    CHECK_BOOK_METRIC_TYPE ||--o{ CHECK_BOOK_METRIC : ""
    CHECK_IMAGE_TYPE ||--o{ CHECK_IMAGE : ""
    CHEMICAL ||--o{ INACTIVE_INGREDIENT : ""
    CHEMICAL ||--o{ ACTIVE_INGREDIENT : ""
    CITY ||--o{ CITY_TO_COUNTY : ""
    CITY_JAPAN ||--o{ DISTRICT_JAPAN : ""
    CITY_TYPE ||--o{ CITY : ""
    CLIMATE_ZONE ||--o{ WEATHER_STATION : ""
    COA_CODE_BALANCE_REASON ||--o{ COA_CODE_BALANCE : ""
    COA_CODE_BALANCE_SUBTYPE ||--o{ COA_CODE_BALANCE : ""
    COA_CODE_BALANCE_TYPE ||--o{ COA_CODE_BALANCE : ""
    COA_CODE_SEGMENT_SUBTYPE ||--o{ COA_CODE_SEGMENT : ""
    COLLECTION_STATUS_TYPE ||--o{ AR_COLLECTION_ACTIVITY : ""
    COMMERCIAL_PAPER_TYPE ||--o{ COMMERCIAL_PAPER : ""
    COMMODITY ||--o{ COMMODITY_TIME_BAND_SCHEME : ""
    COMMODITY_TYPE ||--o{ COMMODITY : ""
    CONDITION_TYPE_VALUE ||--o{ WEATHER_CONDITION_OBSERVED : ""
    CONSTITUTION ||--o{ LEGAL_SYSTEM : ""
    CONSTITUTION_TYPE ||--o{ CONSTITUTION : ""
    CONSTRUCTION_TYPE ||--o{ REAL_ESTATE : ""
    CONTENT_REVIEW_TYPE ||--o{ READER : ""
    CONTENT_SCORE_TYPE ||--o{ READER : ""
    CONTENT_SOURCE_TYPE ||--o{ SOCIAL_MEDIA_CONTENT_SOURCE : ""
    CONVERSION ||--o{ CONVERSION_STEP : ""
    CONVERSION_CATEGORY ||--o{ CONVERSION : ""
    COST_TYPE ||--o{ COLLECTION_COST : ""
    COST_TYPE ||--o{ SITE_COST : ""
    COST_TYPE ||--o{ COST_TYPE : ""
    COUNTY ||--o{ CITY_TO_COUNTY : ""
    COUNTY ||--o{ CENSUS_TRACT__GEO : ""
    COURSE ||--o{ COURSE_FEEDBACK_QUESTION : ""
    COURSE ||--o{ COURSE_COMPLETED : ""
    COURSE ||--o{ COURSE_SCHEDULED : ""
    COURSE ||--o{ COURSE : ""
    COURSE_COMPLETED ||--o{ COURSE_COMPLETED_CERTIFICATION : ""
    COURSE_FEEDBACK_QUESTION ||--o{ COURSE_FEEDBACK_RESPONSE : ""
    COURSE_SCHEDULED ||--o{ SCHEDULED_INSTRUCTOR : ""
    COURSE_SCHEDULED ||--o{ STUDENT_ENROLLMENT : ""
    CRITICALITY_TYPE ||--o{ ANALYTICAL_MODEL : ""
    CUSTOM_AREA_REASON_TYPE ||--o{ CUSTOM_AREA : ""
    CUSTOM_PROGRAM_TYPE ||--o{ CUSTOM_PROGRAM : ""
    DATA_SOURCE_TYPE ||--o{ APPLICATION_METRIC : ""
    DATA_SOURCE_TYPE ||--o{ WATCH_LIST_SOURCE : ""
    DATA_SOURCE_TYPE ||--o{ ANALYTICAL_MODEL : ""
    DATA_SOURCE_TYPE ||--o{ DOCUMENT : ""
    DAY_OF_WEEK ||--o{ DIGITAL_PLACEMENT_XREF : ""
    DAY_OF_WEEK ||--o{ CONTENT_DELIVERY_XREF : ""
    DAY_OF_WEEK ||--o{ ORDER_PLACEMENT_DAYPART : ""
    DAY_OF_WEEK ||--o{ SITE_DAY_OF_WEEK_HOURS : ""
    DAY_OF_WEEK ||--o{ DAYPART_HOURS : ""
    DAY_OF_WEEK ||--o{ ORDER_PLACEMENT_DISPLAY_TIME : ""
    DAY_OF_WEEK ||--o{ GREGORIAN_DATE : ""
    DAYPART ||--o{ CONTENT_DELIVERY_XREF : ""
    DAYPART ||--o{ DAYPART_HOURS : ""
    DAYPART ||--o{ DIGITAL_PLACEMENT_XREF : ""
    DAYPART ||--o{ ORDER_PLACEMENT_DAYPART : ""
    DAYPART ||--o{ ORDER_PLACEMENT_DISPLAY_TIME : ""
    DEGREE_DAYS_DAILY ||--o{ DEGREE_DAYS_INTRADAY : ""
    DEPRECIATION_METHOD_TYPE ||--o{ DEPRECIATION_AMOUNT : ""
    DERIVED_WEATHER ||--o{ WEATHER_NORMALS_PERIODIC : ""
    DIAGNOSIS_CODE ||--o{ DIAGNOSIS_CODE_SERVICE_XREF : ""
    DIAGNOSIS_CODE ||--o{ DIAGNOSIS_CODE_XREF : ""
    DIGITAL_PLACEMENT ||--o{ DIGITAL_PLACEMENT_XREF : ""
    DIGITAL_PLACEMENT ||--o{ DIGITAL_PLACEMENT_SUMMARY : ""
    DIGITAL_PLACEMENT_SUBTYPE ||--o{ DIGITAL_PLACEMENT : ""
    DIGITAL_PLACEMENT_SUBTYPE ||--o{ DIGITAL_REQUEST_PLACEMENT : ""
    DIRECT_PAY_ELEMENT_FIXED_TYPE ||--o{ DIRECT_PAY_ELEMENT_FIXED : ""
    DIRECT_PAY_ELEMENT_TYPE ||--o{ DIRECT_PAY_ELEMENT : ""
    DIRECTION_TYPE ||--o{ ROADWAY : ""
    DISTRICT_JAPAN ||--o{ BLOCK_JAPAN : ""
    DOCUMENT ||--o{ LABOR_GRIEVANCE_DOCUMENT : ""
    DOCUMENT ||--o{ DOCUMENT_STATUS : ""
    DOCUMENT ||--o{ ANALYTICAL_MODEL_DOCUMENT : ""
    DOCUMENT ||--o{ DOCUMENT_GROUP_XREF : ""
    DOCUMENT ||--o{ STEP_SPECIFICATION_STANDARD : ""
    DOCUMENT ||--o{ DOCUMENT_TEXT_SECTION : ""
    DOCUMENT ||--o{ GRIEVANCE_PROCEDURE : ""
    DOCUMENT ||--o{ MICROSITE_DOCUMENT_XREF : ""
    DOCUMENT ||--o{ DOCUMENT_SITE : ""
    DOCUMENT ||--o{ CASE_DOCUMENT : ""
    DOCUMENT ||--o{ APPLICATION_DOCUMENT : ""
    DOCUMENT ||--o{ LEGAL_ACTION_DOCUMENT : ""
    DOCUMENT_FORMAT_TYPE ||--o{ DOCUMENT : ""
    DOCUMENT_GROUP ||--o{ DOCUMENT_GROUP_XREF : ""
    DOCUMENT_GROUP_TYPE ||--o{ DOCUMENT_GROUP : ""
    DOCUMENT_IMAGE_SOURCE_TYPE ||--o{ CHECK_IMAGE : ""
    DOCUMENT_IMAGE_TYPE ||--o{ CHECK_IMAGE : ""
    DOCUMENT_RELATED_TYPE ||--o{ DOCUMENT_RELATED : ""
    DOCUMENT_STATUS_TYPE ||--o{ DOCUMENT_STATUS : ""
    DOCUMENT_SUBTYPE ||--o{ DOCUMENT : ""
    DOCUMENT_TYPE ||--o{ DOCUMENT_TYPE : ""
    DOCUMENT_TYPE ||--o{ NEXT_ACTIVITY : ""
    DOCUMENT_TYPE ||--o{ DOCUMENT : ""
    DOSAGE_FORM_TYPE ||--o{ DRUG_NDC__GEO : ""
    DRAFT_TYPE ||--o{ BANK_DRAFT : ""
    DRUG_NDC__GEO ||--o{ DRUG_PUBLISHED_PRICE : ""
    DRUG_NDC__GEO ||--o{ FORMULARY_DRUG_NDC__GEO : ""
    DRUG_PUBLISHED_PRICE ||--o{ DRUG_MAXIMUM_ALLOWABLE_COST : ""
    DRUG_STANDARD_PRICE_TYPE ||--o{ DRUG_PUBLISHED_PRICE : ""
    DUNNING_LEVEL_TYPE ||--o{ DUNNING_LETTER : ""
    EARLY_AMORTIZATION_TYPE ||--o{ CCF_EARLY_AMORTIZATION_PARAMETER : ""
    ECONOMIC_MEASURE_TYPE ||--o{ GEOGRAPHIC_ECONOMIC_MEASURE : ""
    EDUCATION_LEVEL_TYPE ||--o{ INSURANCE_AGENT : ""
    EDUCATION_SUPPORT_TYPE ||--o{ INSURANCE_AGENT : ""
    EXCHANGE_CODE ||--o{ EXCHANGE : ""
    EXCHANGE_DELISTING_REASON_TYPE ||--o{ EXCHANGE_DELISTING : ""
    EXTERNAL_LIST ||--o{ EXTERNAL_WATCH_LIST_SOURCE : ""
    EXTERNAL_LIST_TYPE ||--o{ EXTERNAL_LIST : ""
    EXTERNAL_TRIGGER_TYPE ||--o{ EXTERNAL_TRIGGER : ""
    FACILITY_QUALIFIER_TYPE ||--o{ FACILITY_TYPE : ""
    FACILITY_TYPE ||--o{ HOME_HEALTH_CERTIFICATION : ""
    FILE_FORMAT ||--o{ DIGITAL_ITEM : ""
    FINANCIAL_INSTITUTION_TYPE ||--o{ FINANCIAL_INSTITUTION : ""
    FINANCIAL_INSTRUMENT_GLOBAL_IDENTIFIER ||--o{ FINANCIAL_INSTRUMENT_GLOBAL_IDENTIFIER : ""
    FINANCIAL_INSTRUMENT_GLOBAL_IDENTIFIER_TYPE ||--o{ FINANCIAL_INSTRUMENT_GLOBAL_IDENTIFIER : ""
    FINANCIAL_PLAN ||--o{ FINANCIAL_PLAN_PROJECT_TASK_RESOURCE : ""
    FINANCIAL_PLAN ||--o{ PROJECT_FINANCIAL_PLAN : ""
    FINANCIAL_PLAN ||--o{ PROJECT_TASK_FINANCIAL_PLAN : ""
    FINANCIAL_PLAN ||--o{ LABOR_FINANCIAL_PLAN : ""
    FINANCIAL_PLAN ||--o{ FINANCIAL_PLAN_BALANCE : ""
    FINANCIAL_PLAN_STATUS_TYPE ||--o{ FINANCIAL_PLAN : ""
    FINANCIAL_RULE ||--o{ FINANCIAL_RULE_STRATEGY : ""
    FINANCIAL_RULE_METRIC_TYPE ||--o{ FINANCIAL_RULE : ""
    FINANCIAL_RULE_RELATED_TYPE ||--o{ FINANCIAL_RULE_RELATED : ""
    FOREIGN_EXCHANGE_POINT_TENOR_TYPE ||--o{ FOREIGN_EXCHANGE_POINT : ""
    FORM_STATUS_TYPE ||--o{ FORM_STATUS : ""
    FORMULARY ||--o{ FORMULARY_TIER : ""
    FORMULARY_CATEGORY ||--o{ FORMULARY : ""
    FORMULARY_TIER ||--o{ FORMULARY_DRUG_NDC__GEO : ""
    FORMULARY_TIER_TYPE ||--o{ FORMULARY_TIER : ""
    FREIGHT_TERM_TYPE ||--o{ RETURN_LINE : ""
    FREIGHT_TERM_TYPE ||--o{ VENDOR : ""
    GENDER_TYPE ||--o{ MORTALITY_TABLE : ""
    GENDER_TYPE ||--o{ ANIMAL : ""
    GEOGRAPHICAL_AREA ||--o{ JURISDICTION : ""
    GEOGRAPHICAL_AREA ||--o{ SOCIAL_MEDIA_INTERACTION : ""
    GEOGRAPHICAL_AREA ||--o{ ACTUAL_IMPACT_AREA : ""
    GEOGRAPHICAL_AREA ||--o{ COVERED_AREA : ""
    GEOGRAPHICAL_AREA ||--o{ CERTIFICATION_GEOGRAPHICAL_AREA : ""
    GEOGRAPHICAL_AREA ||--o{ GEOGRAPHIC_ECONOMIC_MEASURE : ""
    GEOGRAPHICAL_AREA ||--o{ PROGRAMMING_PACKAGE : ""
    GEOGRAPHICAL_AREA ||--o{ TRAVEL_PLAN_DESTINATION : ""
    GEOGRAPHICAL_AREA ||--o{ GEOGRAPHICAL_AREA_SCORE : ""
    GEOGRAPHICAL_AREA ||--o{ GEOGRAPHIC_LIMIT : ""
    GEOGRAPHICAL_AREA ||--o{ SIC_ECONOMIC_MEASURE : ""
    GEOGRAPHICAL_AREA ||--o{ GEOGRAPHIC_AREA_TIME_ZONE : ""
    GEOGRAPHICAL_AREA ||--o{ GEOGRAPHICAL_AREA_SEASON : ""
    GEOGRAPHICAL_AREA ||--o{ GEOGRAPHICAL_AREA_HOLIDAY : ""
    GEOGRAPHICAL_AREA ||--o{ MORTALITY_TABLE : ""
    GEOGRAPHICAL_AREA ||--o{ GEOGRAPHIC_AREA_SUBJECT : ""
    GEOGRAPHICAL_AREA ||--o{ WEATHER_FORECAST : ""
    GEOGRAPHICAL_AREA ||--o{ FORECASTED_IMPACT_AREA : ""
    GEOGRAPHICAL_AREA_HOLIDAY ||--o{ RECOGNIZED_HOLIDAY : ""
    GEOGRAPHICAL_AREA_SEASON ||--o{ GEOGRAPHICAL_AREA_SEASON_DAY : ""
    GEOGRAPHICAL_AREA_SUBTYPE ||--o{ GEOGRAPHICAL_AREA : ""
    GEOSEQUENCE ||--o{ GEOSEQUENCE_POINT : ""
    GEOSEQUENCE_POINT ||--o{ GEOSEQUENCE_POINT_TRAIT_XREF : ""
    GEOSEQUENCE_POINT_TRAIT ||--o{ GEOSEQUENCE_POINT_TRAIT_VALUE : ""
    GEOSEQUENCE_POINT_TRAIT_VALUE ||--o{ GEOSEQUENCE_POINT_TRAIT_XREF : ""
    GEOSPATIAL ||--o{ GEOSPATIAL_SET_MEMBER : ""
    GEOSPATIAL_AREA ||--o{ GEOSPATIAL_AREA_POINT : ""
    GEOSPATIAL_LINE_CURVE ||--o{ GEOSPATIAL_LINE_CURVE_POINT : ""
    GEOSPATIAL_POINT ||--o{ GEOSPATIAL_LINE_CURVE_POINT : ""
    GEOSPATIAL_POINT ||--o{ REQUEST_PLACEMENT_OUTDOOR : ""
    GEOSPATIAL_POINT ||--o{ GEOSPATIAL_AREA_POINT : ""
    GEOSPATIAL_POINT ||--o{ GEOSEQUENCE_POINT : ""
    GEOSPATIAL_ROADWAY_SUBTYPE ||--o{ GEOSPATIAL : ""
    GEOSPATIAL_SET ||--o{ GEOSPATIAL_SET_MEMBER : ""
    GEOSPATIAL_SUBTYPE ||--o{ GEOSPATIAL : ""
    GICS_INDUSTRY_GROUP_TYPE ||--o{ GICS_INDUSTRY_TYPE : ""
    GICS_INDUSTRY_TYPE ||--o{ GICS_SUBINDUSTRY_TYPE : ""
    GICS_SECTOR_TYPE ||--o{ GICS_INDUSTRY_GROUP_TYPE : ""
    GOAL ||--o{ GOAL_OBJECTIVE : ""
    GOVERNMENT ||--o{ GOVERNMENT_SPONSORED_ENTITY : ""
    GOVERNMENT_TYPE ||--o{ GOVERNMENT : ""
    GREGORIAN_DATE ||--o{ SITE_DAILY_HOURS : ""
    GREGORIAN_DATE ||--o{ RECOGNIZED_HOLIDAY : ""
    GREGORIAN_DATE ||--o{ GEOGRAPHICAL_AREA_SEASON_DAY : ""
    GREGORIAN_MONTH ||--o{ GREGORIAN_MONTH_WEEK : ""
    GREGORIAN_MONTH_WEEK ||--o{ GREGORIAN_DATE : ""
    GREGORIAN_QUARTER ||--o{ GREGORIAN_MONTH : ""
    GREGORIAN_WEEK ||--o{ GREGORIAN_MONTH_WEEK : ""
    GREGORIAN_YEAR ||--o{ GREGORIAN_QUARTER : ""
    GRIEVANCE_PROCEDURE ||--o{ LABOR_GRIEVANCE_PROCESS : ""
    GRIEVANCE_PROCEDURE_SCOPE_TYPE ||--o{ GRIEVANCE_PROCEDURE : ""
    GRIEVANCE_PROCEDURE_TYPE ||--o{ GRIEVANCE_PROCEDURE : ""
    GRIEVANCE_PROCESS_STATUS_REASON ||--o{ GRIEVANCE_PROCESS_STATUS : ""
    GRIEVANCE_PROCESS_STATUS_TYPE ||--o{ GRIEVANCE_PROCESS_STATUS : ""
    HEALTH_CONDITION_TYPE ||--o{ FAMILY_HEALTH_CONDITION : ""
    HEALTH_PROCEDURE ||--o{ HEALTH_PROCEDURE_TO_PROCEDURE_CODE : ""
    HEALTH_PROCEDURE_CATEGORY ||--o{ HEALTH_PROCEDURE : ""
    HEALTH_PROCEDURE_TO_PROCEDURE_CODE ||--o{ PROCEDURE_CODE_XREF : ""
    HEDGING_SET_TYPE ||--o{ HEDGING_SET : ""
    HOLIDAY ||--o{ GEOGRAPHICAL_AREA_HOLIDAY : ""
    HOLIDAY_TYPE ||--o{ GEOGRAPHICAL_AREA_HOLIDAY : ""
    IMPRESSION_DELIVERY_STATUS_TYPE ||--o{ IMPRESSION_DELIVERY_STATUS : ""
    IMPRESSION_SELECTED ||--o{ CONVERSION : ""
    INCENTIVE_TYPE ||--o{ INCENTIVE : ""
    INDIRECT_PAY_ELEMENT_TYPE ||--o{ INDIRECT_PAY_ELEMENT : ""
    INFORMATION_CATEGORY ||--o{ INFORMATION_TYPE : ""
    INFORMATION_TYPE ||--o{ SELECTION_CRITERION_TYPE : ""
    INFORMATION_TYPE ||--o{ PRIVACY_PRESET : ""
    INFORMATION_TYPE ||--o{ MEMBER_PRIVACY_PREFERENCE : ""
    INFRASTRUCTURE_SUPPORT_TYPE ||--o{ INSURANCE_AGENCY : ""
    INSURANCE_AGENT_TYPE ||--o{ INSURANCE_AGENCY : ""
    INSURANCE_AGENT_TYPE ||--o{ INSURANCE_AGENT : ""
    INSURANCE_COVERAGE_TYPE ||--o{ INSURANCE_COVERAGE_TYPE : ""
    INSURANCE_METRIC_TYPE ||--o{ POLICY_COVERAGE_METRIC : ""
    INSURANCE_METRIC_TYPE ||--o{ POLICY_METRIC : ""
    INSURANCE_TYPE ||--o{ INSURANCE_VERIFICATION_STATUS : ""
    INSURANCE_VERIFY_STATUS_TYPE ||--o{ INSURANCE_VERIFICATION_STATUS : ""
    INTERACTION_STATUS_TYPE ||--o{ INTERACTION_STATUS : ""
    INTERACTIVE_DEVICE_TYPE ||--o{ OPERATING_SYSTEM : ""
    INTERACTIVE_DEVICE_TYPE ||--o{ INTERACTIVE_DEVICE : ""
    INTEREST_RATE_INDEX ||--o{ INTEREST_INDEX_RATE : ""
    INTEREST_RATE_INDEX ||--o{ FLOATING_RATE_NOTE : ""
    INTEREST_RATE_INDEX_TYPE ||--o{ INTEREST_RATE_INDEX : ""
    ITEM ||--o{ READER : ""
    ITEM ||--o{ AUDIO_PLAY : ""
    ITEM ||--o{ MEDIA_PLAYER : ""
    ITEM ||--o{ GAME_PLAY : ""
    ITEM_CLASS ||--o{ ITEM_SUBCLASS : ""
    ITEM_SUBCLASS ||--o{ ITEM : ""
    JURISDICTION ||--o{ STATUTORY_RESPONSIBILITY : ""
    KEYWORD_CATEGORY ||--o{ KEYWORD_PHRASE : ""
    KEYWORD_PHRASE ||--o{ SOCIAL_MEDIA_KEYWORD_SUMMARY : ""
    KEYWORD_PHRASE ||--o{ KEYWORD_PLACEMENT : ""
    KEYWORD_PHRASE ||--o{ REFERRAL_SEARCH : ""
    KEYWORD_PHRASE ||--o{ INTERACTION_SUMMARY : ""
    KEYWORD_PHRASE ||--o{ REFERRAL : ""
    KEYWORD_PLACEMENT ||--o{ PAID_SEARCH : ""
    LABOR_GRIEVANCE ||--o{ LABOR_GRIEVANCE_PROCESS : ""
    LABOR_GRIEVANCE ||--o{ LABOR_GRIEVANCE_DOCUMENT : ""
    LABOR_GRIEVANCE ||--o{ LABOR_GRIEVANCE_STATUS : ""
    LABOR_GRIEVANCE ||--o{ GRIEVANCE_PROJECT : ""
    LABOR_GRIEVANCE_PROCESS ||--o{ GRIEVANCE_PROCESS_STATUS : ""
    LABOR_GRIEVANCE_STATUS_REASON ||--o{ LABOR_GRIEVANCE_STATUS : ""
    LABOR_GRIEVANCE_STATUS_TYPE ||--o{ LABOR_GRIEVANCE_STATUS : ""
    LABOR_GRIEVANCE_TYPE ||--o{ LABOR_GRIEVANCE : ""
    LABOR_TASK_GROUP ||--o{ LABOR_TASK_TYPE : ""
    LAW_ENFORCEABILITY_TYPE ||--o{ LEGAL_SYSTEM : ""
    LEDGER_BATCH_TYPE ||--o{ LEDGER_BATCH : ""
    LEGAL_ACTION ||--o{ LEGAL_ACTION_DOCUMENT : ""
    LEGAL_ACTION ||--o{ LEGAL_ACTION_OUTCOME : ""
    LEGAL_ACTION ||--o{ LEGAL_ACTION_STATUS : ""
    LEGAL_ACTION ||--o{ LEGAL_ACTION_FINANCIAL : ""
    LEGAL_ACTION_FINANCIAL ||--o{ LEGAL_ACTION_RECOVERY : ""
    LEGAL_ACTION_METRIC_TYPE ||--o{ LEGAL_ACTION_FINANCIAL : ""
    LEGAL_ACTION_OUTCOME_TYPE ||--o{ LEGAL_ACTION_OUTCOME : ""
    LEGAL_ACTION_RELATED_TYPE ||--o{ LEGAL_ACTION_RELATED : ""
    LEGAL_ACTION_STATUS_TYPE ||--o{ LEGAL_ACTION_STATUS : ""
    LEGAL_ACTION_TYPE ||--o{ LEGAL_ACTION : ""
    LEGAL_SYSTEM ||--o{ JURISDICTION : ""
    LEGAL_SYSTEM_TYPE ||--o{ LEGAL_SYSTEM : ""
    LIABILITY ||--o{ LIABILITY_BALANCE : ""
    LIABILITY_TYPE ||--o{ LIABILITY : ""
    LIMIT_TYPE ||--o{ GEOGRAPHIC_LIMIT : ""
    LIMIT_TYPE ||--o{ ACCESS_DEVICE_LIMIT : ""
    MAJOR_DIAGNOSTIC_CATEGORY ||--o{ DIAGNOSIS_CODE : ""
    MAJOR_DIAGNOSTIC_CATEGORY ||--o{ DIAGNOSIS_RELATED_GROUP : ""
    MANUFACTURER_MODEL ||--o{ MONITORING_DEVICE : ""
    MAXIMUM_ALLOWABLE_COST ||--o{ DRUG_MAXIMUM_ALLOWABLE_COST : ""
    MEASUREMENT ||--o{ MEASUREMENT_STANDARD_RESULT : ""
    MEASUREMENT_CONDITION_TYPE ||--o{ MEASUREMENT : ""
    MEASUREMENT_DIAGNOSTIC_TYPE ||--o{ MEASUREMENT_READING : ""
    MEASUREMENT_RELATED_ROLE ||--o{ MEASUREMENT_RELATED : ""
    MEASUREMENT_STANDARD_RESULT_TYPE ||--o{ MEASUREMENT_STANDARD_RESULT : ""
    MEASUREMENT_SUBTYPE ||--o{ MEASUREMENT : ""
    METROPOLITAN_STATISTICAL_AREA__GEO ||--o{ COUNTY : ""
    MICROSITE ||--o{ MICROSITE_METRIC_XREF : ""
    MICROSITE ||--o{ MICROSITE_STATUS : ""
    MICROSITE ||--o{ MICROSITE_RATING_XREF : ""
    MICROSITE ||--o{ MICROSITE_DOCUMENT_XREF : ""
    MICROSITE ||--o{ MICROSITE_TARGET_GROUP : ""
    MICROSITE ||--o{ MICROSITE_CATEGORY_XREF : ""
    MICROSITE ||--o{ MICROSITE_MEMBER : ""
    MICROSITE_ACTIVITY_TYPE ||--o{ MICROSITE : ""
    MICROSITE_CATEGORY_STATUS_TYPE ||--o{ MICROSITE_CATEGORY_STATUS : ""
    MICROSITE_CATEGORY_XREF ||--o{ MICROSITE_CATEGORY_STATUS : ""
    MICROSITE_CONTENT_CATEGORY ||--o{ MICROSITE_CATEGORY_XREF : ""
    MICROSITE_CONTENT_GROUP ||--o{ MICROSITE_CONTENT_CATEGORY : ""
    MICROSITE_CONTENT_RATING ||--o{ MICROSITE_RATING_XREF : ""
    MICROSITE_CONTENT_RATING_REASON ||--o{ MICROSITE_RATING_REASON_XREF : ""
    MICROSITE_CONTENT_RATING_SYSTEM ||--o{ MICROSITE_CONTENT_RATING : ""
    MICROSITE_DOCUMENT_ROLE ||--o{ MICROSITE_DOCUMENT_XREF : ""
    MICROSITE_METRIC_TYPE ||--o{ MICROSITE_METRIC_XREF : ""
    MICROSITE_RATING_XREF ||--o{ MICROSITE_RATING_REASON_XREF : ""
    MICROSITE_STATUS_TYPE ||--o{ MICROSITE_STATUS : ""
    MODEL_ALGORITHM_TYPE ||--o{ ANALYTICAL_MODEL : ""
    MODEL_RELATIONSHIP_ROLE_TYPE ||--o{ MODEL_RELATIONSHIP : ""
    MODEL_REVIEW_FINDING_TYPE ||--o{ ANALYTICAL_MODEL_RUN_REVIEW : ""
    MODEL_RUN ||--o{ CASE_SCORE : ""
    MODEL_RUN ||--o{ GEOGRAPHICAL_AREA_SCORE : ""
    MODEL_RUN ||--o{ WEATHER_FORECAST : ""
    MODEL_RUN ||--o{ NEXT_ACTIVITY : ""
    MODEL_RUN ||--o{ APPLICATION_SCORE : ""
    MODEL_RUN ||--o{ ANALYTICAL_MODEL_RUN_REVIEW : ""
    MODEL_STATUS_TYPE ||--o{ ANALYTICAL_MODEL_STATUS : ""
    MODEL_TYPE ||--o{ ANALYTICAL_MODEL : ""
    MULTIMEDIA_GROUP ||--o{ MULTIMEDIA_GROUP_OBJECT_XREF : ""
    MULTIMEDIA_OBJECT ||--o{ MULTIMEDIA_GROUP_OBJECT_XREF : ""
    MULTIMEDIA_OBJECT ||--o{ SCRIPTED_MESSAGE : ""
    MULTIMEDIA_OBJECT ||--o{ DOCUMENT : ""
    MULTIMEDIA_SOURCE ||--o{ MULTIMEDIA_OBJECT : ""
    MULTIMEDIA_SUBTYPE ||--o{ MULTIMEDIA_OBJECT : ""
    MULTIMEDIA_SUBTYPE ||--o{ MULTIMEDIA_SOURCE : ""
    MULTIMEDIA_TEXT_OBJECT ||--o{ MM_OBJECT_TEXT_SECTION : ""
    NACE_DIVISION ||--o{ NACE_GROUP : ""
    NACE_GROUP ||--o{ NACE_CLASS : ""
    NACE_SECTION ||--o{ NACE_DIVISION : ""
    NAICS_INDUSTRY__GEO ||--o{ NAICS_NATIONAL_INDUSTRY__GEO : ""
    NAICS_INDUSTRY_GROUP__GEO ||--o{ NAICS_INDUSTRY__GEO : ""
    NAICS_SECTOR__GEO ||--o{ NAICS_SUBSECTOR__GEO : ""
    NAICS_SUBSECTOR__GEO ||--o{ NAICS_INDUSTRY_GROUP__GEO : ""
    NAVIGATION_LEVEL ||--o{ NAVIGATION_LEVEL : ""
    NETWORK_GROUPING_TYPE ||--o{ NETWORK_TYPE : ""
    NEXT_ACTIVITY ||--o{ NEXT_ACTIVITY : ""
    NUMBER_CHANGE_REASON_TYPE ||--o{ STOCK_ISSUANCE : ""
    OBJECTIVE ||--o{ STRATEGY_OBJECTIVE : ""
    OBJECTIVE ||--o{ GOAL_OBJECTIVE : ""
    OBJECTIVE ||--o{ PROJECT_OBJECTIVE : ""
    OBJECTIVE_TYPE ||--o{ OBJECTIVE : ""
    OBSERVATION_CLASS ||--o{ OBSERVATION_TYPE : ""
    OBSERVATION_CLASS_SUBTYPE ||--o{ OBSERVATION_TYPE : ""
    OBSERVATION_SET ||--o{ OBSERVATION_TYPE : ""
    OBSERVATION_SUBTYPE ||--o{ WEATHER_FORECAST : ""
    OBSERVATION_SUBTYPE ||--o{ OBSERVATION_TYPE : ""
    OBSERVATION_TYPE ||--o{ WEATHER_FORECAST : ""
    OBSERVATION_TYPE ||--o{ STATION_OBSERVATION_XREF : ""
    OFFSET_VALUE_TYPE ||--o{ INTERNAL_SEARCH_RESULT_CONTENT : ""
    OPERATING_SYSTEM ||--o{ OPERATING_SYSTEM_VERSION : ""
    OPERATING_SYSTEM_FAMILY ||--o{ OPERATING_SYSTEM : ""
    OPERATIONAL_AUTHORITY_TYPE ||--o{ INSURANCE_AGENT : ""
    ORAL_CAVITY_TYPE ||--o{ DENTAL_SERVICE_ORAL_CAVITY : ""
    ORANGE_BOOK_THERAPEUTIC_EQUIVALENCE_TYPE__GEO ||--o{ DRUG_NDC__GEO : ""
    OTHER_FINANCIAL_SERVICES_SUBTYPE ||--o{ OTHER_FINANCIAL_SERVICE : ""
    OUTBOUND_CALL_REASON_TYPE ||--o{ OUTBOUND_CALL : ""
    PAGE_TYPE ||--o{ REQUEST_PLACEMENT_PRINT : ""
    PAGE_TYPE ||--o{ DIGITAL_REQUEST_PLACEMENT : ""
    PASSBOOK ||--o{ PASSBOOK_STATUS : ""
    PASSBOOK_RELATED_ROLE_TYPE ||--o{ PASSBOOK_RELATED : ""
    PASSBOOK_STATUS_TYPE ||--o{ PASSBOOK_STATUS : ""
    PASSBOOK_TYPE ||--o{ PASSBOOK : ""
    PAY_ELEMENT_TYPE ||--o{ PAY_ELEMENT : ""
    PAY_ELEMENT_VARIABLE_BASIS_TYPE ||--o{ DIRECT_PAY_ELEMENT_VARIABLE : ""
    PAY_ELEMENT_VARIABLE_TYPE ||--o{ DIRECT_PAY_ELEMENT_VARIABLE : ""
    PAY_STUB ||--o{ PAY_STUB_BALANCE : ""
    PHARMACEUTICAL_DRUG ||--o{ ACTIVE_INGREDIENT : ""
    PHARMACEUTICAL_DRUG ||--o{ COMPOUND_DRUG : ""
    PHARMACEUTICAL_DRUG ||--o{ INACTIVE_INGREDIENT : ""
    PHARMACEUTICAL_DRUG ||--o{ DRUG_NDC__GEO : ""
    PLACEMENT_CATEGORY ||--o{ TRADITIONAL_PLACEMENT : ""
    PLACEMENT_CATEGORY ||--o{ POD_PLACEMENT : ""
    PO_ACCRUE_TYPE ||--o{ VENDOR_PO : ""
    PO_TERM ||--o{ VENDOR_PO_LINE_TERM : ""
    PO_TERM ||--o{ VENDOR_PO_TERM : ""
    PO_TERM ||--o{ RECEIPT_TERM : ""
    PO_TERM_TYPE ||--o{ PO_TERM : ""
    POOL_CONTENT_TYPE ||--o{ PURCHASED_RECEIVABLE_POOL_CONTENT : ""
    PREFECTURE_JAPAN ||--o{ CITY_JAPAN : ""
    PREFECTURE_JAPAN ||--o{ ISO_3166_JAPAN_PREFECTURE : ""
    PRIVACY_DATA_USAGE ||--o{ PRIVACY_PRESET : ""
    PRIVACY_DATA_USAGE ||--o{ MEMBER_PRIVACY_PREFERENCE : ""
    PRIVACY_POLICY_SCOPE ||--o{ PRIVACY_PRESET : ""
    PROCEDURE_CODE ||--o{ PROCEDURE_CODE_XREF : ""
    PROCEDURE_CODE ||--o{ HEALTH_PROCEDURE_TO_PROCEDURE_CODE : ""
    PROCEDURE_CODE ||--o{ HOME_HEALTH_CERTIFICATION : ""
    PROFIT_COMPONENT_TYPE ||--o{ PROFITABILITY_COMPONENT : ""
    PROFIT_TYPE ||--o{ PROFITABILITY_COMPONENT : ""
    PROJECT ||--o{ REPORTING_PROJECT : ""
    PROJECT ||--o{ WORK_PROCESS_STEP_PROJECT : ""
    PROJECT ||--o{ PROJECT_FINANCIAL_PLAN : ""
    PROJECT ||--o{ PROJECT_TASK : ""
    PROJECT ||--o{ PROJECT_OBJECTIVE : ""
    PROJECT ||--o{ GRIEVANCE_PROJECT : ""
    PROJECT ||--o{ PROJECT_METRIC : ""
    PROJECT ||--o{ PROJECT_STATUS : ""
    PROJECT ||--o{ PROJECT : ""
    PROJECT_BILLABLE_TYPE ||--o{ PROJECT_TASK : ""
    PROJECT_BILLABLE_TYPE ||--o{ PROJECT : ""
    PROJECT_METRIC_TYPE ||--o{ PROJECT_METRIC : ""
    PROJECT_RELATED_ROLE ||--o{ PROJECT_RELATED : ""
    PROJECT_STATUS_TYPE ||--o{ PROJECT_TASK_STATUS : ""
    PROJECT_STATUS_TYPE ||--o{ PROJECT_STATUS : ""
    PROJECT_TASK ||--o{ PROJECT_TASK_STATUS : ""
    PROJECT_TASK ||--o{ TASK_ADJUSTMENT : ""
    PROJECT_TASK ||--o{ PROJECT_TASK_RESOURCE_ASSIGNMENT : ""
    PROJECT_TASK ||--o{ PROJECT_TASK_FINANCIAL_PLAN : ""
    PROJECT_TASK_RELATED_TYPE ||--o{ PROJECT_TASK_RELATED : ""
    PROJECT_TASK_RESOURCE_ASSIGNMENT ||--o{ FINANCIAL_PLAN_PROJECT_TASK_RESOURCE : ""
    PROJECT_TASK_RESOURCE_ITEM_TYPE ||--o{ PROJECT_TASK_RESOURCE_ITEM : ""
    PROJECT_TASK_RESOURCE_TYPE ||--o{ PROJECT_TASK_RESOURCE_ASSIGNMENT : ""
    PROJECT_TYPE ||--o{ PROJECT : ""
    PROVIDER_DESELECT_REASON ||--o{ INSURED_PROVIDER_SELECTION : ""
    PROVIDER_SELECT_REASON ||--o{ INSURED_PROVIDER_SELECTION : ""
    PROVIDER_SELECT_ROLE_TYPE ||--o{ INSURED_PROVIDER_SELECTION : ""
    PURCHASE_REQUISITION ||--o{ PO_REQUISITION : ""
    PURCHASE_REQUISITION ||--o{ PURCHASE_REQUISITION_LINE : ""
    PURCHASE_REQUISITION ||--o{ PURCHASE_REQUISITION_STATUS : ""
    PURCHASE_REQUISITION_LINE ||--o{ PURCHASE_REQUISITION_LINE_ASSIGNMENT : ""
    PURCHASE_REQUISITION_LINE ||--o{ PURCHASE_REQUISITION_LINE_STATUS : ""
    PURCHASE_TYPE ||--o{ PURCHASE_CARD : ""
    PURCHASED_RECEIVABLE_POOL ||--o{ PURCHASED_RECEIVABLE_POOL_CONTENT : ""
    PURCHASED_RECEIVABLE_POOL_TYPE ||--o{ PURCHASED_RECEIVABLE_POOL : ""
    QUERY_STRING_FIELD_TYPE ||--o{ QUERY_STRING_FIELD_VALUE : ""
    QUESTION ||--o{ QUESTIONNAIRE_QUESTION : ""
    QUESTION_CATEGORY ||--o{ QUESTION : ""
    QUESTION_FORMAT_TYPE ||--o{ QUESTION : ""
    QUESTIONNAIRE ||--o{ QUESTIONNAIRE_QUESTION : ""
    QUESTIONNAIRE_CATEGORY ||--o{ QUESTIONNAIRE : ""
    RANK_TYPE ||--o{ SOCIAL_MEDIA_AUTHOR_RANK : ""
    RANK_TYPE ||--o{ BOOKMARK : ""
    RANK_TYPE ||--o{ PUBLISHED_CONTENT_REVIEW : ""
    REAL_ESTATE ||--o{ REAL_ESTATE_DETAIL : ""
    REAL_ESTATE ||--o{ REAL_ESTATE_REBUILD_AMOUNT : ""
    REAL_ESTATE_RIGHTS_TYPE ||--o{ REAL_ESTATE : ""
    REAL_ESTATE_TYPE ||--o{ REAL_ESTATE : ""
    REAL_ESTATE_ZONE_TYPE ||--o{ REAL_ESTATE : ""
    RECEIPT ||--o{ RECEIPT_TERM : ""
    RECEIPT ||--o{ RECEIPT_LINE : ""
    RECEIPT ||--o{ RECEIPT_STATUS : ""
    RECEIPT_LINE ||--o{ RECEIVED_QUANTITY : ""
    RECEIPT_LINE ||--o{ RECEIPT_LINE_UNIQUE_ITEM_INSTANCE : ""
    RECEIPT_LINE ||--o{ RECEIPT_LINE_INSPECTION : ""
    RECEIPT_LINE ||--o{ RECEIPT_LINE_DOCUMENT : ""
    RECEIPT_LINE ||--o{ RECEIPT_LINE_STATUS : ""
    RECEIPT_LINE_DOCUMENT_TYPE ||--o{ RECEIPT_LINE_DOCUMENT : ""
    RECEIPT_LINE_QUALITY_TYPE ||--o{ RECEIPT_LINE_INSPECTION : ""
    RECEIPT_LINE_STATUS_TYPE ||--o{ RECEIPT_LINE_STATUS : ""
    RECEIPT_LINE_STATUS_TYPE ||--o{ RECEIPT_LINE_INSPECTION : ""
    RECEIPT_LINE_TYPE ||--o{ RECEIPT_LINE : ""
    RECEIPT_STATUS_TYPE ||--o{ RECEIPT_STATUS : ""
    RECEIVABLE_TYPE ||--o{ RECEIVABLE : ""
    RECEIVED_QUANTITY_TYPE ||--o{ RECEIVED_QUANTITY : ""
    REFERRAL ||--o{ REFERRAL_SEARCH : ""
    REFERRAL_SUBTYPE ||--o{ REFERRAL : ""
    REFERRING_SITE ||--o{ REFERRAL : ""
    REFERRING_SITE_TYPE ||--o{ REFERRING_SITE : ""
    RESPONSE_TYPE ||--o{ NEXT_ACTIVITY : ""
    RETURN_DETAIL ||--o{ RETURN_LINE : ""
    RETURN_LINE ||--o{ RETURN_LINE_STATUS : ""
    RETURN_LINE ||--o{ RETURN_LINE_UNIQUE_ITEM_INSTANCE : ""
    RETURN_LINE ||--o{ VENDOR_RETURN_PO_LINE : ""
    RETURN_LINE_TYPE ||--o{ RETURN_LINE : ""
    RETURN_REASON_TYPE ||--o{ RETURN_LINE : ""
    RETURN_STATUS_TYPE ||--o{ RETURN_LINE_STATUS : ""
    REVENUE_TYPE ||--o{ REVENUE_TYPE : ""
    ROOF_CONSTRUCTION_TYPE ||--o{ REAL_ESTATE_DETAIL : ""
    SALES_METHOD_TYPE ||--o{ LEAD : ""
    SALES_PROGRAM_TYPE ||--o{ SALES_PROGRAM : ""
    SALES_STAGE_PHASE_TYPE ||--o{ SALES_STAGE : ""
    SCHEDULE_GROUP_TYPE ||--o{ SITE_SCHEDULE_GROUP : ""
    SCRIPTED_MESSAGE ||--o{ SCRIPTED_MESSAGE_STATUS : ""
    SCRIPTED_MESSAGE_STATUS_TYPE ||--o{ SCRIPTED_MESSAGE_STATUS : ""
    SCRIPTED_MESSAGE_TYPE ||--o{ SCRIPTED_MESSAGE : ""
    SEARCH_ENGINE_SYSTEM ||--o{ REFERRAL_SEARCH : ""
    SEARCH_ENGINE_SYSTEM ||--o{ REFERRAL : ""
    SEARCH_ENGINE_SYSTEM ||--o{ KEYWORD_PLACEMENT : ""
    SEARCH_ENGINE_SYSTEM_TYPE ||--o{ SEARCH_ENGINE_SYSTEM : ""
    SEARCH_MATCH_TYPE ||--o{ KEYWORD_PLACEMENT : ""
    SEARCH_TYPE ||--o{ REFERRAL : ""
    SEASON ||--o{ GEOGRAPHICAL_AREA_SEASON : ""
    SECTION_CONTAINS_SECTION_TYPE ||--o{ SECTION_CONTAINS_SECTION : ""
    SEGMENT_RELATIONSHIP_REASON ||--o{ COA_SEGMENT_RELATED : ""
    SELECTION_CRITERION_TYPE ||--o{ SELECTION_SET_CRITERION : ""
    SELECTION_CRITERION_TYPE ||--o{ MODEL_CALCULATION_CRITERIA : ""
    SELECTION_CRITERION_TYPE ||--o{ SEGMENT_CRITERION : ""
    SELECTION_SET_FORMULA_TYPE ||--o{ SELECTION_SET_CRITERION : ""
    SERVICE_QUOTE_REQUEST_TYPE ||--o{ SERVICE_REQUEST : ""
    SERVICE_REQUEST ||--o{ SERVICE_REQUEST_STATUS : ""
    SERVICE_REQUEST ||--o{ SERVICE_REQUEST_ACTIVITY : ""
    SERVICE_REQUEST_ACTIVITY ||--o{ SERVICE_REQUEST_ACTIVITY_STATUS : ""
    SERVICE_REQUEST_RELATED_ROLE ||--o{ SERVICE_REQUEST_RELATED : ""
    SERVICE_REQUEST_STATUS_REASON ||--o{ SERVICE_REQUEST_STATUS : ""
    SERVICE_REQUEST_STATUS_SCHEME_TYPE ||--o{ SERVICE_REQUEST_STATUS : ""
    SERVICE_REQUEST_STATUS_TYPE ||--o{ SERVICE_REQUEST_STATUS : ""
    SERVICE_REQUEST_STATUS_TYPE ||--o{ SERVICE_REQUEST_ACTIVITY_STATUS : ""
    SERVICE_REQUEST_SUBTYPE ||--o{ SERVICE_REQUEST : ""
    SERVICE_REQUEST_TYPE ||--o{ SERVICE_REQUEST : ""
    SET_OF_BOOKS ||--o{ SET_OF_BOOKS : ""
    SET_OF_BOOKS_RELATED_REASON ||--o{ SET_OF_BOOKS_RELATED : ""
    SET_OF_BOOKS_TYPE ||--o{ SET_OF_BOOKS : ""
    SHOPPING_TOOL_TYPE ||--o{ SHOPPING_TOOL : ""
    SIC ||--o{ SIC_ECONOMIC_MEASURE : ""
    SIC_GROUP ||--o{ SIC : ""
    SITE ||--o{ SITE_STATUS : ""
    SITE ||--o{ COVERED_SITE : ""
    SITE ||--o{ SITE_SITE_CLASS_XREF : ""
    SITE ||--o{ LABOR_POOL : ""
    SITE ||--o{ SITE_COST : ""
    SITE ||--o{ SITE_METRIC : ""
    SITE ||--o{ DOCUMENT_SITE : ""
    SITE ||--o{ LABOR_FINANCIAL_PLAN : ""
    SITE ||--o{ SITE : ""
    SITE ||--o{ SITE_SCHEDULE_XREF : ""
    SITE ||--o{ PROJECT_TASK : ""
    SITE ||--o{ RECEIPT_LINE : ""
    SITE ||--o{ RETURN_LINE : ""
    SITE ||--o{ COURSE_SCHEDULED : ""
    SITE ||--o{ SITE_TRAIT_XREF : ""
    SITE ||--o{ SITE_TYPE_XREF : ""
    SITE ||--o{ VENDOR_PO : ""
    SITE ||--o{ VISIT : ""
    SITE_CLASS_SCHEME_TYPE ||--o{ SITE_CLASS_SCHEME_TYPE : ""
    SITE_CLASS_SCHEME_TYPE ||--o{ SITE_CLASS_VALUE : ""
    SITE_CLASS_SCHEME_TYPE ||--o{ SITE_SITE_CLASS_XREF : ""
    SITE_CLASS_VALUE ||--o{ SITE_SITE_CLASS_XREF : ""
    SITE_CLASS_VALUE ||--o{ SITE_CLASS_VALUE : ""
    SITE_MAJOR_TYPE ||--o{ SITE : ""
    SITE_METRIC_TYPE ||--o{ SITE_METRIC : ""
    SITE_RELATIONSHIP_TYPE ||--o{ SITE_RELATED : ""
    SITE_SCHEDULE_GROUP ||--o{ SITE_DAILY_HOURS : ""
    SITE_SCHEDULE_GROUP ||--o{ SITE_SCHEDULE_XREF : ""
    SITE_SCHEDULE_GROUP ||--o{ SITE_DAY_OF_WEEK_HOURS : ""
    SITE_SCHEDULE_GROUP ||--o{ DAYPART_HOURS : ""
    SITE_STATUS_TYPE ||--o{ SITE_STATUS : ""
    SITE_TRAIT ||--o{ SITE_TRAIT_VALUE : ""
    SITE_TRAIT_TYPE ||--o{ SITE_TRAIT : ""
    SITE_TRAIT_VALUE ||--o{ SITE_TRAIT_XREF : ""
    SITE_TYPE ||--o{ SITE_TYPE_XREF : ""
    SKILL_TYPE ||--o{ STEP_SKILL_SET : ""
    SOCIAL_CONSTRUCT_TYPE ||--o{ LEGAL_SYSTEM : ""
    SOCIAL_MEDIA_AUTHOR ||--o{ SOCIAL_MEDIA_AUTHOR_RANK : ""
    SOCIAL_MEDIA_CATEGORY ||--o{ SOCIAL_MEDIA_CATEGORY_SCORE : ""
    SOCIAL_MEDIA_CATEGORY ||--o{ SOCIAL_MEDIA_CATEGORY_XREF : ""
    SOCIAL_MEDIA_CATEGORY ||--o{ SOCIAL_MEDIA_CONTENT_REVIEW : ""
    SOCIAL_MEDIA_CATEGORY ||--o{ SOCIAL_MEDIA_RESULT_CATEGORY : ""
    SOCIAL_MEDIA_GROUP ||--o{ SOCIAL_MEDIA_CATEGORY : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_ACTIVITY_IMPRESSION_XREF : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_STATUS : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_NETWORK_SUMMARY_ACTIVITY : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_KEYWORD_SUMMARY : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_CATEGORY_XREF : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_NETWORK_PROFILE : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_AUTHOR : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_CONTENT_SOURCE : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_RESULT : ""
    SOCIAL_MEDIA_INTERACTION ||--o{ SOCIAL_MEDIA_CONTENT_REVIEW : ""
    SOCIAL_MEDIA_INTERACTION_TYPE ||--o{ SOCIAL_MEDIA_INTERACTION : ""
    SOCIAL_MEDIA_LOGON ||--o{ SOCIAL_NETWORK_MEMBER : ""
    SOCIAL_MEDIA_RESULT_CATEGORY ||--o{ SOCIAL_MEDIA_RESULT_TOPIC : ""
    SOCIAL_MEDIA_RESULT_TOPIC ||--o{ SOCIAL_MEDIA_RESULT : ""
    SOCIAL_MEDIA_SITE ||--o{ SOCIAL_MEDIA_INTERACTION : ""
    SOCIAL_MEDIA_STATUS_TYPE ||--o{ SOCIAL_MEDIA_STATUS : ""
    SOCIAL_NETWORK_AFFILIATION_TYPE ||--o{ SOCIAL_NETWORK_AFFILIATION : ""
    SOCIAL_NETWORK_MEMBER ||--o{ SOCIAL_NETWORK_AFFILIATION : ""
    SOCIAL_NETWORK_MEMBER ||--o{ MEMBER_PRIVACY_PREFERENCE : ""
    SOFTWARE ||--o{ CSR_APPLICATION_JUMP : ""
    SOURCE_SYSTEM_PROCESSING ||--o{ HIT_PAGE : ""
    STANDARD_COMMENT ||--o{ ALERT_SETUP_COMMENT : ""
    STANDARD_COMMENT_TYPE ||--o{ STANDARD_COMMENT : ""
    STANDARD_RESULT_SET ||--o{ STANDARD_RESULT_VALID_VALUE : ""
    STANDARD_RESULT_SET ||--o{ MEASUREMENT_STANDARD_RESULT : ""
    STANDARD_RESULT_SET_TYPE ||--o{ STANDARD_RESULT_SET : ""
    STANDARD_TEXT_PATTERN ||--o{ TEXT_PATTERN_RESPONSE : ""
    STATION_OBSERVATION_XREF ||--o{ DERIVED_WEATHER : ""
    STATION_OBSERVATION_XREF ||--o{ WEATHER_OBSERVATION : ""
    STATION_OBSERVATION_XREF ||--o{ TMY_DAY : ""
    STEP ||--o{ STEP_SKILL_SET : ""
    STEP ||--o{ STEP_SPECIFICATION_STANDARD : ""
    STEP ||--o{ STEP_STANDARD_INPUT_OUTPUT : ""
    STEP ||--o{ STEP_ACTUAL_INPUT_OUTPUT : ""
    STEP ||--o{ WORK_PROCESS_STEP_ACTUAL : ""
    STEP ||--o{ WORK_PROCESS_STEP_STANDARD : ""
    STEP ||--o{ STEP_GROUP_TO_STEP : ""
    STEP_GROUP ||--o{ STEP_GROUP_TO_STEP : ""
    STEP_GROUP ||--o{ STEP_GROUP : ""
    STEP_PRIORITY_TYPE ||--o{ WORK_PROCESS_STEP_ACTUAL : ""
    STEP_RELATED_ROLE ||--o{ STEP_RELATED_STANDARD : ""
    STEP_RELATED_ROLE ||--o{ STEP_RELATED_ACTUAL : ""
    STEP_STATUS_TYPE ||--o{ STEP_STATUS : ""
    STOCK ||--o{ STOCK_ISSUANCE : ""
    STOCK_SHARE_CLASS_TYPE ||--o{ STOCK : ""
    STOCK_TYPE ||--o{ STOCK : ""
    STRATEGY ||--o{ STRATEGY_OBJECTIVE : ""
    STRATEGY ||--o{ TACTIC : ""
    STRATEGY ||--o{ FINANCIAL_RULE_STRATEGY : ""
    STRATEGY_TYPE ||--o{ STRATEGY : ""
    SUBJECT ||--o{ WATCH_LIST_MEMBER : ""
    SUBJECT_TYPE ||--o{ SUBJECT : ""
    SUPPLEMENTAL_FORM ||--o{ SUPPLEMENTAL_FORM_RESPONSE : ""
    TASK ||--o{ PROJECT_TASK : ""
    TASK ||--o{ TASK : ""
    TASK_ADJUSTMENT_REASON_TYPE ||--o{ TASK_ADJUSTMENT : ""
    TASK_ADJUSTMENT_TYPE ||--o{ TASK_ADJUSTMENT : ""
    TAX_LOT ||--o{ TAX_LOT_METRIC : ""
    TAX_LOT_METRIC_TYPE ||--o{ TAX_LOT_METRIC : ""
    TECHNOLOGY_TYPE ||--o{ CARD : ""
    TEXT_PATTERN_METHOD_TYPE ||--o{ TEXT_PATTERN_RESPONSE : ""
    TEXT_SECTION ||--o{ MM_OBJECT_TEXT_SECTION : ""
    TEXT_SECTION ||--o{ DOCUMENT_TEXT_SECTION : ""
    TEXT_SECTION_RELATED_REASON_SUBTYPE ||--o{ TEXT_SECTION_RELATED : ""
    TEXT_SUBTYPE ||--o{ TEXT_SECTION : ""
    THERAPEUTIC_CLASS ||--o{ THERAPEUTIC_SUBCLASS : ""
    THERAPEUTIC_CLASS_TYPE ||--o{ THERAPEUTIC_CLASS : ""
    THERAPEUTIC_SUBCLASS ||--o{ PHARMACEUTICAL_DRUG : ""
    TIME_BAND ||--o{ TIME_BAND_PARAMETER : ""
    TIME_BAND ||--o{ TIME_BAND_CALCULATION : ""
    TIME_BAND ||--o{ SPECIAL_LENDING_SLOTTING_PARAMETER : ""
    TIME_BAND_METRIC_TYPE ||--o{ TIME_BAND_CALCULATION : ""
    TIME_BAND_PARAMETER_TYPE ||--o{ TIME_BAND_PARAMETER : ""
    TIME_BAND_ROLE_TYPE ||--o{ TIME_BAND_RELATED : ""
    TIME_BAND_SCHEME ||--o{ TIME_BAND : ""
    TIME_BAND_TYPE ||--o{ TIME_BAND : ""
    TIME_ZONE ||--o{ TIME_ZONE_AREA : ""
    TIME_ZONE ||--o{ GEOGRAPHIC_AREA_TIME_ZONE : ""
    TIME_ZONE ||--o{ SITE : ""
    TMY_DAY ||--o{ TMY_INTRADAY : ""
    TOOTH_SURFACE_TYPE ||--o{ DENTAL_SERVICE_TOOTH : ""
    TRADITIONAL_PLACEMENT ||--o{ POD_PLACEMENT : ""
    TRADITIONAL_PLACEMENT ||--o{ CONTENT_DELIVERY_XREF : ""
    TRADITIONAL_PLACEMENT_SUBTYPE ||--o{ TRADITIONAL_PLACEMENT : ""
    TRADITIONAL_PLACEMENT_SUBTYPE ||--o{ TRADITIONAL_REQUEST_PLACEMENT : ""
    TRAIT ||--o{ SITE_TRAIT_XREF : ""
    TRAIT ||--o{ GEOSEQUENCE_POINT_TRAIT_XREF : ""
    TRAIT ||--o{ ASSUMPTION_SET : ""
    TRAIT_SUBTYPE ||--o{ TRAIT : ""
    TRAIT_TYPE ||--o{ TRAIT : ""
    TRANCHE ||--o{ TRANCHE : ""
    TRANCHE_TYPE ||--o{ TRANCHE : ""
    TRANSMITTAL_MODE_TYPE ||--o{ VENDOR_PO : ""
    TRAVEL_PLAN ||--o{ TRAVEL_PLAN_CARD : ""
    TRAVEL_PLAN ||--o{ TRAVEL_PLAN_DESTINATION : ""
    TV_RECEIVER_SETTING_TYPE ||--o{ TV_RECEIVER_SETTING : ""
    TV_SIGNAL_RECEIVER ||--o{ PROGRAMMING_PACKAGE : ""
    TV_SIGNAL_RECEIVER ||--o{ TV_RECEIVER_SETTING : ""
    TV_SIGNAL_RECEIVER ||--o{ RECEIVER_USER_SETTING : ""
    TV_SYSTEM_TYPE ||--o{ PROGRAMMING_PACKAGE : ""
    UNDERWRITE_CLASS ||--o{ AGENT_REPORT : ""
    UNDERWRITING_AUTHORITY_TYPE ||--o{ INSURANCE_AGENT : ""
    UNDERWRITING_REQUIREMENT_TYPE ||--o{ APPLICATION_UNDERWRITE_EXCEPTION : ""
    UNDERWRITING_REQUIREMENT_TYPE ||--o{ APPLICATION_UNDERWRITE_REQUIREMENT : ""
    UNDERWRITING_STATUS_TYPE ||--o{ APPLICATION_UNDERWRITE_REQUIREMENT_STATUS : ""
    UNIFIED_COVERAGE_CATEGORY ||--o{ UNIFIED_COVERAGE : ""
    URL_CATEGORY ||--o{ URL_INFORMATION : ""
    USER_SETTING_TYPE ||--o{ RECEIVER_USER_SETTING : ""
    VACCINE_ADMINISTERED_STATUS ||--o{ VACCINE_ADMINISTERED : ""
    VENDOR_PO ||--o{ VENDOR_PO_LINE : ""
    VENDOR_PO ||--o{ VENDOR_PO_STATUS_ASSIGN : ""
    VENDOR_PO ||--o{ VENDOR_PO_TERM : ""
    VENDOR_PO ||--o{ VENDOR_PO_COMMENT : ""
    VENDOR_PO ||--o{ PO_REQUISITION : ""
    VENDOR_PO_LINE ||--o{ VENDOR_PO_LINE_TERM : ""
    VENDOR_PO_LINE ||--o{ VENDOR_PO_LINE_STATUS_ASSIGNMENT : ""
    VENDOR_PO_LINE ||--o{ VENDOR_RECEIPT_LINE_VENDOR_PO_LINE : ""
    VENDOR_PO_LINE ||--o{ PURCHASE_REQUISITION_LINE_ASSIGNMENT : ""
    VENDOR_PO_LINE ||--o{ VENDOR_PO_LINE_BACK_ORDER : ""
    VENDOR_PO_LINE ||--o{ VENDOR_RETURN_PO_LINE : ""
    VENDOR_PO_LINE ||--o{ VENDOR_PO_LINE_COMMENT : ""
    VENDOR_PO_LINE_RELATED_TYPE ||--o{ VENDOR_PO_LINE_RELATED : ""
    VENDOR_PO_REASON ||--o{ VENDOR_PO_STATUS_ASSIGN : ""
    VENDOR_PO_REASON ||--o{ PURCHASE_REQUISITION_LINE_STATUS : ""
    VENDOR_PO_REASON ||--o{ VENDOR_PO_LINE_STATUS_ASSIGNMENT : ""
    VENDOR_PO_REASON ||--o{ PURCHASE_REQUISITION_STATUS : ""
    VENDOR_PO_RELATED_TYPE ||--o{ VENDOR_PO_RELATED : ""
    VENDOR_PO_STATUS ||--o{ VENDOR_PO_STATUS_ASSIGN : ""
    VENDOR_PO_STATUS ||--o{ PURCHASE_REQUISITION_LINE_STATUS : ""
    VENDOR_PO_STATUS ||--o{ PURCHASE_REQUISITION_STATUS : ""
    VENDOR_PO_STATUS ||--o{ VENDOR_PO_LINE_STATUS_ASSIGNMENT : ""
    VENDOR_PO_TYPE ||--o{ VENDOR_PO : ""
    VENDOR_RECEIPT_LINE ||--o{ VENDOR_RECEIPT_LINE_VENDOR_PO_LINE : ""
    VENDOR_TYPE ||--o{ VENDOR : ""
    VISIT_ACTION_TYPE ||--o{ VISIT : ""
    VISIT_SUBTYPE ||--o{ VISIT : ""
    WATCH_LIST ||--o{ WATCH_LIST_SOURCE : ""
    WATCH_LIST ||--o{ WATCH_LIST_MEMBER : ""
    WEATHER_CONDITION_TYPE ||--o{ CONDITION_TYPE_VALUE : ""
    WEATHER_NORMALS_DAILY ||--o{ WEATHER_NORMALS_INTRADAY : ""
    WEATHER_STATION ||--o{ COVERED_AREA : ""
    WEATHER_STATION ||--o{ STATION_OBSERVATION_XREF : ""
    WEATHER_STATION ||--o{ COVERED_SITE : ""
    WORK_PROCESS ||--o{ WORK_PROCESS_STATUS : ""
    WORK_PROCESS ||--o{ WORK_PROCESS_STEP_STANDARD : ""
    WORK_PROCESS ||--o{ WORK_PROCESS_STEP_ACTUAL : ""
    WORK_PROCESS_RELATED_ROLE ||--o{ WORK_PROCESS_RELATED : ""
    WORK_PROCESS_STATUS_TYPE ||--o{ WORK_PROCESS_STATUS : ""
    WORK_PROCESS_STEP_ACTUAL ||--o{ STEP_STATUS : ""
    WORK_PROCESS_STEP_ACTUAL ||--o{ WORK_PROCESS_STEP_PROJECT : ""
    WORK_PROCESS_STEP_ACTUAL_SUBTYPE ||--o{ WORK_PROCESS_STEP_ACTUAL : ""
    WORK_PROCESS_SUBTYPE ||--o{ WORK_PROCESS : ""
    WORK_PROCESS_TYPE ||--o{ WORK_PROCESS : ""
    WORKSTATION_TYPE ||--o{ WORKSTATION_TERMINAL : ""
    AGENT_APPLICATION_DETAIL ||--|| AGENT_REPORT : "inherits"
    APPLICATION_FRAUD_CASE ||--|| APPLICANT_FRAUD : "inherits"
    DOCUMENT ||--|| APPLICANT_RÉSUMÉ : "inherits"
    DOCUMENT ||--|| APPLICATION_FORM : "inherits"
    CASE_DETAIL ||--|| APPLICATION_FRAUD_CASE : "inherits"
    APPLICATION_FRAUD_CASE ||--|| APPLICATION_IDENTITY_THEFT : "inherits"
    GEOGRAPHICAL_AREA ||--|| AREA_JAPAN : "inherits"
    DOCUMENT ||--|| BANK_DRAFT : "inherits"
    GEOGRAPHICAL_AREA ||--|| BLOCK_JAPAN : "inherits"
    CHECK_IMAGE ||--|| BOFD_CHECK_IMAGE : "inherits"
    ACCESS_DEVICE ||--|| CARD : "inherits"
    CASH_MANAGEMENT ||--|| CASH_HANDLING : "inherits"
    GEOGRAPHICAL_AREA ||--|| CENSUS_BLOCK__GEO : "inherits"
    GEOGRAPHICAL_AREA ||--|| CENSUS_BLOCK_GROUP__GEO : "inherits"
    GEOGRAPHICAL_AREA ||--|| CENSUS_TRACT__GEO : "inherits"
    GOVERNMENT ||--|| CENTRAL_BANK : "inherits"
    BANK_DRAFT ||--|| CHECK_IMAGE : "inherits"
    GEOGRAPHICAL_AREA ||--|| CITY : "inherits"
    GEOGRAPHICAL_AREA ||--|| CITY_JAPAN : "inherits"
    COA_CODE_BALANCE ||--|| COA_QUANTITATIVE_BALANCE : "inherits"
    TIME_BAND_SCHEME ||--|| COMMODITY_TIME_BAND_SCHEME : "inherits"
    STOCK ||--|| COMMON_STOCK : "inherits"
    GEOGRAPHICAL_AREA ||--|| COUNTY : "inherits"
    STOCK ||--|| CUMULATIVE_PREFERRED_STOCK : "inherits"
    GEOGRAPHICAL_AREA ||--|| CUSTOM_AREA : "inherits"
    CARD ||--|| DEBIT_CARD : "inherits"
    DERIVED_WEATHER ||--|| DEGREE_DAYS_DAILY : "inherits"
    AD ||--|| DIRECT_MAIL_AD : "inherits"
    PAY_ELEMENT ||--|| DIRECT_PAY_ELEMENT : "inherits"
    DIRECT_PAY_ELEMENT ||--|| DIRECT_PAY_ELEMENT_FIXED : "inherits"
    DIRECT_PAY_ELEMENT ||--|| DIRECT_PAY_ELEMENT_VARIABLE : "inherits"
    GEOGRAPHICAL_AREA ||--|| DISTRICT_JAPAN : "inherits"
    AR_COLLECTION_ACTIVITY ||--|| DUNNING_LETTER : "inherits"
    WORK_PROCESS_STEP_ACTUAL ||--|| EMPLOYMENT_WORK_PROCESS_STEP_ACTUAL : "inherits"
    PROJECT ||--|| EXTERNAL_PROJECT : "inherits"
    WATCH_LIST_SOURCE ||--|| EXTERNAL_WATCH_LIST_SOURCE : "inherits"
    GOVERNMENT ||--|| FINANCIAL_REGULATOR : "inherits"
    WEATHER_FORECAST ||--|| FORECAST_CONDITION : "inherits"
    WEATHER_FORECAST ||--|| FORECAST_OBSERVATION : "inherits"
    SUBJECT ||--|| GEOGRAPHIC_AREA_SUBJECT : "inherits"
    GEOGRAPHICAL_AREA ||--|| GEOPOLITICAL_AREA : "inherits"
    TRAIT ||--|| GEOSEQUENCE_POINT_TRAIT : "inherits"
    GEOSPATIAL ||--|| GEOSPATIAL_AREA : "inherits"
    GEOSPATIAL ||--|| GEOSPATIAL_LINE_CURVE : "inherits"
    GEOSPATIAL ||--|| GEOSPATIAL_POINT : "inherits"
    GEOSPATIAL ||--|| GEOSPATIAL_SET : "inherits"
    CHECK_IMAGE ||--|| HOME_BANK_CHECK_IMAGE : "inherits"
    CERTIFICATION_OF_MEDICAL_NECESSITY ||--|| HOME_HEALTH_CERTIFICATION : "inherits"
    TIME_BAND_RELATED ||--|| HORIZONTAL_DISALLOWANCE_PARAMETER : "inherits"
    PAY_ELEMENT ||--|| INDIRECT_PAY_ELEMENT : "inherits"
    INSURANCE_PROVIDER ||--|| INSURANCE_COMPANY : "inherits"
    INSURANCE_PROVIDER ||--|| INSURANCE_POOL : "inherits"
    TRANCHE ||--|| INTEREST_ONLY_STRIP : "inherits"
    PROJECT ||--|| INTERNAL_PROJECT : "inherits"
    PROJECT ||--|| JOINT_PROJECT : "inherits"
    DOCUMENT ||--|| LEGAL_DOCUMENT : "inherits"
    WATCH_LIST_MEMBER ||--|| MATCH_LIST_MEMBER : "inherits"
    MEASUREMENT ||--|| MEASUREMENT_READING : "inherits"
    MEASUREMENT ||--|| MEASUREMENT_STANDARD_CONDITION : "inherits"
    GEOGRAPHICAL_AREA ||--|| METROPOLITAN_STATISTICAL_AREA__GEO : "inherits"
    MULTIMEDIA_OBJECT ||--|| MULTIMEDIA_AUDIO_OBJECT : "inherits"
    MULTIMEDIA_OBJECT ||--|| MULTIMEDIA_IMAGE_OBJECT : "inherits"
    MULTIMEDIA_OBJECT ||--|| MULTIMEDIA_TEXT_OBJECT : "inherits"
    MULTIMEDIA_OBJECT ||--|| MULTIMEDIA_VIDEO_OBJECT : "inherits"
    DOCUMENT ||--|| OTHER_DOCUMENT : "inherits"
    STOCK ||--|| PAIRED_SHARE : "inherits"
    STOCK ||--|| PARTICIPATING_PREFERRED_STOCK : "inherits"
    TRANCHE ||--|| PLANNED_AMORTIZATION_CLASS : "inherits"
    GEOGRAPHICAL_AREA ||--|| PREFECTURE_JAPAN : "inherits"
    STOCK ||--|| PREFERRED_STOCK : "inherits"
    AD ||--|| PRINT_AD : "inherits"
    PROJECT_TASK_RESOURCE_ASSIGNMENT ||--|| PROJECT_TASK_RESOURCE_ITEM : "inherits"
    PROJECT_TASK_RESOURCE_ITEM ||--|| PROJECT_TASK_RESOURCE_SUPPLY : "inherits"
    REFERRAL ||--|| REFERRAL_DIRECTORY : "inherits"
    INSURANCE_PROVIDER ||--|| REINSURANCE_COMPANY : "inherits"
    TRADITIONAL_REQUEST_PLACEMENT ||--|| REQUEST_PLACEMENT_BROADCAST : "inherits"
    DIGITAL_REQUEST_PLACEMENT ||--|| REQUEST_PLACEMENT_INTERACTIVE : "inherits"
    TRADITIONAL_REQUEST_PLACEMENT ||--|| REQUEST_PLACEMENT_OUTDOOR : "inherits"
    TRADITIONAL_REQUEST_PLACEMENT ||--|| REQUEST_PLACEMENT_PRINT : "inherits"
    DIGITAL_REQUEST_PLACEMENT ||--|| REQUEST_PLACEMENT_WEB : "inherits"
    GEOSPATIAL ||--|| ROADWAY : "inherits"
    GEOSPATIAL ||--|| ROADWAY_SEGMENT : "inherits"
    TEXT_SECTION_RELATED ||--|| SECTION_CONTAINS_SECTION : "inherits"
    OTHER_FINANCIAL_SERVICE ||--|| SECURITIES_ORIGINATION : "inherits"
    TRAIT ||--|| SITE_TRAIT : "inherits"
    PHARMACEUTICAL_DRUG ||--|| SPECIALTY_DRUG : "inherits"
    STOCK ||--|| STOCK_ISSUE_DETAIL : "inherits"
    LEGAL_ACTION ||--|| SUBROGATION : "inherits"
    STOCK ||--|| SUBSCRIPTION_RIGHT : "inherits"
    STOCK ||--|| SUBSCRIPTION_WARRANT : "inherits"
    DOCUMENT ||--|| SUSPICIOUS_ACTIVITY_REPORT : "inherits"
    TRANCHE ||--|| TARGETED_AMORTIZATION_CLASS : "inherits"
    TEXT_SECTION ||--|| TEXT_DATASET : "inherits"
    TEXT_SECTION ||--|| TEXT_PARAGRAPH : "inherits"
    TEXT_SECTION ||--|| TEXT_PHRASE : "inherits"
    TEXT_SECTION ||--|| TEXT_SENTENCE : "inherits"
    TEXT_SECTION ||--|| TEXT_TAG : "inherits"
    TEXT_SECTION ||--|| TEXT_TERM : "inherits"
    GEOGRAPHICAL_AREA ||--|| TIME_ZONE_AREA : "inherits"
    AD ||--|| TRAILER_AD : "inherits"
    OTHER_FINANCIAL_SERVICE ||--|| TRUST_ESTATE : "inherits"
    AD ||--|| TV_AD : "inherits"
    RECEIPT_LINE ||--|| VENDOR_RECEIPT_LINE : "inherits"
    DERIVED_WEATHER ||--|| WEATHER_ALMANAC_DAILY : "inherits"
    WEATHER_OBSERVATION ||--|| WEATHER_CONDITION_OBSERVED : "inherits"
    OBSERVATION_TYPE ||--|| WEATHER_CONDITION_TYPE : "inherits"
    WEATHER_OBSERVATION ||--|| WEATHER_MEASURE : "inherits"
    WEATHER_OBSERVATION ||--|| WEATHER_MEASURE_DAILY : "inherits"
    OBSERVATION_TYPE ||--|| WEATHER_MEASURE_TYPE : "inherits"
    DERIVED_WEATHER ||--|| WEATHER_NORMALS_DAILY : "inherits"
    SITE ||--|| WEATHER_STATION : "inherits"