erDiagram
    AD_CONTACT_XREF {
        Identifier Ad_Id "PK"
        Identifier Contact_Event_Id "PK"
    }
    AD_ORDER_PARTY {
        Code Ad_Order_Party_Role_Cd "PK"
        Identifier Ad_Order_Party_id "PK"
        Identifier Ad_Order_Header_Id "PK"
        Date Party_Ad_Order_Header_Start_Dt "PK"
        Date Party_Ad_Order_Header_End_Dt ""
    }
    AD_ORDER_PARTY_ROLE {
        Code Ad_Order_Party_Role_Cd "PK"
        Description Ad_Order_Party_Role_Desc ""
    }
    AGREEMENT_IDENTIFICATION {
        Identifier Agreement_Id "PK"
        Code Agreement_Identification_Type_Cd "PK"
        Datetime Agreement_Identifier_Start_Dttm "PK"
        Identifier Issuing_Organization_Party_Id ""
        Datetime Agreement_Identifier_End_Dttm ""
        string more "1 more"
    }
    AGREEMENT_IDENTIFICATION_CATEGORY {
        Code Agreement_Identification_Category_Cd "PK"
        Description Agreement_Identification_Category_Desc ""
    }
    AGREEMENT_IDENTIFICATION_TYPE {
        Code Agreement_Identification_Type_Cd "PK"
        Description Agreement_Identification_Type_Desc ""
    }
    AGREEMENT_INSURED_PARTY {
        Number Member_Num ""
    }
    AGREEMENT_LOCATOR {
        Identifier Agreement_Id "PK"
        Code Agreement_Locator_Role_Type_Cd "PK"
        Identifier Locator_Id "PK"
        Date Agreement_Locator_Start_Dt "PK"
        Date Agreement_Locator_End_Dt ""
    }
    AGREEMENT_LOCATOR_ROLE {
        Code Agreement_Locator_Role_Type_Cd "PK"
        Description Agreement_Locator_Role_Type_Desc ""
    }
    AGREEMENT_PARTY_FEATURE {
        Identifier Party_Id "PK"
        Identifier Agreement_Id "PK"
        Code Party_Agreement_Role_Cd "PK"
        Date Party_Agreement_Start_Dt "PK"
        Identifier Feature_Id "PK"
        string more "3 more"
    }
    AGREEMENT_PARTY_FEATURE_RELATED {
        Identifier Party_Id "PK"
        Identifier Agreement_Id "PK"
        Code Party_Agreement_Role_Cd "PK"
        Date Party_Agreement_Start_Dt "PK"
        Identifier Feature_Id "PK"
        string more "5 more"
    }
    AGREEMENT_PARTY_TEXT {
        Identifier Party_Id "PK"
        Identifier Agreement_Id "PK"
        Code Party_Agreement_Role_Cd "PK"
        Date Party_Agreement_Start_Dt "PK"
        Datetime Agreement_Party_Text_Dttm "PK"
        string more "3 more"
    }
    ALERT_SETUP_NOTIFICATION_LOCATOR {
        Identifier Alert_Setup_Id "PK"
        Identifier Locator_Id "PK"
        Code Transmittal_Mode_Type_Cd "PK"
    }
    ALERT_SETUP_NOTIFICATION_PARTY {
        Identifier Alert_Setup_Id "PK"
        Identifier Alert_Setup_Party_Id "PK"
        Code Alert_Setup_Notification_Level_Cd "PK"
        Date Alert_Setup_Party_Hierarchy_Start_Dt "PK"
        Date Alert_Party_Hierarchy_End_Dt ""
        string more "4 more"
    }
    ANALYTICAL_MODEL_PARTY {
        Identifier Model_Id "PK"
        Identifier Party_Id "PK"
        Code Analytical_Model_Party_Role_Cd "PK"
        Date Analytical_Model_Party_Start_Dt "PK"
        Date Analytical_Model_Party_End_Dt ""
    }
    ANALYTICAL_MODEL_PARTY_ROLE {
        Code Analytical_Model_Party_Role_Cd "PK"
        Description Analytical_Model_Party_Role_Desc ""
    }
    APPLICATION_LOCATOR {
        Identifier Application_Id "PK"
        Code Agreement_Locator_Role_Type_Cd "PK"
        Identifier Locator_Id "PK"
        Date Application_Address_Start_Dt "PK"
        Date Application_Address_End_Dt ""
    }
    APPLICATION_PARTY_PRODUCT {
        Identifier Application_Id "PK"
        Identifier Party_Id "PK"
        Identifier Product_Id "PK"
        Date Application_Party_Policy_Start_Dt "PK"
        Date Application_Party_Policy_End_Dt ""
    }
    ASSET_INSPECTION_PARTY {
        Identifier Party_Id "PK"
        Identifier Party_Asset_Id "PK"
        Date Inspection_Dt "PK"
        Code Party_Asset_Inspection_Role_Cd "PK"
    }
    ASSOCIATE {
        Identifier Associate_Party_Id "PK"
        Identifier Primary_Site_Id ""
        Number Associate_Human_Resource_Num ""
    }
    ASSOCIATE_BENEFICIARY {
        Identifier Beneficiary_Party_Id "PK"
        Identifier Associate_Party_Id "PK"
        Identifier Benefit_Plan_Id "PK"
        Identifier Benefit_Plan_Option_Id "PK"
        Date Associate_Benefit_Period_Start_Dt "PK"
        string more "3 more"
    }
    ASSOCIATE_BENEFIT_PLAN {
        Identifier Associate_Party_Id "PK"
        Identifier Benefit_Plan_Id "PK"
        Identifier Benefit_Plan_Option_Id "PK"
        Date Associate_Benefit_Period_Start_Dt "PK"
        Date Associate_Benefit_Period_End_Dt ""
    }
    ASSOCIATE_CONTACT {
        Identifier Associate_Contact_Party_Id "PK"
        Identifier Associate_Party_Id "PK"
        Number Associate_Contact_Sequence_Num ""
        Code Associate_Relationship_Type_Cd ""
    }
    ASSOCIATE_DEDUCTION {
        Code Associate_Deduction_Subtype_Cd ""
    }
    ASSOCIATE_DEDUCTION_SUBTYPE {
        Code Associate_Deduction_Subtype_Cd "PK"
        Description Associate_Deduction_Subtype_Desc ""
    }
    ASSOCIATE_EMPLOYMENT {
        Identifier Associate_Party_Id "PK"
        Identifier Organization_Party_Id "PK"
        Date Associate_Employment_Start_Dt "PK"
        Date Associate_Employment_End_Dt ""
        Date Associate_Hire_Dt ""
        string more "2 more"
    }
    ASSOCIATE_EMPLOYMENT_BASIS {
        Code Employment_Basis_Type_Cd "PK"
        Identifier Associate_Party_Id "PK"
        Date Employment_Basis_Start_Dt "PK"
        Date Employment_Basis_End_Dt "PK"
    }
    ASSOCIATE_FUNCTION {
        Code Function_Cd "PK"
        Identifier Associate_Party_Id "PK"
        Date Associate_Function_Start_Dt "PK"
        Date Associate_Function_End_Dt ""
    }
    ASSOCIATE_JOB_CLASSIFICATION {
        Identifier Associate_Party_Id "PK"
        Code Job_Classification_Cd "PK"
        Date Associate_Job_Classification_Start_Dt "PK"
        Date Associate_Job_Classification_End_Dt ""
    }
    ASSOCIATE_JOB_CLASSIFICATION_LABOR_ACTUAL {
        Identifier Site_Id "PK"
        Identifier Associate_Party_Id "PK"
        Date Labor_Pool_Start_Dt "PK"
        Code Work_Shift_Cd "PK"
        Code Job_Classification_Cd "PK"
        string more "3 more"
    }
    ASSOCIATE_JOB_CLASSIFICATION_SHIFT_SCHEDULE {
        Identifier Site_Id "PK"
        Code Work_Shift_Cd "PK"
        Code Job_Classification_Cd "PK"
        Date Labor_Dt "PK"
        Identifier Associate_Party_Id "PK"
        string more "3 more"
    }
    ASSOCIATE_LABOR_TASK {
        Identifier Associate_Party_Id "PK"
        Identifier Labor_Task_Type_Id "PK"
        Datetime Labor_Task_Start_Dttm "PK"
        Datetime Labor_Task_End_Dttm ""
        Name Labor_Task_Name ""
        string more "8 more"
    }
    ASSOCIATE_LEAVE_EARNED {
        Identifier Associate_Party_Id "PK"
        Identifier Internal_Organization_Party_Id "PK"
        Code Associate_Leave_Type_Cd "PK"
        Datetime Associate_Leave_Earned_Start_Dttm "PK"
        Datetime Associate_Leave_Earned_End_Dttm ""
        string more "2 more"
    }
    ASSOCIATE_LEAVE_PLAN {
        Identifier Associate_Party_Id "PK"
        Code Associate_Leave_Type_Cd "PK"
        Date Associate_Leave_Plan_Start_Dt "PK"
        Date Associate_Leave_Plan_End_Dt ""
        Quantity Associate_Planned_Leave_Qty ""
        string more "2 more"
    }
    ASSOCIATE_LEAVE_REASON {
        Code Associate_Leave_Reason_Cd "PK"
        Description Associate_Leave_Reason_Desc ""
    }
    ASSOCIATE_LEAVE_TAKEN {
        Identifier Associate_Party_Id "PK"
        Datetime Associate_Leave_Start_Dttm "PK"
        Datetime Associate_Leave_End_Dttm ""
        Quantity Associate_Leave_Qty ""
        Code Associate_Leave_UOM_Cd "PK"
        string more "3 more"
    }
    ASSOCIATE_LEAVE_TYPE {
        Code Associate_Leave_Type_Cd "PK"
        Description Associate_Leave_Type_Desc ""
    }
    ASSOCIATE_ORGANIZATION_POSITION {
        Identifier Associate_Party_Id "PK"
        Identifier Internal_Organization_Party_Id "PK"
        Date Position_Grade_Start_Dt "PK"
        Identifier HR_Position_Id "PK"
        Code Position_Grade_Type_Cd "PK"
        string more "5 more"
    }
    ASSOCIATE_PAYROLL_TRANSACTION {
        Identifier Associate_Payroll_Transaction_Id "PK"
        Identifier Payroll_Register_Id "PK"
        Datetime Associate_Payroll_Transaction_Dttm ""
        Amount Associate_Payroll_Transaction_Amt ""
        Quantity Associate_Payroll_Transaction_Qty ""
        string more "6 more"
    }
    ASSOCIATE_PAY_ELEMENT {
        Identifier Associate_Party_Id "PK"
        Identifier Pay_Element_Id "PK"
        Date Associate_Pay_Element_Start_Dt "PK"
        Date Associate_Pay_Element_End_Dt ""
    }
    ASSOCIATE_PERFORMANCE_EVALUATION {
        Identifier Associate_Party_Id "PK"
        Number Associate_Evaluation_Year_Num "PK"
        Code Associate_Evaluation_Time_Period_Cd "PK"
        Count Associate_Evaluation_Period_Cnt "PK"
        Date Associate_Evaluation_Deliver_Dt "PK"
        string more "4 more"
    }
    ASSOCIATE_PERFORMANCE_EVALUATION_DETAIL {
        Identifier Associate_Party_Id "PK"
        Number Associate_Evaluation_Year_Num "PK"
        Code Associate_Evaluation_Time_Period_Cd "PK"
        Count Associate_Evaluation_Period_Cnt "PK"
        Identifier Objective_Id "PK"
        string more "2 more"
    }
    ASSOCIATE_PERFORMANCE_GRADE_TYPE {
        Code Associate_Performance_Grade_Type_Cd "PK"
        Description Associate_Performance_Grade_Type_Desc ""
    }
    ASSOCIATE_PLAN_CONTRIBUTION {
        Identifier Associate_Party_Id "PK"
        Identifier Benefit_Plan_Id "PK"
        Identifier Benefit_Plan_Option_Id "PK"
        Code Associate_Plan_Contribution_Type_Cd "PK"
        Date Associate_Benefit_Period_Start_Dt "PK"
        string more "2 more"
    }
    ASSOCIATE_PLAN_CONTRIBUTION_TYPE {
        Code Associate_Plan_Contribution_Type_Cd "PK"
        Description Associate_Plan_Contribution_Type_Desc ""
    }
    ASSOCIATE_POSITION_STATUS {
        Identifier Associate_Party_Id "PK"
        Date Position_Grade_Start_Dt "PK"
        Identifier HR_Position_Id "PK"
        Code Position_Grade_Type_Cd "PK"
        Date Organization_Position_Start_Dt "PK"
        string more "5 more"
    }
    ASSOCIATE_POSITION_STATUS_TYPE {
        Code Associate_Position_Status_Type_Cd "PK"
        Description Associate_Position_Status_Type_Desc ""
    }
    ASSOCIATE_RELATIONSHIP_TYPE {
        Code Associate_Relationship_Type_Cd "PK"
        Description Associate_Relationship_Type_Desc ""
    }
    ASSOCIATE_STATUS {
        Identifier Associate_Party_Id "PK"
        Code Associate_Status_Scheme_Type_Cd "PK"
        Datetime Associate_Status_Dttm "PK"
        Code Associate_Status_Type_Cd "PK"
        Datetime Associate_Status_Effective_Dttm ""
    }
    ASSOCIATE_STATUS_REASON {
        Identifier Associate_Party_Id "PK"
        Code Associate_Status_Scheme_Type_Cd "PK"
        Datetime Associate_Status_Dttm "PK"
        Code Associate_Status_Reason_Cd "PK"
    }
    ASSOCIATE_STATUS_REASON_TYPE {
        Code Associate_Status_Reason_Cd "PK"
        Description Associate_Status_Reason_Desc ""
    }
    ASSOCIATE_STATUS_SCHEME_TYPE {
        Code Associate_Status_Scheme_Type_Cd "PK"
        Description Associate_Status_Scheme_Type_Desc ""
    }
    ASSOCIATE_STATUS_TYPE {
        Code Associate_Status_Type_Cd "PK"
        Description Associate_Status_Type_Desc ""
    }
    BANKING_LINE_OF_BUSINESS_TYPE {
        Code Banking_Line_Of_Business_Cd "PK"
        Description Banking_Line_Of_Business_Desc ""
    }
    BANK_IDENTIFICATION_NUMBER {
        string Bank_Identification_Num "PK"
        Identifier Party_Id ""
        Identifier Issuing_Party_Id ""
        Code Party_Identification_Type_Cd ""
        Datetime Party_Identification_Start_Dttm ""
    }
    BASEL_ORGANIZATION_TYPE {
        Code Basel_Organization_Type_Cd "PK"
        Description Basel_Organization_Type_Desc ""
    }
    BIC_BUSINESS_TYPE {
        string BIC_Business_Alpha_4_Cd "PK"
        Description BIC_Business_Desc ""
    }
    BROWSER_IDENTIFICATION {
        Identifier Browser_Identification_Id "PK"
        Code Browser_Application_Cd "PK"
        Number Browser_Application_Version_Num "PK"
        Number Operating_System_Num ""
        Number Operating_System_Version_Num ""
        string more "3 more"
    }
    INDIVIDUAL ||--o{ INDIVIDUAL_NAME : ""
    INTERNAL_ORGANIZATION_TYPE ||--o{ INTERNAL_ORGANIZATION : ""
    LOCATOR ||--o{ PARTY_LOCATOR : ""
    ORGANIZATION ||--o{ ORGANIZATION : ""
    ORGANIZATION ||--o{ ORGANIZATION_NAME : ""
    PARTY ||--o{ PARTY_ADDRESS : ""
    PARTY ||--o{ PARTY_LOCATOR : ""
    PARTY ||--o{ PARTY_IDENTIFICATION : ""
    PARTY ||--o{ DEMO_PARTY : ""
    PARTY_SUBTYPE ||--o{ PARTY : ""
    AD_ORDER_PARTY_ROLE ||--o{ AD_ORDER_PARTY : ""
    AGREEMENT_IDENTIFICATION_CATEGORY ||--o{ AGREEMENT_IDENTIFICATION : ""
    AGREEMENT_IDENTIFICATION_TYPE ||--o{ AGREEMENT_IDENTIFICATION : ""
    AGREEMENT_INSURED_PARTY ||--o{ INDIVIDUAL_MORTALITY : ""
    AGREEMENT_INSURED_PARTY ||--o{ INSURED_PARTY_UNDERWRITE_CLASS : ""
    AGREEMENT_LOCATOR_ROLE ||--o{ AGREEMENT_LOCATOR : ""
    AGREEMENT_LOCATOR_ROLE ||--o{ QUOTATION_LOCATOR : ""
    AGREEMENT_LOCATOR_ROLE ||--o{ APPLICATION_LOCATOR : ""
    AGREEMENT_PARTY_FEATURE ||--o{ POLICY_PARTY_COVERAGE_METRIC : ""
    AGREEMENT_PARTY_FEATURE ||--o{ AGREEMENT_PARTY_FEATURE_RELATED : ""
    ANALYTICAL_MODEL_PARTY_ROLE ||--o{ ANALYTICAL_MODEL_PARTY : ""
    ANALYTICAL_MODEL_PARTY_ROLE ||--o{ MODEL_RUN_PARTY : ""
    ASSOCIATE ||--o{ ASSOCIATE_PAYROLL_TRANSACTION : ""
    ASSOCIATE ||--o{ ASSOCIATE_PAY_ELEMENT : ""
    ASSOCIATE ||--o{ ASSOCIATE_LABOR_TASK : ""
    ASSOCIATE ||--o{ ASSOCIATE_JOB_CLASSIFICATION : ""
    ASSOCIATE ||--o{ ASSOCIATE_LEAVE_EARNED : ""
    ASSOCIATE ||--o{ ASSOCIATE_EMPLOYMENT_BASIS : ""
    ASSOCIATE ||--o{ ASSOCIATE_STATUS : ""
    ASSOCIATE ||--o{ ASSOCIATE_EMPLOYMENT : ""
    ASSOCIATE ||--o{ ASSOCIATE_LEAVE_TAKEN : ""
    ASSOCIATE ||--o{ ASSOCIATE_CONTACT : ""
    ASSOCIATE ||--o{ ASSOCIATE_BENEFIT_PLAN : ""
    ASSOCIATE ||--o{ ASSOCIATE_PERFORMANCE_EVALUATION : ""
    ASSOCIATE ||--o{ ASSOCIATE_LEAVE_PLAN : ""
    ASSOCIATE ||--o{ ASSOCIATE_FUNCTION : ""
    ASSOCIATE_BENEFIT_PLAN ||--o{ ASSOCIATE_BENEFICIARY : ""
    ASSOCIATE_BENEFIT_PLAN ||--o{ ASSOCIATE_PLAN_CONTRIBUTION : ""
    ASSOCIATE_DEDUCTION_SUBTYPE ||--o{ ASSOCIATE_DEDUCTION : ""
    ASSOCIATE_LEAVE_REASON ||--o{ ASSOCIATE_LEAVE_PLAN : ""
    ASSOCIATE_LEAVE_REASON ||--o{ ASSOCIATE_LEAVE_TAKEN : ""
    ASSOCIATE_LEAVE_TYPE ||--o{ ASSOCIATE_LEAVE_TAKEN : ""
    ASSOCIATE_LEAVE_TYPE ||--o{ ASSOCIATE_LEAVE_PLAN : ""
    ASSOCIATE_LEAVE_TYPE ||--o{ ASSOCIATE_LEAVE_EARNED : ""
    ASSOCIATE_ORGANIZATION_POSITION ||--o{ ASSOCIATE_POSITION_STATUS : ""
    ASSOCIATE_PERFORMANCE_EVALUATION ||--o{ ASSOCIATE_PERFORMANCE_EVALUATION_DETAIL : ""
    ASSOCIATE_PERFORMANCE_GRADE_TYPE ||--o{ ASSOCIATE_PERFORMANCE_EVALUATION_DETAIL : ""
    ASSOCIATE_PERFORMANCE_GRADE_TYPE ||--o{ ASSOCIATE_PERFORMANCE_EVALUATION : ""
    ASSOCIATE_PLAN_CONTRIBUTION_TYPE ||--o{ ASSOCIATE_PLAN_CONTRIBUTION : ""
    ASSOCIATE_POSITION_STATUS_TYPE ||--o{ ASSOCIATE_POSITION_STATUS : ""
    ASSOCIATE_RELATIONSHIP_TYPE ||--o{ ASSOCIATE_CONTACT : ""
    ASSOCIATE_RELATIONSHIP_TYPE ||--o{ ASSOCIATE_BENEFICIARY : ""
    ASSOCIATE_STATUS ||--o{ ASSOCIATE_STATUS_REASON : ""
    ASSOCIATE_STATUS_REASON_TYPE ||--o{ ASSOCIATE_STATUS_REASON : ""
    ASSOCIATE_STATUS_SCHEME_TYPE ||--o{ ASSOCIATE_STATUS : ""
    ASSOCIATE_STATUS_TYPE ||--o{ ASSOCIATE_STATUS : ""
    BASEL_ORGANIZATION_TYPE ||--o{ ORGANIZATION : ""
    BIC_BUSINESS_TYPE ||--o{ BUSINESS_IDENTIFIER_CODE_ADDRESS : ""
    BIC_BUSINESS_TYPE ||--o{ ORGANIZATION : ""
    BUSINESS ||--o{ INDIVIDUAL_PAY_TIMING : ""
    BUSINESS_CASE_TYPE ||--o{ BUSINESS_CASE : ""
    BUSINESS_CATEGORY ||--o{ BUSINESS : ""
    BUSINESS_LINE_LOSS_TYPE_MEASURE ||--o{ BUSINESS_LINE_LOSS_SCORE : ""
    BUSINESS_LINE_LOSS_TYPE_MEASURE ||--o{ BUSINESS_UNIT_OPERATIONAL_RISK_ADVANCED : ""
    BUSINESS_LINE_RISK_MEASURE ||--o{ BUSINESS_UNIT_OPERATIONAL_RISK_STANDARDIZED : ""
    CALL_CENTER_CONTACT_TYPE ||--o{ CALL_CENTER_CONTACT_EVENT : ""
    CAMPAIGN_LOCATOR_RELATIONSHIP_TYPE ||--o{ CAMPAIGN_LOCATOR : ""
    CAMPAIGN_PARTY_ROLE ||--o{ CONTACT_LIST_MANAGEMENT : ""
    CAMPAIGN_PARTY_ROLE ||--o{ CAMPAIGN_PARTY : ""
    CASE_PARTY_ROLE_TYPE ||--o{ CASE_PARTY : ""
    CHANNEL_INSTANCE_LOCATOR_REASON ||--o{ CHANNEL_INSTANCE_LOCATOR : ""
    CLAIM_IDENTIFICATION_TYPE ||--o{ CLAIM_IDENTIFICATION : ""
    CLAIM_LOCATOR_ROLE ||--o{ CLAIM_LOCATOR : ""
    COMPLEMENTARY_IDENTIFICATION_CODE_CATEGORY ||--o{ COMPLEMENTARY_IDENTIFICATION_CODE_SUBCATEGORY : ""
    COMPLEMENTARY_IDENTIFICATION_CODE_EXCEPTION ||--o{ INVESTMENT_PRODUCT_COMPLEMENTARY_IDENTIFICATION_CODE : ""
    COMPLEMENTARY_IDENTIFICATION_CODE_EXCEPTION ||--o{ FIXED_ASSET_COMPLEMENTARY_IDENTIFICATION_CODE : ""
    COMPLEMENTARY_IDENTIFICATION_CODE_SUBCATEGORY ||--o{ FIXED_ASSET_COMPLEMENTARY_IDENTIFICATION_CODE : ""
    COMPLEMENTARY_IDENTIFICATION_CODE_SUBCATEGORY ||--o{ INVESTMENT_PRODUCT_COMPLEMENTARY_IDENTIFICATION_CODE : ""
    CONTACT_ACTION_SUBTYPE ||--o{ CONTACT_ACTION : ""
    CONTACT_ACTION_TYPE ||--o{ CONTACT_ACTION : ""
    CONTACT_EVENT ||--o{ SALES_MARKETING_ACTIVITY_CONTACT : ""
    CONTACT_EVENT ||--o{ LEAD_CONTACT_EVENT : ""
    CONTACT_EVENT ||--o{ CONTACT_RESOLUTION : ""
    CONTACT_EVENT ||--o{ AD_CONTACT_XREF : ""
    CONTACT_EVENT ||--o{ PROMOTION_PARTY_STEP_RESPONSE : ""
    CONTACT_EVENT ||--o{ CONTACT_FOLLOW_UP : ""
    CONTACT_EVENT ||--o{ PROMOTION_PARTY_STEP : ""
    CONTACT_EVENT ||--o{ CONTACT_EVENT_OFFER : ""
    CONTACT_EVENT ||--o{ CONTACT_ACTION : ""
    CONTACT_EVENT ||--o{ CONTACT_SCRIPT : ""
    CONTACT_EVENT_SUBTYPE ||--o{ CONTACT_EVENT : ""
    CONTACT_FOLLOW_UP_TYPE ||--o{ CONTACT_FOLLOW_UP : ""
    CONTACT_FOLLOW_UP_TYPE ||--o{ CONTACT_EVENT_OFFER : ""
    CONTACT_INITIATION_TYPE ||--o{ DIRECT_CONTACT_EVENT : ""
    CONTACT_LIST ||--o{ CONTACT_LIST_MANAGEMENT : ""
    CONTACT_LIST ||--o{ CELL_TARGET_CONTACT_LIST : ""
    CONTACT_LIST ||--o{ CAMPAIGN_TARGET_CONTACT_LIST : ""
    CONTACT_LIST ||--o{ CONTACT_LIST_UPDATE : ""
    CONTACT_LIST_AVAILABILITY_TYPE ||--o{ CONTACT_LIST : ""
    CONTACT_LIST_SOURCE_TYPE ||--o{ CONTACT_LIST : ""
    CONTACT_OUTCOME_TYPE ||--o{ CONTACT_EVENT : ""
    CONTACT_OUTCOME_TYPE ||--o{ CONTACT_EVENT_OFFER : ""
    CONTACT_REASON_TYPE ||--o{ CONTACT_EVENT : ""
    CONTACT_RESOLUTION_TYPE ||--o{ CONTACT_RESOLUTION : ""
    CREDIT_REPORTING_PARTY_SUBTYPE ||--o{ PARTY_CREDIT_REPORT : ""
    CUSTOMER_LOCATION_TYPE ||--o{ BUSINESS : ""
    CUSTOMER_TONE_TYPE ||--o{ DIRECT_CONTACT_EVENT : ""
    DEMOGRAPHIC ||--o{ LOCATOR_DEMOGRAPHIC : ""
    DEMOGRAPHIC ||--o{ PARTY_APPLICATION_DEMOGRAPHIC : ""
    DEMOGRAPHIC ||--o{ PRODUCT_DEMOGRAPHIC : ""
    DEMOGRAPHIC ||--o{ PARTY_DEMOGRAPHIC : ""
    DEMOGRAPHIC ||--o{ FEATURE_DEMOGRAPHIC_ELIGIBILITY : ""
    DEMOGRAPHIC ||--o{ CHANNEL_DEMOGRAPHIC : ""
    DEMOGRAPHIC ||--o{ PRODUCT_FEATURE_DEMOGRAPHIC_ELIGIBILITY : ""
    DEMOGRAPHIC ||--o{ DEMOGRAPHIC_VALUE : ""
    DEMOGRAPHIC ||--o{ MARKET_SEGMENT_DEMOGRAPHIC : ""
    DEMOGRAPHIC ||--o{ PRODUCT_DEMOGRAPHIC_ELIGIBILITY : ""
    DEMOGRAPHIC ||--o{ PARTY_GROUP_DEMOGRAPHIC : ""
    DEMOGRAPHIC_GROUP ||--o{ DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ PARTY_APPLICATION_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ LOCATOR_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ MARKET_SEGMENT_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ PARTY_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ ORDER_PLACEMENT_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ PARTY_GROUP_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ ONLINE_APPLICATION_ACCESS_SEGMENT_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ FEATURE_DEMOGRAPHIC_ELIGIBILITY : ""
    DEMOGRAPHIC_VALUE ||--o{ PRODUCT_FEATURE_DEMOGRAPHIC_ELIGIBILITY : ""
    DEMOGRAPHIC_VALUE ||--o{ PRODUCT_DEMOGRAPHIC_ELIGIBILITY : ""
    DEMOGRAPHIC_VALUE ||--o{ CHANNEL_DEMOGRAPHIC : ""
    DEMOGRAPHIC_VALUE ||--o{ PRODUCT_DEMOGRAPHIC : ""
    DIRECT_CONTACT_TYPE ||--o{ DIRECT_CONTACT_EVENT : ""
    EMAIL_AD ||--o{ EMAIL_REFERRAL : ""
    EMAIL_CLIENT_APPLICATION ||--o{ EMAIL_REFERRAL : ""
    EVENT_LOCATOR_REASON ||--o{ EVENT_LOCATOR : ""
    EVENT_PARTY ||--o{ EVENT_PARTY_TEXT_SECTION : ""
    EVENT_PARTY_ROLE ||--o{ EVENT_PARTY : ""
    FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION ||--o{ BUSINESS_LINE_LOSS_TYPE_MEASURE : ""
    FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION ||--o{ INTERNAL_ORGANIZATION_GROUP_FUNCTION : ""
    FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION ||--o{ INTERNAL_ORGANIZATION_GROUP_SKILL : ""
    FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION ||--o{ INTERNAL_ORGANIZATION_WORKSTATION : ""
    FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION ||--o{ ORGANIZATION_OPERATING_HOURS : ""
    FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION ||--o{ BUSINESS_LINE_RISK_MEASURE : ""
    FIXED_ASSET_IDENTIFICATION_TYPE ||--o{ FIXED_ASSET_IDENTIFICATION : ""
    GEOGRAPHICAL_AREA_IDENTIFICATION_TYPE ||--o{ GEOGRAPHICAL_AREA_IDENTIFICATION : ""
    GL_ORGANIZATION_SEGMENT ||--o{ REPORTING_ORGANIZATION : ""
    HOUSEHOLD ||--o{ HOUSEHOLD_MEMBER : ""
    HR_INTERNAL_ORGANIZATION ||--o{ ASSOCIATE_LEAVE_EARNED : ""
    HR_INTERNAL_ORGANIZATION ||--o{ ORGANIZATION_POSITION : ""
    HR_INTERNAL_ORGANIZATION_TYPE ||--o{ HR_INTERNAL_ORGANIZATION : ""
    IDENTIFICATION_USAGE_TYPE ||--o{ IDENTIFICATION_TYPE_USAGE_TYPE : ""
    INDIVIDUAL ||--o{ HOUSEHOLD_MEMBER : ""
    INDIVIDUAL ||--o{ UNKNOWN_PARTY : ""
    INDIVIDUAL ||--o{ PERSONA : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_PAY_TIMING : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_VIP_STATUS : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_MIGRATION : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_SPECIAL_NEED : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_MILITARY_STATUS : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_MARITAL_STATUS : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_MEDICAL : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_HEALTH_CONDITION : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_SKILL : ""
    INDIVIDUAL ||--o{ INDIVIDUAL_OCCUPATION : ""
    INDIVIDUAL_PAY_TIMING ||--o{ INDIVIDUAL_BONUS_TIMING : ""
    INSURANCE_LINE_OF_BUSINESS_TYPE ||--o{ INSURANCE_AGREEMENT_LINE_OF_BUSINESS : ""
    INSURANCE_LINE_OF_BUSINESS_TYPE ||--o{ INSURANCE_LINE_OF_BUSINESS_METRIC : ""
    INSURANCE_LINE_OF_BUSINESS_TYPE ||--o{ LINE_OF_BUSINESS_PARTY_METRIC : ""
    INSURANCE_LINE_OF_BUSINESS_TYPE ||--o{ INSURANCE_LINE_OF_BUSINESS_TYPE : ""
    INSURANCE_LINE_OF_BUSINESS_TYPE ||--o{ LINE_OF_BUSINESS_RISK_SCENARIO_METRIC : ""
    INTEREST_RATE_INDEX_PARTY_ROLE ||--o{ INTEREST_RATE_INDEX_PARTY : ""
    INTERNAL_ORGANIZATION ||--o{ SET_OF_BOOKS_INTERNAL_ORGANIZATION : ""
    INTERNAL_ORGANIZATION_SUBTYPE ||--o{ INTERNAL_ORGANIZATION : ""
    INVOICE_LINE_PARTY_ROLE ||--o{ INVOICE_LINE_PARTY : ""
    INVOICE_PARTY_ROLE_TYPE ||--o{ INVOICE_PARTY : ""
    LEAD_PARTY_ROLE_TYPE ||--o{ LEAD_PARTY_ROLE : ""
    LEGAL_ACTION_PARTY_ROLE_TYPE ||--o{ PARTY_LEGAL_ACTION : ""
    LINE_OF_BUSINESS_CLASSIFICATION_SCHEME ||--o{ INSURANCE_LINE_OF_BUSINESS_TYPE : ""
    LOCATOR ||--o{ PARTY_ASSET_LOCATOR : ""
    LOCATOR ||--o{ LOCATOR_METRIC : ""
    LOCATOR ||--o{ PROJECT_LOCATOR : ""
    LOCATOR ||--o{ LOCATOR_PERIL_TYPE_METRIC : ""
    LOCATOR ||--o{ ALERT_SETUP_NOTIFICATION_LOCATOR : ""
    LOCATOR ||--o{ VISITOR_LOCATOR : ""
    LOCATOR ||--o{ PAYMENT_INSTRUCTION_LOCATOR : ""
    LOCATOR ||--o{ TRADE_SETTLEMENT_INSTRUCTION_LOCATOR : ""
    LOCATOR ||--o{ SALES_MARKETING_ACTIVITY_LOCATOR : ""
    LOCATOR ||--o{ SITE_LOCATOR : ""
    LOCATOR ||--o{ TRADE_EVENT_SETTLE_LOCATOR : ""
    LOCATOR ||--o{ CHANNEL_INSTANCE_LOCATOR : ""
    LOCATOR ||--o{ ORGANIZATION_POSITION : ""
    LOCATOR ||--o{ PARTY_AGREEMENT_LOCATOR : ""
    LOCATOR ||--o{ CLAIM_LOCATOR : ""
    LOCATOR ||--o{ FEATURE_RELATED_LOCATOR : ""
    LOCATOR ||--o{ PRODUCT_FEATURE_LOCATOR : ""
    LOCATOR ||--o{ CAMPAIGN_LOCATOR : ""
    LOCATOR ||--o{ PRODUCT_LOCATOR : ""
    LOCATOR ||--o{ QUOTATION_LOCATOR : ""
    LOCATOR ||--o{ AGREEMENT_LOCATOR : ""
    LOCATOR ||--o{ APPLICATION_LOCATOR : ""
    LOCATOR ||--o{ FEATURE_LOCATOR : ""
    LOCATOR ||--o{ EVENT_LOCATOR : ""
    LOCATOR ||--o{ LOCATOR_DEMOGRAPHIC : ""
    LOCATOR ||--o{ PARTY_IDENTIFICATION_LOCATOR : ""
    LOCATOR_METRIC_TYPE ||--o{ LOCATOR_PERIL_TYPE_METRIC : ""
    LOCATOR_METRIC_TYPE ||--o{ LOCATOR_METRIC : ""
    LOCATOR_RELATED_REASON ||--o{ LOCATOR_RELATED : ""
    LOCATOR_SUBTYPE ||--o{ LOCATOR : ""
    LOCATOR_USAGE_TYPE ||--o{ PARTY_LOCATOR : ""
    LOCATOR_USAGE_TYPE ||--o{ SITE_LOCATOR : ""
    LOYALTY_PARTY_ROLE_TYPE ||--o{ LOYALTY_PROGRAM_PARTY : ""
    MICROSITE_PARTY_ROLE ||--o{ MICROSITE_PARTY_XREF : ""
    MOBILE_PHONE ||--o{ MOBILE_TELEPHONE_NUMBER : ""
    NAME_TYPE ||--o{ ORGANIZATION_NAME : ""
    NAME_TYPE ||--o{ INDIVIDUAL_NAME : ""
    NAME_TYPE ||--o{ PRODUCT_PARTY_NAME : ""
    NAME_USAGE_TYPE ||--o{ NAME_VALEDICTION : ""
    NAME_USAGE_TYPE ||--o{ NAME_SALUTATION : ""
    ORGANIZATION ||--o{ ASSOCIATE_EMPLOYMENT : ""
    ORGANIZATION ||--o{ ORGANIZATION_SIC__GEO : ""
    ORGANIZATION ||--o{ ORGANIZATION_NAICS__GEO : ""
    ORGANIZATION ||--o{ PRODUCT_IDENTIFICATION : ""
    ORGANIZATION ||--o{ UNKNOWN_PARTY : ""
    ORGANIZATION ||--o{ ORGANIZATION_NACE__GEO : ""
    ORGANIZATION ||--o{ ORGANIZATION_TAX_STATUS : ""
    ORGANIZATION ||--o{ ORGANIZATION_DUNS : ""
    ORGANIZATION ||--o{ ORGANIZATION_BUSINESS_TYPE_XREF : ""
    ORGANIZATION ||--o{ ORGANIZATION_GICS : ""
    ORGANIZATION ||--o{ ASSOCIATE_LABOR_TASK : ""
    ORGANIZATION ||--o{ REPORTING_ORGANIZATION : ""
    ORGANIZATION ||--o{ PERSONA : ""
    ORGANIZATION ||--o{ AGREEMENT_IDENTIFICATION : ""
    ORGANIZATION ||--o{ DEMOGRAPHIC : ""
    ORGANIZATION ||--o{ ORGANIZATION_LEVEL : ""
    ORGANIZATION ||--o{ ORGANIZATION_BASEL_APPROACH : ""
    ORGANIZATION_BUSINESS_TYPE ||--o{ ORGANIZATION_BUSINESS_TYPE_XREF : ""
    ORGANIZATION_BUSINESS_TYPE ||--o{ ORGANIZATION_BUSINESS_TYPE : ""
    ORGANIZATION_BUSINESS_TYPE ||--o{ BUSINESS_TYPE_RISK_FACTOR : ""
    ORGANIZATION_BUSINESS_TYPE ||--o{ PURCHASE_CARD_BUSINESS : ""
    ORGANIZATION_BUSINESS_TYPE ||--o{ PURCHASE_AGREEMENT_BUSINESS_TYPE : ""
    ORGANIZATION_CENTER_TYPE ||--o{ FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION : ""
    ORGANIZATION_CLASSIFICATION_SCHEME ||--o{ ORGANIZATION_CLASSIFICATION_GEOGRAPHIC_AREA : ""
    ORGANIZATION_CLASSIFICATION_SCHEME ||--o{ ORGANIZATION_BUSINESS_TYPE : ""
    ORGANIZATION_HIERARCHY_LEVEL ||--o{ ORGANIZATION_HIERARCHY : ""
    ORGANIZATION_HIERARCHY_TYPE ||--o{ ORGANIZATION_HIERARCHY : ""
    ORGANIZATION_LEVEL_TYPE ||--o{ ORGANIZATION_LEVEL : ""
    ORGANIZATION_NAICS__GEO ||--o{ ORGANIZATION_NAICS_RATIO : ""
    ORGANIZATION_POSITION ||--o{ ORGANIZATION_POSITION_TRAIT_XREF : ""
    ORGANIZATION_POSITION ||--o{ ORGANIZATION_POSITION_STATUS : ""
    ORGANIZATION_POSITION ||--o{ ORGANIZATION_PAY_ELEMENT : ""
    ORGANIZATION_POSITION ||--o{ ASSOCIATE_ORGANIZATION_POSITION : ""
    ORGANIZATION_SIC__GEO ||--o{ ORGANIZATION_SIC_RATIO : ""
    ORGANIZATION_SIZE_TYPE ||--o{ ORGANIZATION : ""
    ORGANIZATION_TYPE ||--o{ ORGANIZATION : ""
    OTHER_PARTY_INSURER ||--o{ OTHER_PARTY_INSURANCE_COVERAGE : ""
    PARTY ||--o{ UNKNOWN_PARTY_SESSION_PRIVACY_PREFERENCE : ""
    PARTY ||--o{ PROJECT_PARTY : ""
    PARTY ||--o{ UNKNOWN_PARTY_THIRD_PARTY_CONSENT : ""
    PARTY ||--o{ PARTY_ACCOUNT : ""
    PARTY ||--o{ PARTY_DRIVING_HISTORY : ""
    PARTY ||--o{ PARTY_GOAL : ""
    PARTY ||--o{ INVOICE_PARTY : ""
    PARTY ||--o{ PARTY_HOLIDAY_CALENDAR : ""
    PARTY ||--o{ PROJECT_TASK_RESOURCE_PARTY : ""
    PARTY ||--o{ INVOICE_LINE_PARTY : ""
    PARTY ||--o{ VENDOR_PO_PARTY : ""
    PARTY ||--o{ PARTY_CURRENCY : ""
    PARTY ||--o{ PARTY_SPECIALTY : ""
    PARTY ||--o{ MICROSITE_PARTY_XREF : ""
    PARTY ||--o{ PARTY_LIFECYCLE : ""
    PARTY ||--o{ PARTY_SANCTION : ""
    PARTY ||--o{ INTEREST_RATE_INDEX_PARTY : ""
    PARTY ||--o{ PARTY_INVESTMENT_OBJECTIVE : ""
    PARTY ||--o{ PARTY_OBJECTIVE : ""
    PARTY ||--o{ PARTY_AUTHORIZATION_RESPONSE : ""
    PARTY ||--o{ PARTY_METRIC_PROJECTION : ""
    PARTY ||--o{ PARTY_TO_AGREEMENT_RISK_GRADE : ""
    PARTY ||--o{ PARTY_CHANNEL_INSTANCE_PREFERENCE : ""
    PARTY ||--o{ LINE_OF_BUSINESS_PARTY_METRIC : ""
    PARTY ||--o{ SALES_MARKETING_ACTIVITY_PARTY : ""
    PARTY ||--o{ PARTY_CHANNEL_TYPE : ""
    PARTY ||--o{ ASSOCIATE_BENEFICIARY : ""
    PARTY ||--o{ NAME_SALUTATION : ""
    PARTY ||--o{ PARTY_TRAIT_VALUE_XREF : ""
    PARTY ||--o{ NAME_VALEDICTION : ""
    PARTY ||--o{ LEAD_PARTY_ROLE : ""
    PARTY ||--o{ PARTY_SUBJECT : ""
    PARTY ||--o{ PARTY_GRIEVANCE : ""
    PARTY ||--o{ CUSTOM_CALENDAR_PARTY : ""
    PARTY ||--o{ PARTY_TACTIC : ""
    PARTY ||--o{ MODEL_RUN_PARTY : ""
    PARTY ||--o{ AD_ORDER_PARTY : ""
    PARTY ||--o{ PARTY_LEGAL_ACTION : ""
    PARTY ||--o{ CASE_PARTY : ""
    PARTY ||--o{ ANALYTICAL_MODEL_PARTY : ""
    PARTY ||--o{ PROMOTION_CELL_PARTY : ""
    PARTY ||--o{ OPPORTUNITY_PARTY : ""
    PARTY ||--o{ PARTY_STRATEGY : ""
    PARTY ||--o{ PARTY_TO_PARTY_RISK_GRADE : ""
    PARTY ||--o{ CONTACT_LIST_MANAGEMENT : ""
    PARTY ||--o{ POLICY_INSURABLE_COVERAGE_PARTY : ""
    PARTY ||--o{ SERVICE_REQUEST_PARTY : ""
    PARTY ||--o{ TRADE_EVENT_SETTLE_PARTY : ""
    PARTY ||--o{ ALERT_SETUP_NOTIFICATION_PARTY : ""
    PARTY ||--o{ APPLICATION_PARTY_PRODUCT : ""
    PARTY ||--o{ SERVICE_REQUEST_ACTIVITY_PARTY : ""
    PARTY ||--o{ ASSOCIATE_PERFORMANCE_EVALUATION : ""
    PARTY ||--o{ BUSINESS_INTEREST_SUMMARY : ""
    PARTY ||--o{ PROPOSAL_PARTY : ""
    PARTY ||--o{ PARTY_CHANNEL_TYPE_ACTIVITY_QUOTA : ""
    PARTY ||--o{ SITE_PARTY : ""
    PARTY ||--o{ ASSOCIATE_CONTACT : ""
    PARTY ||--o{ SITE_IDENTIFICATION : ""
    PARTY ||--o{ STATION_IDENTIFICATION : ""
    PARTY ||--o{ PARTY_LANGUAGE_PROFICIENCY : ""
    PARTY ||--o{ AGREEMENT_PARTY_TEXT : ""
    PARTY ||--o{ PARTY_INSURABLE_INTEREST : ""
    PARTY ||--o{ CAMPAIGN_CELL_PARTY : ""
    PARTY ||--o{ THIRD_PARTY_CONSENT : ""
    PARTY ||--o{ PARTY_CHANNEL_INSTANCE : ""
    PARTY ||--o{ PARTY_ASSET_REGISTRATION : ""
    PARTY ||--o{ PARTY_ASSET_PART_VALUATION : ""
    PARTY ||--o{ PARTY_LANGUAGE_USAGE : ""
    PARTY ||--o{ PARTY_ASSET_CONDITION : ""
    PARTY ||--o{ WORK_PROCESS_STEP_PARTY : ""
    PARTY ||--o{ ASSET_INSPECTION_PARTY : ""
    PARTY ||--o{ PARTY_IDENTIFICATION_VALIDATION : ""
    PARTY ||--o{ PARTY_INVESTMENT_RISK_TOLERANCE : ""
    PARTY ||--o{ PARTY_BANKRUPTCY : ""
    PARTY ||--o{ PRODUCT_FEATURE_PARTY : ""
    PARTY ||--o{ PARTY_FEATURE : ""
    PARTY ||--o{ PARTY_ACCESS_DEVICE : ""
    PARTY ||--o{ PARTY_CLAIM : ""
    PARTY ||--o{ PARTY_INSURANCE_RISK_FACTOR : ""
    PARTY ||--o{ PARTY_CLAIM_SERVICE : ""
    PARTY ||--o{ PARTY_INSURANCE_RISK_CATEGORY : ""
    PARTY ||--o{ PARTY_PRODUCT_QUOTA : ""
    PARTY ||--o{ PARTY_SCORE : ""
    PARTY ||--o{ PARTY_SEGMENT : ""
    PARTY ||--o{ PARTY_AGREEMENT_BALANCE_SUMMARY : ""
    PARTY ||--o{ PARTY_PARTY_CLASS_XREF : ""
    PARTY ||--o{ PARTY_RISK_GRADE : ""
    PARTY ||--o{ PARTY_RISK_GRADE_RELATED : ""
    PARTY ||--o{ PARTY_TO_PARTY_GROUP : ""
    PARTY ||--o{ PARTY_APPLICATION : ""
    PARTY ||--o{ PARTY_TO_PARTY_ASSET : ""
    PARTY ||--o{ PARTY_LIMIT : ""
    PARTY ||--o{ PARTY_TO_EXTERNAL_LIST : ""
    PARTY ||--o{ PARTY_SOLICITATION_PREFERENCE : ""
    PARTY ||--o{ PARTY_SCRIPT : ""
    PARTY ||--o{ PARTY_SYSTEM_ABUSE : ""
    PARTY ||--o{ PARTY_CHANNEL_PREFERENCE_SCORE : ""
    PARTY ||--o{ PARTY_PRODUCT_SCORE : ""
    PARTY ||--o{ PARTY_COST : ""
    PARTY ||--o{ PARTY_PROFIT : ""
    PARTY ||--o{ PARTY_QUOTATION : ""
    PARTY ||--o{ PARTY_CLAIM_AUTHORIZATION : ""
    PARTY ||--o{ PARTY_SURVEY_RESPONSE : ""
    PARTY ||--o{ PRODUCT_PARTY : ""
    PARTY ||--o{ PRODUCT_PACKAGE_PARTY : ""
    PARTY ||--o{ PARTY_PRODUCT_GROUP_QUOTA : ""
    PARTY ||--o{ PARTY_QUOTA : ""
    PARTY ||--o{ CAMPAIGN_PARTY : ""
    PARTY ||--o{ PROMOTION_PARTY : ""
    PARTY ||--o{ PARTY_DOCUMENT : ""
    PARTY ||--o{ PARTY_AGREEMENT_GROUP : ""
    PARTY ||--o{ EVENT_PARTY : ""
    PARTY ||--o{ PARTY_DEMOGRAPHIC : ""
    PARTY ||--o{ PARTY_LIABILITY : ""
    PARTY ||--o{ PRODUCT_GROUP_PARTY : ""
    PARTY ||--o{ PARTY_METRIC : ""
    PARTY ||--o{ LOYALTY_PROGRAM_PARTY : ""
    PARTY ||--o{ PARTY_AGREEMENT : ""
    PARTY ||--o{ PARTY_REVENUE : ""
    PARTY ||--o{ PARTY_STATUS : ""
    PARTY ||--o{ PARTY_CHANNEL_INSTANCE_XREF : ""
    PARTY ||--o{ PARTY_PORTFOLIO : ""
    PARTY_ACCESS_DEVICE_ROLE_TYPE ||--o{ PARTY_ACCESS_DEVICE : ""
    PARTY_ACCOUNT_ROLE ||--o{ PARTY_ACCOUNT : ""
    PARTY_ADDRESS_USAGE_TYPE ||--o{ PARTY_ADDRESS : ""
    PARTY_AGREEMENT ||--o{ AGREEMENT_PARTY_FEATURE : ""
    PARTY_AGREEMENT ||--o{ PARTY_AGREEMENT_ASSET : ""
    PARTY_AGREEMENT ||--o{ PARTY_AGREEMENT_METRIC : ""
    PARTY_AGREEMENT ||--o{ AGREEMENT_PARTY_TEXT : ""
    PARTY_AGREEMENT ||--o{ PARTY_AGREEMENT_LOCATOR : ""
    PARTY_AGREEMENT_ASSET ||--o{ PARTY_AGREEMENT_ASSET_FEATURE : ""
    PARTY_AGREEMENT_GROUP_ROLE_TYPE ||--o{ PARTY_AGREEMENT_GROUP : ""
    PARTY_AGREEMENT_ROLE ||--o{ PARTY_AGREEMENT : ""
    PARTY_APPLICATION ||--o{ PARTY_APPLICATION_DEMOGRAPHIC : ""
    PARTY_APPLICATION_ROLE ||--o{ PARTY_APPLICATION : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_LOCATOR : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_REVENUE : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_PART_TYPE_XREF : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_EVENT : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_LEGAL_ACTION : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_DAMAGE_ASSESSMENT : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_STATUS : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_COST_RECOVERY : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_SPECIFICATION : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_CONDITION : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_MAINTENANCE : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_COST : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_SALVAGE_STATUS : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_RECALL : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_REGISTRATION : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_GROUP_XREF : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_CLASS_XREF : ""
    PARTY_ASSET ||--o{ PARTY_TO_PARTY_ASSET : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_LIABILITY : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_DOCUMENT : ""
    PARTY_ASSET ||--o{ PARTY_ASSET_INTERNAL_IDENTIFIER : ""
    PARTY_ASSET_CLASS_SCHEME_TYPE ||--o{ PARTY_ASSET_CLASS_XREF : ""
    PARTY_ASSET_CLASS_SCHEME_TYPE ||--o{ PARTY_ASSET_CLASS_SCHEME_TYPE : ""
    PARTY_ASSET_CLASS_SCHEME_TYPE ||--o{ PARTY_ASSET_CLASS_VALUE : ""
    PARTY_ASSET_CLASS_VALUE ||--o{ PARTY_ASSET_CLASS_RISK_GRADE : ""
    PARTY_ASSET_CLASS_VALUE ||--o{ PARTY_ASSET_SALVAGE_SUMMARY : ""
    PARTY_ASSET_CLASS_VALUE ||--o{ PARTY_ASSET_CLASS_XREF : ""
    PARTY_ASSET_CLASS_VALUE ||--o{ PARTY_ASSET_PRICE_SENSITIVITY : ""
    PARTY_ASSET_CLASS_VALUE ||--o{ PARTY_ASSET_CLASS_VALUE : ""
    PARTY_ASSET_CONDITION_TYPE ||--o{ PARTY_ASSET_CONDITION : ""
    PARTY_ASSET_DAMAGE_TYPE ||--o{ PARTY_ASSET_DAMAGE_ASSESSMENT : ""
    PARTY_ASSET_DAMAGE_TYPE ||--o{ PARTY_ASSET_SALVAGE_SUMMARY : ""
    PARTY_ASSET_EVENT_ROLE ||--o{ PARTY_ASSET_EVENT : ""
    PARTY_ASSET_GROUP ||--o{ PARTY_ASSET_GROUP_XREF : ""
    PARTY_ASSET_GROUP_PURPOSE_TYPE ||--o{ PARTY_ASSET_GROUP : ""
    PARTY_ASSET_INSPECTION_ROLE ||--o{ ASSET_INSPECTION_PARTY : ""
    PARTY_ASSET_INSURER ||--o{ PARTY_ASSET_INSURANCE_COVERAGE : ""
    PARTY_ASSET_INTERNAL_ID_TYPE ||--o{ PARTY_ASSET_INTERNAL_IDENTIFIER : ""
    PARTY_ASSET_LIABILITY_REASON ||--o{ PARTY_ASSET_LIABILITY : ""
    PARTY_ASSET_LOCATOR_ROLE ||--o{ PARTY_ASSET_LOCATOR : ""
    PARTY_ASSET_OWNER ||--o{ PARTY_ASSET_TITLE : ""
    PARTY_ASSET_PART_TYPE ||--o{ PARTY_ASSET_PART_TYPE_XREF : ""
    PARTY_ASSET_PART_TYPE_XREF ||--o{ PARTY_ASSET_PART_RECALL : ""
    PARTY_ASSET_PART_TYPE_XREF ||--o{ PARTY_ASSET_PART_VALUATION : ""
    PARTY_ASSET_PHYSICAL_TYPE ||--o{ PARTY_ASSET : ""
    PARTY_ASSET_RECOVERY_AMOUNT_TYPE ||--o{ PARTY_ASSET_COST_RECOVERY : ""
    PARTY_ASSET_RELATED_TYPE ||--o{ PARTY_ASSET_RELATED : ""
    PARTY_ASSET_SALVAGE_STATUS_TYPE ||--o{ PARTY_ASSET_SALVAGE_STATUS : ""
    PARTY_ASSET_SENSITIVITY_TYPE ||--o{ PARTY_ASSET_PRICE_SENSITIVITY : ""
    PARTY_ASSET_SPECIFICATION_TYPE ||--o{ PARTY_ASSET_SPECIFICATION : ""
    PARTY_ASSET_STATUS_TYPE ||--o{ PARTY_ASSET_STATUS : ""
    PARTY_ASSET_SUBTYPE ||--o{ PARTY_ASSET : ""
    PARTY_ASSET_TITLE_TYPE ||--o{ PARTY_ASSET_TITLE : ""
    PARTY_AUTHORIZATION_QUESTION ||--o{ PARTY_AUTHORIZATION_RESPONSE : ""
    PARTY_BANK_IDENTIFICATION_NUMBER ||--o{ BANK_IDENTIFICATION_NUMBER : ""
    PARTY_CHANNEL_REASON_TYPE ||--o{ PARTY_CHANNEL_INSTANCE_XREF : ""
    PARTY_CHANNEL_ROLE ||--o{ PARTY_CHANNEL_TYPE : ""
    PARTY_CHANNEL_ROLE ||--o{ PARTY_CHANNEL_INSTANCE_XREF : ""
    PARTY_CLAIM ||--o{ PARTY_INSURABLE_INTEREST_EVENT : ""
    PARTY_CLAIM ||--o{ PARTY_CLAIM_EXPOSURE : ""
    PARTY_CLAIM ||--o{ PARTY_CLAIM_INSURABLE_INTEREST : ""
    PARTY_CLAIM ||--o{ PARTY_CLAIM_AMOUNT : ""
    PARTY_CLAIM_AUTHORIZATION_ROLE_TYPE ||--o{ PARTY_CLAIM_AUTHORIZATION : ""
    PARTY_CLAIM_ROLE_TYPE ||--o{ PARTY_CLAIM : ""
    PARTY_CLAIM_ROLE_TYPE ||--o{ PARTY_CLAIM_SERVICE : ""
    PARTY_CLAIM_SERVICE ||--o{ PARTY_CLAIM_SERVICE_DIAGNOSIS_AMOUNT : ""
    PARTY_CLAIM_SERVICE ||--o{ PARTY_CLAIM_SERVICE_AMOUNT : ""
    PARTY_CLASS_SCHEME_TYPE ||--o{ PARTY_PARTY_CLASS_XREF : ""
    PARTY_CLASS_SCHEME_TYPE ||--o{ PARTY_CLASS_VALUE : ""
    PARTY_CLASS_SCHEME_TYPE ||--o{ PARTY_CLASS_SCHEME_TYPE : ""
    PARTY_CLASS_VALUE ||--o{ PARTY_CLASSIFICATION_SUBJECT : ""
    PARTY_CLASS_VALUE ||--o{ PARTY_PARTY_CLASS_XREF : ""
    PARTY_CLASS_VALUE ||--o{ PARTY_CLASS_RISK_GRADE : ""
    PARTY_CLASS_VALUE ||--o{ PARTY_CLASS_VALUE : ""
    PARTY_CREDIT_REPORT ||--o{ PARTY_CREDIT_REPORT_SCORE : ""
    PARTY_CREDIT_REPORT ||--o{ PARTY_PUBLIC_RECORD : ""
    PARTY_CREDIT_REPORT ||--o{ PARTY_CREDIT_REPORT_COMMENT : ""
    PARTY_CREDIT_REPORT ||--o{ PARTY_LIABILITY_CREDIT_RATING : ""
    PARTY_CURRENCY_ROLE_TYPE ||--o{ PARTY_CURRENCY : ""
    PARTY_DOCUMENT ||--o{ PARTY_DOCUMENT_LOCATOR : ""
    PARTY_DOCUMENT_ROLE_TYPE ||--o{ PARTY_DOCUMENT : ""
    PARTY_DRIVING_LICENSE ||--o{ PARTY_DRIVING_LICENSE_ISSUANCE : ""
    PARTY_FEATURE_ROLE_TYPE ||--o{ PARTY_FEATURE : ""
    PARTY_FINANCIAL_DOCUMENT ||--o{ PARTY_FINANCIAL_DOCUMENT_ITEM : ""
    PARTY_GRIEVANCE_ROLE ||--o{ PARTY_GRIEVANCE : ""
    PARTY_GROUP ||--o{ PRODUCT_PARTY_GROUP : ""
    PARTY_GROUP ||--o{ PARTY_GROUP_LIMIT : ""
    PARTY_GROUP ||--o{ PARTY_GROUP_SUBJECT : ""
    PARTY_GROUP ||--o{ PARTY_GROUP_DEMOGRAPHIC : ""
    PARTY_GROUP ||--o{ PARTY_GROUP_METRIC : ""
    PARTY_GROUP ||--o{ PARTY_GROUP_RISK_GRADE : ""
    PARTY_GROUP ||--o{ PARTY_GROUP_SCORE : ""
    PARTY_GROUP ||--o{ PARTY_TO_PARTY_GROUP : ""
    PARTY_GROUP ||--o{ PARTY_GROUP_SELECT_CRITERION : ""
    PARTY_GROUP_REASON_TYPE ||--o{ PARTY_GROUP : ""
    PARTY_GROUP_RELATED_REASON ||--o{ PARTY_GROUP_RELATED : ""
    PARTY_IDENTIFICATION ||--o{ PARTY_IDENTIFICATION_EVENT : ""
    PARTY_IDENTIFICATION ||--o{ PARTY_IDENTIFICATION_VALIDATION : ""
    PARTY_IDENTIFICATION ||--o{ PARTY_IDENTIFICATION_LOCATOR : ""
    PARTY_IDENTIFICATION_CATEGORY ||--o{ PARTY_IDENTIFICATION_TYPE : ""
    PARTY_IDENTIFICATION_LOCATOR_USAGE_TYPE ||--o{ PARTY_IDENTIFICATION_LOCATOR : ""
    PARTY_IDENTIFICATION_ROLE ||--o{ PARTY_CLAIM_AUTHORIZATION_IDENTIFICATION : ""
    PARTY_IDENTIFICATION_STATUS_TYPE ||--o{ PARTY_IDENTIFICATION_STATUS : ""
    PARTY_IDENTIFICATION_TYPE ||--o{ IDENTIFICATION_TYPE_USAGE_TYPE : ""
    PARTY_IDENTIFICATION_TYPE ||--o{ PARTY_IDENTIFICATION_STATUS : ""
    PARTY_IDENTIFICATION_TYPE ||--o{ PARTY_CLAIM_AUTHORIZATION_IDENTIFICATION : ""
    PARTY_IDENTIFICATION_TYPE ||--o{ PARTY_IDENTIFICATION : ""
    PARTY_IDENTIFICATION_TYPE ||--o{ EVENT_PARTY : ""
    PARTY_IDENTIFICATION_TYPE_RELATED_REASON ||--o{ PARTY_IDENTIFICATION_TYPE_RELATED : ""
    PARTY_IDENTIFICATION_VALIDATION ||--o{ PARTY_IDENTIFICATION_DOCUMENT : ""
    PARTY_INFORMATION_VALIDATION ||--o{ PARTY_INFORMATION_DOCUMENT : ""
    PARTY_LOCATOR ||--o{ PARTY_DOCUMENT_LOCATOR : ""
    PARTY_METRIC_TYPE ||--o{ PARTY_RELATED_METRIC : ""
    PARTY_METRIC_TYPE ||--o{ PARTY_GROUP_METRIC : ""
    PARTY_METRIC_TYPE ||--o{ PARTY_METRIC_PROJECTION : ""
    PARTY_METRIC_TYPE ||--o{ PARTY_METRIC : ""
    PARTY_OPPORTUNITY_ROLE_TYPE ||--o{ OPPORTUNITY_PARTY : ""
    PARTY_PLAN_ROLE ||--o{ PARTY_STRATEGY : ""
    PARTY_PLAN_ROLE ||--o{ PARTY_GOAL : ""
    PARTY_PLAN_ROLE ||--o{ PARTY_TACTIC : ""
    PARTY_PLAN_ROLE ||--o{ PARTY_OBJECTIVE : ""
    PARTY_PORTFOLIO_ROLE_TYPE ||--o{ PARTY_PORTFOLIO : ""
    PARTY_PRIVACY_PREFERENCE ||--o{ THIRD_PARTY_CONSENT : ""
    PARTY_PROJECT_ROLE ||--o{ PROJECT_PARTY : ""
    PARTY_PROJECT_TASK_ROLE ||--o{ PROJECT_TASK_RESOURCE_PARTY : ""
    PARTY_QUOTATION_ROLE ||--o{ PARTY_QUOTATION : ""
    PARTY_RELATED ||--o{ PARTY_RELATED_METRIC : ""
    PARTY_RELATED ||--o{ PARTY_RELATIONSHIP_COST : ""
    PARTY_RELATED ||--o{ PARTY_RELATED_FUNCTION : ""
    PARTY_RELATED_FUNCTION ||--o{ PARTY_RELATED_FUNCTION_GEOGRAPHIC_AREA : ""
    PARTY_RELATED_ROLE ||--o{ PARTY_RELATED : ""
    PARTY_RELATED_ROLE ||--o{ PERSONA : ""
    PARTY_RELATED_ROLE ||--o{ UNKNOWN_PARTY : ""
    PARTY_RELATED_STATUS_REASON ||--o{ PARTY_RELATED : ""
    PARTY_RELATED_STATUS_TYPE ||--o{ PARTY_RELATED : ""
    PARTY_RELATED_SUBTYPE ||--o{ PARTY_RELATED : ""
    PARTY_RISK_GRADE ||--o{ PARTY_TO_PARTY_RISK_GRADE : ""
    PARTY_RISK_GRADE_ROLE ||--o{ PARTY_TO_PARTY_RISK_GRADE : ""
    PARTY_RISK_GRADE_ROLE ||--o{ PARTY_TO_AGREEMENT_RISK_GRADE : ""
    PARTY_ROLE_RELATIONSHIP_TYPE ||--o{ PARTY_ROLE_TO_PARTY_ROLE : ""
    PARTY_SALES_ACTIVITY_ROLE ||--o{ SALES_MARKETING_ACTIVITY_PARTY : ""
    PARTY_STATUS_REASON_TYPE ||--o{ PARTY_STATUS : ""
    PARTY_STATUS_SCHEME_TYPE ||--o{ PARTY_STATUS_TYPE : ""
    PARTY_STATUS_SCHEME_TYPE ||--o{ PARTY_STATUS : ""
    PARTY_STATUS_TYPE ||--o{ PARTY_STATUS : ""
    PARTY_STRUCTURE_TYPE ||--o{ PARTY_RELATED : ""
    PARTY_STRUCTURE_TYPE ||--o{ ORGANIZATION_LEVEL : ""
    PARTY_TEXT ||--o{ PARTY_TEXT_SECTION : ""
    PARTY_TO_PARTY_ASSET ||--o{ PARTY_AUTOMOBILE_DRIVING_BEHAVIOR : ""
    PARTY_TO_PARTY_GROUP_REASON ||--o{ PARTY_TO_PARTY_GROUP : ""
    PARTY_TRAIT ||--o{ PARTY_TRAIT_VALUE : ""
    PARTY_TRAIT_VALUE ||--o{ PARTY_TRAIT_VALUE_XREF : ""
    PARTY_TRANSACTION_ROLE ||--o{ VENDOR_PO_PARTY : ""
    PARTY_TYPE ||--o{ PARTY : ""
    PAYMENT_INSTRUCTION_IDENTIFICATION_TYPE ||--o{ PAYMENT_INSTRUCTION_IDENTIFICATION : ""
    PAYMENT_INSTRUCTION_LOCATOR_REASON_TYPE ||--o{ PAYMENT_INSTRUCTION_LOCATOR : ""
    POLICY_INSURABLE_COVERAGE_PARTY ||--o{ POLICY_INSURABLE_COVERAGE_PARTY_METRIC : ""
    PRODUCT_FEATURE_LOCATOR_TYPE ||--o{ PRODUCT_FEATURE_LOCATOR : ""
    PRODUCT_FEATURE_LOCATOR_TYPE ||--o{ PRODUCT_LOCATOR : ""
    PRODUCT_FEATURE_LOCATOR_TYPE ||--o{ FEATURE_LOCATOR : ""
    PRODUCT_FEATURE_PARTY_ROLE_TYPE ||--o{ PRODUCT_FEATURE_PARTY : ""
    PRODUCT_IDENTIFICATION ||--o{ EVENT_PRODUCT_IDENTIFICATION : ""
    PRODUCT_IDENTIFICATION_SUBTYPE ||--o{ PRODUCT_IDENTIFICATION : ""
    PRODUCT_IDENTIFICATION_TYPE ||--o{ PRODUCT_IDENTIFICATION : ""
    PRODUCT_NAME_TYPE ||--o{ PRODUCT_NAME : ""
    PRODUCT_PARTY ||--o{ PRODUCT_PARTY_STATUS : ""
    PRODUCT_PARTY ||--o{ PRODUCT_PARTY_NAME : ""
    PRODUCT_PARTY ||--o{ PARTY_PRODUCT_FUNCTION : ""
    PRODUCT_PARTY_GROUP ||--o{ PRODUCT_PARTY_GROUP_ELIGIBILITY : ""
    PRODUCT_PARTY_ROLE_TYPE ||--o{ PRODUCT_PARTY : ""
    PRODUCT_PARTY_ROLE_TYPE ||--o{ PRODUCT_PACKAGE_PARTY : ""
    PRODUCT_PARTY_ROLE_TYPE ||--o{ PRODUCT_GROUP_PARTY : ""
    PRODUCT_PARTY_STATUS_TYPE ||--o{ PRODUCT_PARTY_STATUS : ""
    PROJECT_LOCATOR_ROLE ||--o{ PROJECT_LOCATOR : ""
    PROJECT_TASK_RESOURCE_INDIVIDUAL ||--o{ PROJECT_TASK_RESOURCE_PARTY : ""
    PROMOTION_CELL_PARTY ||--o{ PROMOTION_PARTY_STEP : ""
    PROMOTION_PARTY_ROLE ||--o{ PROMOTION_PARTY : ""
    PROMOTION_PARTY_STEP ||--o{ PROMOTION_PARTY_STEP_RESPONSE : ""
    PROMOTION_PARTY_STEP ||--o{ PROMOTION_PARTY_STEP_STATUS : ""
    PROPOSAL_PARTY_ROLE_TYPE ||--o{ PROPOSAL_PARTY : ""
    PURCHASE_CARD_BUSINESS ||--o{ PURCHASE_CARD_BUSINESS_LIMIT : ""
    QUERY_STRING_FIELD_NAME ||--o{ NAME_VALUE_PAIR_EVENT_XREF : ""
    QUERY_STRING_FIELD_NAME ||--o{ QUERY_STRING_NAME_VALUE : ""
    SERVICE_REQUEST_PARTY_ROLE ||--o{ SERVICE_REQUEST_ACTIVITY_PARTY : ""
    SERVICE_REQUEST_PARTY_ROLE ||--o{ SERVICE_REQUEST_PARTY : ""
    SETTLEMENT_LOCATOR_ROLE_TYPE ||--o{ TRADE_SETTLEMENT_INSTRUCTION_LOCATOR : ""
    SETTLEMENT_PARTY_ROLE_TYPE ||--o{ TRADE_EVENT_SETTLE_PARTY : ""
    SITE_IDENTIFICATION_TYPE ||--o{ SITE_IDENTIFICATION : ""
    SITE_PARTY_ROLE ||--o{ SITE_PARTY : ""
    TELEPHONE_NUMBER ||--o{ TELEPHONE_NUMBER_CHANNEL_INSTANCE : ""
    TELEPHONE_NUMBER ||--o{ MOBILE_TELEPHONE_NUMBER : ""
    THIRD_PARTY_FINANCIAL_STATEMENT ||--o{ PARTY_FINANCIAL_DOCUMENT : ""
    THIRD_PARTY_GUARANTEE_TYPE ||--o{ THIRD_PARTY_GUARANTEE_AGREEMENT : ""
    UNKNOWN_PARTY ||--o{ UNKNOWN_PARTY_EVENT : ""
    UNKNOWN_PARTY_EVENT ||--o{ UNKNOWN_PARTY_SESSION_PRIVACY_PREFERENCE : ""
    UNKNOWN_PARTY_ID_TYPE ||--o{ UNKNOWN_PARTY : ""
    UNKNOWN_PARTY_SESSION_PRIVACY_PREFERENCE ||--o{ UNKNOWN_PARTY_THIRD_PARTY_CONSENT : ""
    VERY_IMPORTANT_PERSON_TYPE ||--o{ INDIVIDUAL_VIP_STATUS : ""
    WORK_PROCESS_STEP_PARTY_ROLE ||--o{ WORK_PROCESS_STEP_PARTY : ""
    ORGANIZATION ||--|| BUSINESS : "inherits"
    PARTY ||--|| INDIVIDUAL : "inherits"
    ORGANIZATION ||--|| INTERNAL_ORGANIZATION : "inherits"
    PARTY ||--|| ORGANIZATION : "inherits"
    PARTY_AGREEMENT ||--|| AGREEMENT_INSURED_PARTY : "inherits"
    INDIVIDUAL ||--|| ASSOCIATE : "inherits"
    ASSOCIATE_PAYROLL_TRANSACTION ||--|| ASSOCIATE_DEDUCTION : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| BANK_BUSINESS_TYPE : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| BROKER_BUSINESS_TYPE : "inherits"
    PARTY_RELATED ||--|| BUSINESS_OWNERSHIP : "inherits"
    DIRECT_CONTACT_EVENT ||--|| CALL_CENTER_CONTACT_EVENT : "inherits"
    PARTY_CLAIM ||--|| CLAIM_SUBMITTING_PARTY : "inherits"
    PARTY_CLAIM ||--|| CLAIM_SUBSCRIBING_PARTY : "inherits"
    PARTY_CLAIM ||--|| CLAIM_THIRD_PARTY : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| CUSTODIAN_BUSINESS_TYPE : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| DEALER_BUSINESS_TYPE : "inherits"
    CONTACT_EVENT ||--|| DIRECT_CONTACT_EVENT : "inherits"
    INTERNAL_ORGANIZATION ||--|| FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION : "inherits"
    PARTY_IDENTIFICATION ||--|| GLOBAL_INTERMEDIARY_IDENTIFICATION_NUMBER : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| HEALTH_PROVIDER_BUSINESS_TYPE : "inherits"
    PARTY ||--|| HOUSEHOLD : "inherits"
    FINANCIAL_INSTITUTION_INTERNAL_ORGANIZATION ||--|| HR_INTERNAL_ORGANIZATION : "inherits"
    CALL_CENTER_CONTACT_EVENT ||--|| INBOUND_EMAIL : "inherits"
    PARTY_APPLICATION ||--|| INSURED_PARTY_APPLICATION : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| INTERDEALER_BROKER_BUSINESS_TYPE : "inherits"
    PARTY_IDENTIFICATION ||--|| INTERNAL_PARTY_IDENTIFICATION : "inherits"
    LEAD_PARTY_ROLE ||--|| LEAD_CONTACT : "inherits"
    PARTY_LIABILITY ||--|| LENDER_PARTY_LIABILITY : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| MARKET_DATA_PROVIDER_BUSINESS_TYPE : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| MARKET_MAKER_BUSINESS_TYPE : "inherits"
    INTERNAL_ORGANIZATION ||--|| OTHER_INSTITUTION_INTERNAL_ORGANIZATION : "inherits"
    INTERNAL_ORGANIZATION ||--|| OTHER_INTERNAL_ORGANIZATION : "inherits"
    PARTY_RELATED ||--|| OTHER_PARTY_INSURER : "inherits"
    PARTY_TO_PARTY_ASSET ||--|| PARTY_ASSET_INSURER : "inherits"
    PARTY_ASSET_TITLE ||--|| PARTY_ASSET_JUNK_TITLE : "inherits"
    PARTY_TO_PARTY_ASSET ||--|| PARTY_ASSET_LESSEE : "inherits"
    PARTY_TO_PARTY_ASSET ||--|| PARTY_ASSET_OWNER : "inherits"
    PARTY_ASSET_TITLE ||--|| PARTY_ASSET_SALVAGE_TITLE : "inherits"
    PARTY_IDENTIFICATION ||--|| PARTY_BANK_IDENTIFICATION_NUMBER : "inherits"
    PARTY_IDENTIFICATION ||--|| PARTY_DRIVING_LICENSE : "inherits"
    PARTY_IDENTIFICATION ||--|| PARTY_MARKET_IDENTIFIER_CODE : "inherits"
    PARTY_IDENTIFICATION ||--|| PARTY_ROUTING_TRANSIT_NUMBER : "inherits"
    BUSINESS ||--|| PENSION_PLAN_ORGANIZATION : "inherits"
    PARTY_IDENTIFICATION ||--|| PERSONAL_IDENTIFICATION : "inherits"
    PARTY_IDENTIFICATION ||--|| PROFESSIONAL_IDENTIFICATION : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| PROVIDER_BUSINESS_TYPE : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| RATING_AGENCY_BUSINESS_TYPE : "inherits"
    DIRECT_CONTACT_EVENT ||--|| RECOVERY_COLLECTION_CONTACT_EVENT : "inherits"
    ORGANIZATION_BUSINESS_TYPE ||--|| REGISTRAR_BUSINESS_TYPE : "inherits"
    CONTACT_EVENT ||--|| SELF_SERVICE_CONTACT_EVENT : "inherits"
    PRODUCT_IDENTIFICATION ||--|| TICKER_NAME : "inherits"
    PARTY_APPLICATION ||--|| UNDERWRITER_PARTY_APPLICATION : "inherits"