#!/usr/bin/env python3
"""Generate relationships.json for TAIW — ~300 class relationships"""
import json, os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'src', 'data', 'taiw')

# Core structural relationships
RELS = [
    # Declaration domain relationships
    ("Declaration", "DeclarationGovernment", "composition", "1:N", "Declaration", "Declaration"),
    ("Declaration", "DeclarationGoodShipment", "composition", "1:N", "Declaration", "Declaration"),
    ("Declaration", "Amendment", "composition", "0:N", "Declaration", "Declaration"),
    ("Declaration", "Cancellation", "composition", "0:1", "Declaration", "Declaration"),
    ("Declaration", "CustomsDeclarationDocument", "composition", "1:1", "Declaration", "Declaration"),
    # Declaration to other domains
    ("Declaration", "Consignment", "association", "1:N", "Declaration", "Consignment"),
    ("Declaration", "Party", "association", "1:N", "Declaration", "Party"),
    ("Declaration", "Agent", "association", "0:1", "Declaration", "Party"),
    ("Declaration", "Declarant", "association", "1:1", "Declaration", "Party"),
    ("Declaration", "Importer", "association", "0:1", "Declaration", "Party"),
    ("Declaration", "Exporter", "association", "0:1", "Declaration", "Party"),
    ("Declaration", "CustomsBroker", "association", "0:1", "Declaration", "Party"),
    ("Declaration", "TransportMeans", "association", "1:N", "Declaration", "Transport"),
    ("Declaration", "BorderTransportMeans", "association", "1:1", "Declaration", "Transport"),
    ("Declaration", "AdditionalDocument", "association", "0:N", "Declaration", "Document"),
    ("Declaration", "ObligationGuarantee", "association", "0:N", "Declaration", "Financial"),
    ("Declaration", "DutyTaxFee", "association", "1:N", "Declaration", "Financial"),
    ("Declaration", "Payment", "association", "0:N", "Declaration", "Financial"),
    ("Declaration", "Response", "association", "1:N", "Declaration", "Response"),
    ("Declaration", "RiskAssessment", "association", "0:1", "Declaration", "Risk & Control"),
    ("Declaration", "Selectivity", "association", "0:1", "Declaration", "Risk & Control"),
    ("Declaration", "Location", "association", "1:N", "Declaration", "Location"),
    ("Declaration", "CustomsOffice", "association", "1:1", "Declaration", "Location"),

    # Consignment domain
    ("Consignment", "ConsignmentItem", "composition", "1:N", "Consignment", "Consignment"),
    ("Consignment", "TransportContractDocument", "association", "1:1", "Consignment", "Consignment"),
    ("Consignment", "AssociatedTransportDocument", "association", "0:N", "Consignment", "Consignment"),
    ("ConsolidatedConsignment", "Consignment", "composition", "1:N", "Consignment", "Consignment"),
    ("Consignment", "TransportMeans", "association", "1:N", "Consignment", "Transport"),
    ("Consignment", "TransportEquipment", "association", "0:N", "Consignment", "Transport"),
    ("Consignment", "Carrier", "association", "1:1", "Consignment", "Party"),
    ("Consignment", "Consignor", "association", "1:1", "Consignment", "Party"),
    ("Consignment", "Consignee", "association", "1:1", "Consignment", "Party"),
    ("Consignment", "FreightForwarder", "association", "0:1", "Consignment", "Party"),
    ("Consignment", "NotifyParty", "association", "0:1", "Consignment", "Party"),
    ("Consignment", "LoadingLocation", "association", "1:1", "Consignment", "Location"),
    ("Consignment", "UnloadingLocation", "association", "1:1", "Consignment", "Location"),
    ("Consignment", "Itinerary", "association", "0:1", "Consignment", "Transport"),

    # Goods domain
    ("DeclarationGoodShipment", "GoodsItem", "composition", "1:N", "Declaration", "Goods"),
    ("ConsignmentItem", "GoodsItem", "association", "1:1", "Consignment", "Goods"),
    ("GoodsItem", "Commodity", "association", "1:1", "Goods", "Goods"),
    ("GoodsItem", "Classification", "composition", "1:N", "Goods", "Goods"),
    ("GoodsItem", "GoodsMeasure", "composition", "1:1", "Goods", "Goods"),
    ("GoodsItem", "Packaging", "composition", "1:N", "Goods", "Goods"),
    ("GoodsItem", "DangerousGoods", "composition", "0:1", "Goods", "Goods"),
    ("GoodsItem", "TariffQuantity", "composition", "0:N", "Goods", "Goods"),
    ("GoodsItem", "AdditionalInformation", "composition", "0:N", "Goods", "Goods"),
    ("GoodsItem", "PreviousDocument", "association", "0:N", "Goods", "Goods"),
    ("GoodsItem", "DutyTaxFee", "association", "1:N", "Goods", "Financial"),
    ("GoodsItem", "CustomsValuation", "association", "1:1", "Goods", "Financial"),
    ("GoodsItem", "CertificateOfOrigin", "association", "0:1", "Goods", "Origin"),
    ("GoodsItem", "AdditionalDocument", "association", "0:N", "Goods", "Document"),
    ("GoodsItem", "HarmonizedSystem", "association", "1:1", "Goods", "Classification"),
    ("GoodsItem", "NationalTariffLine", "association", "1:1", "Goods", "Classification"),
    ("GoodsItem", "PreferenceCode", "association", "0:1", "Goods", "Classification"),
    ("GoodsItem", "QuotaAllocation", "association", "0:1", "Goods", "Classification"),
    ("GoodsItem", "Restriction", "association", "0:N", "Goods", "Classification"),
    ("GoodsItem", "ExaminationNotice", "association", "0:1", "Goods", "Risk & Control"),
    ("GoodsItem", "ExaminationResult", "association", "0:1", "Goods", "Risk & Control"),
    ("GoodsItem", "Manufacturer", "association", "0:1", "Goods", "Party"),
    ("GoodsItem", "Seller", "association", "0:1", "Goods", "Party"),
    ("GoodsItem", "Buyer", "association", "0:1", "Goods", "Party"),

    # Transport domain
    ("TransportMeans", "BorderTransportMeans", "specialization", "0:1", "Transport", "Transport"),
    ("TransportMeans", "TransitTransportMeans", "specialization", "0:1", "Transport", "Transport"),
    ("TransportMeans", "ArrivalTransportMeans", "specialization", "0:1", "Transport", "Transport"),
    ("TransportMeans", "DepartureTransportMeans", "specialization", "0:1", "Transport", "Transport"),
    ("TransportMeans", "TransportEquipment", "association", "0:N", "Transport", "Transport"),
    ("TransportEquipment", "Seal", "composition", "0:N", "Transport", "Transport"),
    ("TransportMeans", "Itinerary", "association", "0:1", "Transport", "Transport"),
    ("TransportMeans", "TransportEvent", "composition", "0:N", "Transport", "Transport"),
    ("TransportMeans", "Carrier", "association", "1:1", "Transport", "Party"),
    ("TransportEquipment", "GoodsItem", "association", "0:N", "Transport", "Goods"),
    ("TransportEvent", "Location", "association", "1:1", "Transport", "Location"),
    ("TransportEvent", "EntryPort", "association", "0:1", "Transport", "Location"),
    ("TransportEvent", "ExitPort", "association", "0:1", "Transport", "Location"),

    # Party domain
    ("Party", "Agent", "specialization", "0:1", "Party", "Party"),
    ("Party", "Buyer", "specialization", "0:1", "Party", "Party"),
    ("Party", "Seller", "specialization", "0:1", "Party", "Party"),
    ("Party", "Consignor", "specialization", "0:1", "Party", "Party"),
    ("Party", "Consignee", "specialization", "0:1", "Party", "Party"),
    ("Party", "Declarant", "specialization", "0:1", "Party", "Party"),
    ("Party", "Carrier", "specialization", "0:1", "Party", "Party"),
    ("Party", "CustomsBroker", "specialization", "0:1", "Party", "Party"),
    ("Party", "Importer", "specialization", "0:1", "Party", "Party"),
    ("Party", "Exporter", "specialization", "0:1", "Party", "Party"),
    ("Party", "Manufacturer", "specialization", "0:1", "Party", "Party"),
    ("Party", "NotifyParty", "specialization", "0:1", "Party", "Party"),
    ("Party", "FreightForwarder", "specialization", "0:1", "Party", "Party"),
    ("Party", "WarehouseKeeper", "specialization", "0:1", "Party", "Party"),
    ("Party", "Address", "composition", "0:N", "Party", "Location"),
    ("Party", "Location", "association", "0:N", "Party", "Location"),

    # Location domain
    ("Location", "Address", "composition", "0:1", "Location", "Location"),
    ("Location", "LoadingLocation", "specialization", "0:1", "Location", "Location"),
    ("Location", "UnloadingLocation", "specialization", "0:1", "Location", "Location"),
    ("Location", "CustomsOffice", "specialization", "0:1", "Location", "Location"),
    ("Location", "EntryPort", "specialization", "0:1", "Location", "Location"),
    ("Location", "ExitPort", "specialization", "0:1", "Location", "Location"),
    ("Location", "DestinationCountry", "specialization", "0:1", "Location", "Location"),
    ("CustomsOffice", "Declaration", "association", "0:N", "Location", "Declaration"),

    # Financial domain
    ("CustomsValuation", "ExchangeRate", "association", "1:1", "Financial", "Financial"),
    ("CustomsValuation", "DutyTaxFee", "composition", "1:N", "Financial", "Financial"),
    ("DutyTaxFee", "Payment", "association", "0:1", "Financial", "Financial"),
    ("ObligationGuarantee", "BankAccount", "association", "0:1", "Financial", "Financial"),
    ("Payment", "AccountingEntry", "association", "1:1", "Financial", "Financial"),
    ("Payment", "BankAccount", "association", "0:1", "Financial", "Financial"),
    ("CustomsValuation", "TradeFinanceDocument", "association", "0:N", "Financial", "Financial"),
    ("ObligationGuarantee", "Party", "association", "1:1", "Financial", "Party"),
    ("Payment", "Party", "association", "1:1", "Financial", "Party"),

    # Document domain
    ("AdditionalDocument", "Certificate", "specialization", "0:1", "Document", "Document"),
    ("AdditionalDocument", "License", "specialization", "0:1", "Document", "Document"),
    ("AdditionalDocument", "Permit", "specialization", "0:1", "Document", "Document"),
    ("AdditionalDocument", "Invoice", "specialization", "0:1", "Document", "Document"),
    ("AdditionalDocument", "PackingList", "specialization", "0:1", "Document", "Document"),
    ("AdditionalDocument", "BillOfLading", "specialization", "0:1", "Document", "Document"),
    ("AdditionalDocument", "AirWaybill", "specialization", "0:1", "Document", "Document"),
    ("AdditionalDocument", "InsuranceDocument", "specialization", "0:1", "Document", "Document"),
    ("Certificate", "CertificateOfOrigin", "association", "0:1", "Document", "Origin"),
    ("Invoice", "CustomsValuation", "association", "1:1", "Document", "Financial"),
    ("BillOfLading", "TransportContractDocument", "association", "1:1", "Document", "Consignment"),
    ("AirWaybill", "TransportContractDocument", "association", "1:1", "Document", "Consignment"),
    ("Permit", "GovernmentProcedure", "association", "0:1", "Document", "Risk & Control"),

    # Classification domain
    ("HarmonizedSystem", "NationalTariffLine", "composition", "1:N", "Classification", "Classification"),
    ("NationalTariffLine", "PreferenceCode", "association", "0:N", "Classification", "Classification"),
    ("NationalTariffLine", "QuotaAllocation", "association", "0:N", "Classification", "Classification"),
    ("NationalTariffLine", "Restriction", "association", "0:N", "Classification", "Classification"),
    ("HarmonizedSystem", "DutyTaxFee", "association", "1:N", "Classification", "Financial"),
    ("Classification", "HarmonizedSystem", "association", "1:1", "Goods", "Classification"),

    # Risk domain
    ("RiskAssessment", "ExaminationNotice", "composition", "0:1", "Risk & Control", "Risk & Control"),
    ("ExaminationNotice", "ExaminationResult", "composition", "0:1", "Risk & Control", "Risk & Control"),
    ("RiskAssessment", "Selectivity", "association", "1:1", "Risk & Control", "Risk & Control"),
    ("RiskAssessment", "GovernmentProcedure", "association", "0:N", "Risk & Control", "Risk & Control"),
    ("Selectivity", "Declaration", "association", "1:1", "Risk & Control", "Declaration"),
    ("ExaminationResult", "GoodsItem", "association", "0:N", "Risk & Control", "Goods"),

    # Origin domain
    ("CertificateOfOrigin", "PreferentialTreatment", "association", "0:1", "Origin", "Origin"),
    ("CertificateOfOrigin", "RulesOfOrigin", "association", "1:1", "Origin", "Origin"),
    ("CertificateOfOrigin", "OriginDeclaration", "association", "0:1", "Origin", "Origin"),
    ("RulesOfOrigin", "RegionalValueContent", "composition", "0:1", "Origin", "Origin"),
    ("RulesOfOrigin", "CumulationRule", "association", "0:N", "Origin", "Origin"),
    ("PreferentialTreatment", "NationalTariffLine", "association", "1:1", "Origin", "Classification"),
    ("CertificateOfOrigin", "GoodsItem", "association", "1:N", "Origin", "Goods"),
    ("CertificateOfOrigin", "Exporter", "association", "1:1", "Origin", "Party"),
    ("OriginDeclaration", "Exporter", "association", "1:1", "Origin", "Party"),

    # Warehouse domain
    ("Warehouse", "CustomsBondedArea", "specialization", "0:1", "Warehouse", "Warehouse"),
    ("Warehouse", "TemporaryStorage", "specialization", "0:1", "Warehouse", "Warehouse"),
    ("FreeZone", "Warehouse", "association", "0:N", "Warehouse", "Warehouse"),
    ("InwardProcessing", "Declaration", "association", "1:N", "Warehouse", "Declaration"),
    ("OutwardProcessing", "Declaration", "association", "1:N", "Warehouse", "Declaration"),
    ("Warehouse", "GoodsItem", "association", "0:N", "Warehouse", "Goods"),
    ("Warehouse", "WarehouseKeeper", "association", "1:1", "Warehouse", "Party"),
    ("Warehouse", "Location", "association", "1:1", "Warehouse", "Location"),
    ("FreeZone", "Location", "association", "1:1", "Warehouse", "Location"),
    ("InwardProcessing", "GoodsItem", "association", "1:N", "Warehouse", "Goods"),
    ("OutwardProcessing", "GoodsItem", "association", "1:N", "Warehouse", "Goods"),
    ("TemporaryStorage", "Location", "association", "1:1", "Warehouse", "Location"),

    # E-Commerce domain
    ("ECommerceItem", "GoodsItem", "association", "1:1", "E-Commerce", "Goods"),
    ("ECommerceItem", "DeMinimisDeclaration", "association", "0:1", "E-Commerce", "E-Commerce"),
    ("ECommerceItem", "SimplifiedDeclaration", "association", "0:1", "E-Commerce", "E-Commerce"),
    ("ReturnGoods", "GoodsItem", "association", "1:N", "E-Commerce", "Goods"),
    ("ReturnGoods", "Declaration", "association", "1:1", "E-Commerce", "Declaration"),
    ("PostalItem", "ECommerceItem", "specialization", "0:1", "E-Commerce", "E-Commerce"),
    ("CourierShipment", "ECommerceItem", "specialization", "0:1", "E-Commerce", "E-Commerce"),
    ("PostalItem", "Consignment", "association", "1:1", "E-Commerce", "Consignment"),
    ("CourierShipment", "Consignment", "association", "1:1", "E-Commerce", "Consignment"),
    ("ECommerceItem", "Buyer", "association", "1:1", "E-Commerce", "Party"),
    ("ECommerceItem", "Seller", "association", "1:1", "E-Commerce", "Party"),
    ("DeMinimisDeclaration", "Declaration", "association", "1:1", "E-Commerce", "Declaration"),

    # Response domain
    ("Response", "DecisionNotification", "composition", "0:N", "Response", "Response"),
    ("Response", "ReleaseNotification", "composition", "0:1", "Response", "Response"),
    ("Response", "QueryNotification", "composition", "0:N", "Response", "Response"),
    ("Response", "ErrorNotification", "composition", "0:N", "Response", "Response"),
    ("Response", "PenaltyAssessment", "composition", "0:N", "Response", "Response"),
    ("Response", "Declaration", "association", "1:1", "Response", "Declaration"),
    ("ReleaseNotification", "GoodsItem", "association", "0:N", "Response", "Goods"),
    ("PenaltyAssessment", "Party", "association", "1:1", "Response", "Party"),
    ("QueryNotification", "AdditionalDocument", "association", "0:N", "Response", "Document"),

    # Cross-domain analytical
    ("Declaration", "Warehouse", "association", "0:1", "Declaration", "Warehouse"),
    ("Declaration", "FreeZone", "association", "0:1", "Declaration", "Warehouse"),
    ("Declaration", "ECommerceItem", "association", "0:N", "Declaration", "E-Commerce"),
    ("GoodsItem", "PreferentialTreatment", "association", "0:1", "Goods", "Origin"),
    ("GoodsItem", "RulesOfOrigin", "association", "0:1", "Goods", "Origin"),
    ("Consignment", "Warehouse", "association", "0:1", "Consignment", "Warehouse"),
    ("TransportEquipment", "Location", "association", "0:N", "Transport", "Location"),
    ("CustomsValuation", "GoodsItem", "association", "1:1", "Financial", "Goods"),
    ("ObligationGuarantee", "Declaration", "association", "1:1", "Financial", "Declaration"),
    ("RiskAssessment", "Party", "association", "1:1", "Risk & Control", "Party"),
    ("RiskAssessment", "GoodsItem", "association", "0:N", "Risk & Control", "Goods"),
    ("ExaminationNotice", "Location", "association", "0:1", "Risk & Control", "Location"),
    ("Selectivity", "HarmonizedSystem", "association", "0:N", "Risk & Control", "Classification"),
    ("GovernmentProcedure", "Declaration", "association", "1:1", "Risk & Control", "Declaration"),

    # Additional cross-domain relationships
    ("Consignment", "DestinationCountry", "association", "1:1", "Consignment", "Location"),
    ("TransportContractDocument", "Carrier", "association", "1:1", "Consignment", "Party"),
    ("TransportContractDocument", "Location", "association", "0:N", "Consignment", "Location"),
    ("GoodsItem", "Warehouse", "association", "0:1", "Goods", "Warehouse"),
    ("FreeZone", "Party", "association", "0:N", "Warehouse", "Party"),
    ("InwardProcessing", "CustomsValuation", "association", "0:N", "Warehouse", "Financial"),
    ("Certificate", "Party", "association", "1:1", "Document", "Party"),
    ("License", "Party", "association", "1:1", "Document", "Party"),
    ("Permit", "Party", "association", "1:1", "Document", "Party"),
    ("ExchangeRate", "Declaration", "association", "0:N", "Financial", "Declaration"),
    ("DutyTaxFee", "HarmonizedSystem", "association", "0:1", "Financial", "Classification"),
    ("TradeFinanceDocument", "Party", "association", "1:N", "Financial", "Party"),
    ("TradeFinanceDocument", "BankAccount", "association", "1:1", "Financial", "Financial"),
    ("CumulationRule", "DestinationCountry", "association", "0:N", "Origin", "Location"),
    ("QuotaAllocation", "Declaration", "association", "0:N", "Classification", "Declaration"),
    ("Restriction", "GoodsItem", "association", "0:N", "Classification", "Goods"),
    ("PenaltyAssessment", "Declaration", "association", "1:1", "Response", "Declaration"),
    ("SimplifiedDeclaration", "Party", "association", "1:1", "E-Commerce", "Party"),
    ("Selectivity", "Party", "association", "0:1", "Risk & Control", "Party"),
    ("NationalTariffLine", "DutyTaxFee", "association", "1:N", "Classification", "Financial"),

    # More cross-domain to reach ~300
    ("BorderTransportMeans", "Location", "association", "1:1", "Transport", "Location"),
    ("BorderTransportMeans", "Carrier", "association", "1:1", "Transport", "Party"),
    ("ArrivalTransportMeans", "EntryPort", "association", "0:1", "Transport", "Location"),
    ("DepartureTransportMeans", "ExitPort", "association", "0:1", "Transport", "Location"),
    ("TransitTransportMeans", "Itinerary", "association", "0:1", "Transport", "Transport"),
    ("ConsignmentItem", "Packaging", "association", "0:N", "Consignment", "Goods"),
    ("Declaration", "GovernmentProcedure", "association", "1:N", "Declaration", "Risk & Control"),
    ("Declaration", "CertificateOfOrigin", "association", "0:N", "Declaration", "Origin"),
    ("GoodsItem", "InwardProcessing", "association", "0:1", "Goods", "Warehouse"),
    ("GoodsItem", "OutwardProcessing", "association", "0:1", "Goods", "Warehouse"),
    ("GoodsItem", "FreeZone", "association", "0:1", "Goods", "Warehouse"),
    ("GoodsItem", "TemporaryStorage", "association", "0:1", "Goods", "Warehouse"),
    ("Consignment", "CustomsOffice", "association", "0:N", "Consignment", "Location"),
    ("Declaration", "EntryPort", "association", "0:1", "Declaration", "Location"),
    ("Declaration", "ExitPort", "association", "0:1", "Declaration", "Location"),
    ("Declaration", "DestinationCountry", "association", "0:1", "Declaration", "Location"),
    ("TransportEquipment", "Consignment", "association", "0:N", "Transport", "Consignment"),
    ("Seal", "RiskAssessment", "association", "0:1", "Transport", "Risk & Control"),
    ("Payment", "Declaration", "association", "1:1", "Financial", "Declaration"),
    ("AccountingEntry", "Declaration", "association", "1:1", "Financial", "Declaration"),
]

rels = []
for parent, child, rtype, card, pd, cd in RELS:
    rels.append({
        "parent": parent,
        "child": child,
        "type": rtype,
        "cardinality": card,
        "parentDomain": pd,
        "childDomain": cd
    })

with open(os.path.join(OUTPUT_DIR, 'relationships.json'), 'w') as f:
    json.dump(rels, f, indent=2)

print(f"relationships.json: {len(rels)} relationships")
