#!/usr/bin/env python3
"""Generate dataRequirements.json for TAIW — ~120 trade data requirements"""
import json, os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'src', 'data', 'taiw')

REQS = [
    # Party domain requirements
    {"id": "req_trader_identity", "name": "Trader Identity & Registration", "wcoDomain": "Party", "capabilitiesUsing": 15, "capabilities": ["trader_360_profile", "trader_segmentation", "risk_profiling_engine", "trader_risk_scoring", "aeo_application_pipeline", "new_trader_onboarding_analytics"], "description": "Complete trader identification including NTN, CNIC, AEO status, WeBOC registration"},
    {"id": "req_party_roles", "name": "Party Roles & Functions", "wcoDomain": "Party", "capabilitiesUsing": 12, "capabilities": ["trader_360_profile", "related_party_network_analysis", "transfer_pricing_detection"], "description": "Mapping of party functions — importer, exporter, agent, broker, carrier relationships"},
    {"id": "req_agent_details", "name": "Agent & Broker Details", "wcoDomain": "Party", "capabilitiesUsing": 8, "capabilities": ["trader_360_profile", "document_fraud_detection", "trader_compliance_scorecard"], "description": "Clearing agent licence, representation type, historical performance"},
    {"id": "req_aeo_authorization", "name": "AEO Authorization Data", "wcoDomain": "Party", "capabilitiesUsing": 10, "capabilities": ["aeo_application_pipeline", "aeo_benefit_measurement", "aeo_compliance_monitoring", "aeo_mutual_recognition", "aeo_tier_analytics", "aeo_program_roi"], "description": "AEO tier, certification date, compliance history, benefit utilization"},
    {"id": "req_beneficial_ownership", "name": "Beneficial Ownership", "wcoDomain": "Party", "capabilitiesUsing": 5, "capabilities": ["related_party_network_analysis", "trade_based_money_laundering", "trader_risk_scoring"], "description": "Beneficial ownership chain, related parties, corporate structure"},
    {"id": "req_trader_financial", "name": "Trader Financial Profile", "wcoDomain": "Party", "capabilitiesUsing": 6, "capabilities": ["trader_360_profile", "trader_risk_scoring", "trader_segmentation"], "description": "Credit history, duty payment track record, guarantee utilization"},
    {"id": "req_trader_contact", "name": "Trader Contact & Communication", "wcoDomain": "Party", "capabilitiesUsing": 4, "capabilities": ["trader_communication_outreach", "trader_360_profile"], "description": "Contact details, communication preferences, registered addresses"},

    # Declaration domain
    {"id": "req_gd_header", "name": "GD Header Data", "wcoDomain": "Declaration", "capabilitiesUsing": 20, "capabilities": ["clearance_time_analytics", "gd_processing_analytics", "revenue_dashboarding", "risk_profiling_engine"], "description": "Declaration type, registration number, dates, customs office, procedure codes"},
    {"id": "req_gd_items", "name": "GD Line Items", "wcoDomain": "Declaration", "capabilitiesUsing": 18, "capabilities": ["hs_code_classification_engine", "declared_value_verification", "duty_differential_analysis"], "description": "Item-level details — HS code, value, quantity, origin per line"},
    {"id": "req_previous_docs", "name": "Previous Document References", "wcoDomain": "Declaration", "capabilitiesUsing": 8, "capabilities": ["post_clearance_audit_analytics", "trade_data_reconciliation", "duty_drawback_analytics"], "description": "Links to prior GDs, IGMs, warrants for audit trails"},
    {"id": "req_amendment_history", "name": "Amendment History", "wcoDomain": "Declaration", "capabilitiesUsing": 6, "capabilities": ["post_clearance_audit_analytics", "document_fraud_detection", "data_quality_scorecarding"], "description": "Declaration amendment trail — what changed, when, by whom"},
    {"id": "req_cancellation_data", "name": "Cancellation Data", "wcoDomain": "Declaration", "capabilitiesUsing": 4, "capabilities": ["gd_processing_analytics", "data_quality_scorecarding"], "description": "Cancelled GDs — reasons, timing, patterns"},
    {"id": "req_clearance_timestamps", "name": "Clearance Timestamps", "wcoDomain": "Declaration", "capabilitiesUsing": 12, "capabilities": ["clearance_time_analytics", "bottleneck_identification", "sla_tracking", "24_7_clearance_analytics"], "description": "Lodgement, acceptance, assessment, release, out-of-charge timestamps"},
    {"id": "req_procedure_codes", "name": "Procedure Codes", "wcoDomain": "Declaration", "capabilitiesUsing": 10, "capabilities": ["gd_processing_analytics", "regulatory_compliance_reporting", "sro_concession_tracking"], "description": "CPC codes, requested/previous procedures, additional procedures"},
    {"id": "req_selectivity_data", "name": "Selectivity & Channel Data", "wcoDomain": "Declaration", "capabilitiesUsing": 14, "capabilities": ["risk_profiling_engine", "selectivity_channel_assignment", "green_channel_optimization"], "description": "Assigned channel (G/Y/R/B), risk rule triggered, officer allocation"},

    # Goods domain
    {"id": "req_hs_classification", "name": "HS Classification Data", "wcoDomain": "Goods", "capabilitiesUsing": 25, "capabilities": ["hs_code_classification_engine", "commodity_flow_analysis", "tariff_schedule_management", "commodity_risk_matrix"], "description": "HS 6-digit + national tariff line, classification type, PCT heading"},
    {"id": "req_goods_description", "name": "Goods Description", "wcoDomain": "Goods", "capabilitiesUsing": 10, "capabilities": ["hs_code_classification_engine", "smuggling_pattern_detection", "document_fraud_detection"], "description": "Free-text goods description, brand, model, technical specs"},
    {"id": "req_quantity_weight", "name": "Quantity & Weight Data", "wcoDomain": "Goods", "capabilitiesUsing": 15, "capabilities": ["declared_value_verification", "revenue_per_unit", "trade_balance_dashboard"], "description": "Net mass, gross mass, supplementary quantity, unit of measure"},
    {"id": "req_packaging_details", "name": "Packaging Details", "wcoDomain": "Goods", "capabilitiesUsing": 5, "capabilities": ["port_throughput_analytics", "container_dwell_time", "warehouse_bonded_area_utilization"], "description": "Package type, count, marks and numbers, dimensions"},
    {"id": "req_dangerous_goods", "name": "Dangerous Goods Data", "wcoDomain": "Goods", "capabilitiesUsing": 4, "capabilities": ["smuggling_pattern_detection", "border_intelligence_analytics", "port_throughput_analytics"], "description": "DG class, UN number, flash point, packing group, emergency contact"},
    {"id": "req_dual_use", "name": "Dual-Use Goods Classification", "wcoDomain": "Goods", "capabilitiesUsing": 3, "capabilities": ["sanctions_embargo_screening", "border_intelligence_analytics"], "description": "Strategic goods classification, export control codes"},
    {"id": "req_goods_valuation", "name": "Goods Item Valuation", "wcoDomain": "Goods", "capabilitiesUsing": 18, "capabilities": ["declared_value_verification", "value_trend_analytics", "transaction_value_database"], "description": "Item-level CIF/FOB value, unit price, valuation adjustments"},
    {"id": "req_brand_model", "name": "Brand & Model Data", "wcoDomain": "Goods", "capabilitiesUsing": 6, "capabilities": ["hs_code_classification_engine", "declared_value_verification", "price_prediction_models"], "description": "Brand name, model, product codes for reference pricing"},

    # Financial domain
    {"id": "req_customs_valuation", "name": "Customs Valuation Data", "wcoDomain": "Financial", "capabilitiesUsing": 20, "capabilities": ["declared_value_verification", "transfer_pricing_detection", "transaction_value_database", "valuation_method_selection"], "description": "Declared value, customs value, valuation method, adjustments, WTO method code"},
    {"id": "req_duty_assessment", "name": "Duty Assessment Data", "wcoDomain": "Financial", "capabilitiesUsing": 18, "capabilities": ["revenue_dashboarding", "revenue_forecasting", "leakage_detection", "duty_differential_analysis"], "description": "All duty/tax types assessed — CD, ACD, RD, ST, WHT, FED amounts and rates"},
    {"id": "req_tax_calculation", "name": "Tax Calculation Details", "wcoDomain": "Financial", "capabilitiesUsing": 12, "capabilities": ["revenue_dashboarding", "budget_vs_actual_tracking", "revenue_forecasting"], "description": "Breakdown of each tax type — base, rate, amount, concession applied"},
    {"id": "req_payment_data", "name": "Payment Data", "wcoDomain": "Financial", "capabilitiesUsing": 10, "capabilities": ["electronic_payment_analytics", "revenue_dashboarding", "refund_drawback_management"], "description": "Payment method, date, receipt, bank, e-payment transaction ID"},
    {"id": "req_guarantee_bond", "name": "Guarantee & Bond Data", "wcoDomain": "Financial", "capabilitiesUsing": 6, "capabilities": ["warehouse_bonded_area_utilization", "aeo_benefit_measurement"], "description": "Bond type, amount, validity, bank guarantee references"},
    {"id": "req_exchange_rates", "name": "Exchange Rate Data", "wcoDomain": "Financial", "capabilitiesUsing": 10, "capabilities": ["exchange_rate_impact_analysis", "declared_value_verification", "revenue_forecasting"], "description": "SBP rate, applied rate, rate date, currency code"},
    {"id": "req_sro_concessions", "name": "SRO Concession Data", "wcoDomain": "Financial", "capabilitiesUsing": 10, "capabilities": ["sro_concession_tracking", "leakage_detection", "duty_differential_analysis", "regulatory_duty_impact"], "description": "SRO reference, concession type, saving amount, eligible items"},
    {"id": "req_refund_drawback", "name": "Refund & Drawback Data", "wcoDomain": "Financial", "capabilitiesUsing": 6, "capabilities": ["refund_drawback_management", "duty_drawback_analytics"], "description": "Refund claims, drawback calculations, previous duty paid references"},
    {"id": "req_reference_prices", "name": "Reference Price Database", "wcoDomain": "Financial", "capabilitiesUsing": 8, "capabilities": ["declared_value_verification", "transaction_value_database", "value_trend_analytics"], "description": "DG Valuation reference prices by HS code, origin, period"},
    {"id": "req_trade_finance", "name": "Trade Finance Instruments", "wcoDomain": "Financial", "capabilitiesUsing": 5, "capabilities": ["trade_based_money_laundering", "declared_value_verification"], "description": "LC, DA/DP, TT, open account details linked to imports"},

    # Transport domain
    {"id": "req_vessel_flight", "name": "Vessel/Flight Details", "wcoDomain": "Transport", "capabilitiesUsing": 10, "capabilities": ["port_throughput_analytics", "carrier_performance_analytics", "end_to_end_shipment_tracking"], "description": "IMO number, vessel name, flag state, voyage/flight number"},
    {"id": "req_container_tracking", "name": "Container Tracking Data", "wcoDomain": "Transport", "capabilitiesUsing": 12, "capabilities": ["container_dwell_time", "container_tracking_integration", "port_throughput_analytics"], "description": "Container ID, size/type, status, location, dwell time, scan results"},
    {"id": "req_seal_data", "name": "Seal Data", "wcoDomain": "Transport", "capabilitiesUsing": 6, "capabilities": ["smuggling_pattern_detection", "afghan_transit_trade_monitoring", "tir_convention_compliance"], "description": "Seal type, number, affixing party, condition upon examination"},
    {"id": "req_route_itinerary", "name": "Route & Itinerary Data", "wcoDomain": "Transport", "capabilitiesUsing": 8, "capabilities": ["route_optimization", "cpec_route_analytics", "afghan_transit_trade_analytics"], "description": "Transport route, transit countries, estimated/actual dates, CPEC corridor flag"},
    {"id": "req_multimodal", "name": "Multi-Modal Transport Data", "wcoDomain": "Transport", "capabilitiesUsing": 5, "capabilities": ["end_to_end_shipment_tracking", "route_optimization", "lead_time_analytics"], "description": "Mode changes during transport, intermodal transfer points"},
    {"id": "req_vehicle_data", "name": "Vehicle & Driver Data", "wcoDomain": "Transport", "capabilitiesUsing": 5, "capabilities": ["afghan_transit_trade_monitoring", "border_intelligence_analytics", "controlled_delivery_tracking"], "description": "Vehicle registration, driver ID, bonded carrier licence, GPS tracking"},
    {"id": "req_terminal_data", "name": "Terminal Operations Data", "wcoDomain": "Transport", "capabilitiesUsing": 6, "capabilities": ["port_throughput_analytics", "terminal_performance_benchmarking", "container_dwell_time"], "description": "Terminal code, berth assignment, handling times, yard location"},

    # Origin domain
    {"id": "req_certificate_origin", "name": "Certificate of Origin Data", "wcoDomain": "Origin", "capabilitiesUsing": 12, "capabilities": ["fta_preference_management", "declared_value_verification", "regulatory_compliance_reporting"], "description": "CO number, issuing body, origin criteria, preferential treatment claim"},
    {"id": "req_preferential_treatment", "name": "Preferential Treatment Data", "wcoDomain": "Origin", "capabilitiesUsing": 10, "capabilities": ["fta_preference_management", "duty_differential_analysis", "regulatory_duty_impact"], "description": "FTA code, preference rate, duty saving, utilization rate"},
    {"id": "req_rules_origin", "name": "Rules of Origin Compliance", "wcoDomain": "Origin", "capabilitiesUsing": 8, "capabilities": ["fta_preference_management", "document_fraud_detection", "regulatory_compliance_reporting"], "description": "Origin criterion met (CTC/RVC/process), cumulation rules applied"},
    {"id": "req_cumulation", "name": "Cumulation Data", "wcoDomain": "Origin", "capabilitiesUsing": 4, "capabilities": ["fta_preference_management", "trading_partner_analytics"], "description": "Cumulation type, partner countries, material sourcing chain"},

    # Risk domain
    {"id": "req_risk_scores", "name": "Risk Score Data", "wcoDomain": "Risk & Control", "capabilitiesUsing": 15, "capabilities": ["risk_profiling_engine", "selectivity_channel_assignment", "trader_risk_scoring", "ml_risk_models"], "description": "Risk scores per declaration, rule hits, confidence levels, historical patterns"},
    {"id": "req_selectivity_results", "name": "Selectivity Results", "wcoDomain": "Risk & Control", "capabilitiesUsing": 12, "capabilities": ["selectivity_channel_assignment", "green_channel_optimization", "risk_rule_management"], "description": "Channel assigned, rules triggered, override history, effectiveness metrics"},
    {"id": "req_examination_outcomes", "name": "Examination Outcomes", "wcoDomain": "Risk & Control", "capabilitiesUsing": 10, "capabilities": ["post_clearance_audit_selection", "risk_profiling_engine", "smuggling_pattern_detection"], "description": "Exam type, result, discrepancies found, seizure data, officer notes"},
    {"id": "req_intelligence_feeds", "name": "Intelligence Feeds", "wcoDomain": "Risk & Control", "capabilitiesUsing": 6, "capabilities": ["intelligence_led_targeting", "border_intelligence_analytics", "smuggling_pattern_detection"], "description": "NTC alerts, intelligence bulletins, watch lists, suspect profiles"},
    {"id": "req_seizure_data", "name": "Seizure & Violation Data", "wcoDomain": "Risk & Control", "capabilitiesUsing": 8, "capabilities": ["smuggling_pattern_detection", "trader_compliance_scorecard", "border_intelligence_analytics"], "description": "Seizure records, violation types, penalty amounts, adjudication outcomes"},
    {"id": "req_pca_data", "name": "Post-Clearance Audit Data", "wcoDomain": "Risk & Control", "capabilitiesUsing": 6, "capabilities": ["post_clearance_audit_analytics", "post_clearance_audit_selection", "self_assessment_verification"], "description": "PCA selection criteria, audit findings, duty recovery, compliance gaps"},

    # Location domain
    {"id": "req_port_terminal", "name": "Port & Terminal Data", "wcoDomain": "Location", "capabilitiesUsing": 10, "capabilities": ["port_throughput_analytics", "terminal_performance_benchmarking", "container_dwell_time"], "description": "Port code, terminal, berth, customs station, handling capacity"},
    {"id": "req_warehouse_inventory", "name": "Warehouse Inventory Data", "wcoDomain": "Location", "capabilitiesUsing": 6, "capabilities": ["warehouse_bonded_area_utilization", "free_zone_performance"], "description": "Warehouse stock levels, entry/exit records, bond utilization"},
    {"id": "req_free_zone", "name": "Free Zone Activity Data", "wcoDomain": "Location", "capabilitiesUsing": 5, "capabilities": ["free_zone_performance", "cpec_route_analytics"], "description": "Free zone operations, investment, employment, export production"},
    {"id": "req_dry_port", "name": "Dry Port Operations Data", "wcoDomain": "Location", "capabilitiesUsing": 4, "capabilities": ["dry_port_operations", "route_optimization"], "description": "Dry port throughput, NLC consignment notes, inland clearance"},
    {"id": "req_customs_office", "name": "Customs Office Data", "wcoDomain": "Location", "capabilitiesUsing": 8, "capabilities": ["clearance_time_analytics", "bottleneck_identification", "sla_tracking"], "description": "Office capacity, staff count, workload, processing speed"},
    {"id": "req_border_crossing", "name": "Border Crossing Data", "wcoDomain": "Location", "capabilitiesUsing": 6, "capabilities": ["afghan_transit_trade_analytics", "border_intelligence_analytics", "cpec_route_analytics"], "description": "Border point traffic, wait times, crossing restrictions"},

    # Statistics domain (cross-domain)
    {"id": "req_trade_volumes", "name": "Trade Volume Statistics", "wcoDomain": "Declaration", "capabilitiesUsing": 15, "capabilities": ["trade_balance_dashboard", "commodity_flow_analysis", "trading_partner_analytics", "trade_volume_forecasting"], "description": "Import/export volumes by commodity, country, port, period"},
    {"id": "req_revenue_figures", "name": "Revenue Collection Figures", "wcoDomain": "Financial", "capabilitiesUsing": 12, "capabilities": ["revenue_dashboarding", "revenue_forecasting", "budget_vs_actual_tracking", "leakage_detection"], "description": "Revenue by duty type, collectorate, commodity, period"},
    {"id": "req_clearance_times", "name": "Clearance Time Metrics", "wcoDomain": "Declaration", "capabilitiesUsing": 10, "capabilities": ["clearance_time_analytics", "bottleneck_identification", "sla_tracking", "24_7_clearance_analytics"], "description": "Time-release study data, step-by-step processing durations"},
    {"id": "req_compliance_rates", "name": "Compliance Rate Data", "wcoDomain": "Risk & Control", "capabilitiesUsing": 10, "capabilities": ["trader_compliance_scorecard", "aeo_compliance_monitoring", "regulatory_compliance_reporting"], "description": "Voluntary compliance rates, error rates, repeat offender statistics"},

    # Document domain
    {"id": "req_supporting_docs", "name": "Supporting Document Data", "wcoDomain": "Document", "capabilitiesUsing": 8, "capabilities": ["document_fraud_detection", "single_window_integration", "psw_integration_dashboard"], "description": "Document types attached, verification status, issuing authority"},
    {"id": "req_certificates", "name": "Certificate Data", "wcoDomain": "Document", "capabilitiesUsing": 6, "capabilities": ["fta_preference_management", "regulatory_compliance_reporting"], "description": "Origin certificates, health certificates, conformity certificates"},
    {"id": "req_licences_permits", "name": "Licences & Permits Data", "wcoDomain": "Document", "capabilitiesUsing": 5, "capabilities": ["single_window_integration", "psw_integration_dashboard", "regulatory_compliance_reporting"], "description": "Import licences, OGA permits, validity, electronic clearances"},
    {"id": "req_invoices", "name": "Commercial Invoice Data", "wcoDomain": "Document", "capabilitiesUsing": 10, "capabilities": ["declared_value_verification", "transfer_pricing_detection", "document_fraud_detection"], "description": "Invoice amounts, dates, parties, payment terms, Incoterms"},

    # Classification domain
    {"id": "req_tariff_schedule", "name": "Tariff Schedule Data", "wcoDomain": "Classification", "capabilitiesUsing": 15, "capabilities": ["tariff_schedule_management", "hs_code_classification_engine", "sro_concession_tracking"], "description": "Complete PCT schedule with duty rates, SROs, concessions per tariff line"},
    {"id": "req_hs_updates", "name": "HS Nomenclature Updates", "wcoDomain": "Classification", "capabilitiesUsing": 6, "capabilities": ["hs_code_classification_engine", "tariff_schedule_management", "code_list_harmonization"], "description": "HS version changes, correlation tables, national tariff amendments"},
    {"id": "req_sro_register", "name": "SRO Register", "wcoDomain": "Classification", "capabilitiesUsing": 8, "capabilities": ["sro_concession_tracking", "leakage_detection", "regulatory_duty_impact"], "description": "Complete SRO register — active, expired, conditions, eligible HS codes"},
    {"id": "req_quota_allocations", "name": "Quota Allocation Data", "wcoDomain": "Classification", "capabilitiesUsing": 4, "capabilities": ["tariff_schedule_management", "import_dependency_analysis"], "description": "Tariff quotas, allocation status, utilization rates"},
    {"id": "req_restrictions", "name": "Trade Restrictions Data", "wcoDomain": "Classification", "capabilitiesUsing": 5, "capabilities": ["sanctions_embargo_screening", "regulatory_compliance_reporting"], "description": "Import/export prohibitions, restrictions, strategic goods controls"},

    # Warehouse domain
    {"id": "req_warehouse_ops", "name": "Warehouse Operations Data", "wcoDomain": "Warehouse", "capabilitiesUsing": 6, "capabilities": ["warehouse_bonded_area_utilization", "port_throughput_analytics"], "description": "Warehouse entry/exit records, stock levels, bond utilization"},
    {"id": "req_inward_processing", "name": "Inward Processing Data", "wcoDomain": "Warehouse", "capabilitiesUsing": 4, "capabilities": ["duty_drawback_analytics", "warehouse_bonded_area_utilization"], "description": "IP authorizations, input-output coefficients, re-export performance"},
    {"id": "req_free_zone_ops", "name": "Free Zone Operations", "wcoDomain": "Warehouse", "capabilitiesUsing": 4, "capabilities": ["free_zone_performance", "cpec_route_analytics"], "description": "FZ operator data, investment, production, employment metrics"},
    {"id": "req_temp_storage", "name": "Temporary Storage Data", "wcoDomain": "Warehouse", "capabilitiesUsing": 3, "capabilities": ["port_throughput_analytics", "container_dwell_time"], "description": "Temporary storage declarations, periods, overstay incidents"},

    # E-Commerce domain
    {"id": "req_ecommerce_data", "name": "E-Commerce Transaction Data", "wcoDomain": "E-Commerce", "capabilitiesUsing": 5, "capabilities": ["trade_volume_forecasting", "trade_balance_dashboard"], "description": "Platform, order details, value, return patterns for cross-border e-commerce"},
    {"id": "req_postal_courier", "name": "Postal & Courier Data", "wcoDomain": "E-Commerce", "capabilitiesUsing": 4, "capabilities": ["port_throughput_analytics", "clearance_time_analytics"], "description": "Postal item volumes, courier shipments, de minimis threshold compliance"},
    {"id": "req_deminimis", "name": "De Minimis Threshold Data", "wcoDomain": "E-Commerce", "capabilitiesUsing": 3, "capabilities": ["regulatory_compliance_reporting", "revenue_forecasting"], "description": "Low-value shipment volumes, revenue impact of de minimis thresholds"},

    # Consignment domain
    {"id": "req_manifest_data", "name": "Manifest/IGM Data", "wcoDomain": "Consignment", "capabilitiesUsing": 10, "capabilities": ["port_throughput_analytics", "carrier_performance_analytics", "pre_arrival_processing"], "description": "Import/Export General Manifest data — line items, BL references, carrier"},
    {"id": "req_bl_data", "name": "Bill of Lading Data", "wcoDomain": "Consignment", "capabilitiesUsing": 8, "capabilities": ["end_to_end_shipment_tracking", "carrier_performance_analytics"], "description": "Master/house B/L numbers, shipper, consignee, goods description"},
    {"id": "req_consolidation", "name": "Consolidation Data", "wcoDomain": "Consignment", "capabilitiesUsing": 4, "capabilities": ["port_throughput_analytics", "container_dwell_time"], "description": "LCL consolidation/deconsolidation records, CFS operations"},
    {"id": "req_transit_data", "name": "Transit Movement Data", "wcoDomain": "Consignment", "capabilitiesUsing": 8, "capabilities": ["afghan_transit_trade_analytics", "afghan_transit_trade_monitoring", "tir_convention_compliance"], "description": "Transit declarations, route, seals, guarantees, arrival confirmation"},
    {"id": "req_atta_data", "name": "Afghan Transit Trade Data", "wcoDomain": "Consignment", "capabilitiesUsing": 6, "capabilities": ["afghan_transit_trade_analytics", "afghan_transit_trade_monitoring", "smuggling_pattern_detection"], "description": "ATTA permits, goods types, routes, diversion indicators"},

    # Response domain
    {"id": "req_decision_data", "name": "Customs Decision Data", "wcoDomain": "Response", "capabilitiesUsing": 8, "capabilities": ["gd_processing_analytics", "clearance_time_analytics", "regulatory_compliance_reporting"], "description": "Acceptance, rejection, query, release decisions with timestamps"},
    {"id": "req_penalty_data", "name": "Penalty & Adjudication Data", "wcoDomain": "Response", "capabilitiesUsing": 5, "capabilities": ["trader_compliance_scorecard", "regulatory_compliance_reporting", "smuggling_pattern_detection"], "description": "Penalties assessed, sections cited, amounts, appeal status"},
    {"id": "req_query_data", "name": "Query & Response Data", "wcoDomain": "Response", "capabilitiesUsing": 4, "capabilities": ["bottleneck_identification", "gd_processing_analytics"], "description": "Customs queries, response times, query categories"},

    # System/Analytics
    {"id": "req_weboc_performance", "name": "WeBOC System Metrics", "wcoDomain": "Declaration", "capabilitiesUsing": 6, "capabilities": ["weboc_system_performance", "gd_processing_analytics", "system_modernization_roadmap"], "description": "System uptime, response times, transaction volumes, error rates"},
    {"id": "req_psw_metrics", "name": "PSW Integration Metrics", "wcoDomain": "Document", "capabilitiesUsing": 5, "capabilities": ["psw_integration_dashboard", "single_window_integration"], "description": "OGA clearance times, electronic document volumes, rejection rates"},
    {"id": "req_data_quality", "name": "Data Quality Metrics", "wcoDomain": "Declaration", "capabilitiesUsing": 6, "capabilities": ["data_quality_scorecarding", "wco_dm_conformity_assessment", "master_data_management"], "description": "Missing fields, invalid values, duplicate records, inconsistency rates"},
    {"id": "req_mirror_statistics", "name": "Mirror Trade Statistics", "wcoDomain": "Goods", "capabilitiesUsing": 5, "capabilities": ["trade_data_reconciliation", "declared_value_verification", "trade_balance_dashboard"], "description": "Partner country trade data for bilateral comparison and gap detection"},

    # Additional cross-domain requirements
    {"id": "req_historical_trends", "name": "Historical Trade Trends", "wcoDomain": "Declaration", "capabilitiesUsing": 10, "capabilities": ["trade_volume_forecasting", "seasonal_trade_patterns", "price_prediction_models"], "description": "Multi-year trade data for trend analysis, forecasting, seasonal patterns"},
    {"id": "req_benchmark_data", "name": "International Benchmark Data", "wcoDomain": "Declaration", "capabilitiesUsing": 6, "capabilities": ["terminal_performance_benchmarking", "wco_dm_conformity_assessment"], "description": "WCO TRS data, World Bank Doing Business, global customs KPIs"},
    {"id": "req_geographic_data", "name": "Geographic & Mapping Data", "wcoDomain": "Location", "capabilitiesUsing": 4, "capabilities": ["port_throughput_analytics", "route_optimization", "cpec_route_analytics"], "description": "Port coordinates, route distances, transit times, corridor data"},
    {"id": "req_economic_indicators", "name": "Economic Indicators", "wcoDomain": "Financial", "capabilitiesUsing": 6, "capabilities": ["revenue_forecasting", "trade_volume_forecasting", "budget_vs_actual_tracking"], "description": "GDP growth, inflation, PKR exchange rate trends, trade-to-GDP ratio"},
    {"id": "req_staffing_data", "name": "Customs Staffing Data", "wcoDomain": "Party", "capabilitiesUsing": 4, "capabilities": ["bottleneck_identification", "clearance_time_analytics", "queue_management"], "description": "Officer count per station, shift data, specialization, workload metrics"},

    # More to reach ~120
    {"id": "req_cpec_data", "name": "CPEC Trade Data", "wcoDomain": "Transport", "capabilitiesUsing": 5, "capabilities": ["cpec_route_analytics", "transshipment_hub_performance"], "description": "CPEC corridor shipments, Gwadar volumes, SEZ imports/exports"},
    {"id": "req_fta_utilization", "name": "FTA Utilization Data", "wcoDomain": "Origin", "capabilitiesUsing": 6, "capabilities": ["fta_preference_management", "export_diversification_metrics", "trading_partner_analytics"], "description": "FTA preference claims, utilization rates, duty savings by agreement"},
    {"id": "req_export_data", "name": "Export Performance Data", "wcoDomain": "Declaration", "capabilitiesUsing": 8, "capabilities": ["export_diversification_metrics", "trade_balance_dashboard", "revenue_per_unit"], "description": "Export GDs, sectors, destinations, value, textile/non-textile breakdown"},
    {"id": "req_vendor_supplier", "name": "Vendor & Supplier Data", "wcoDomain": "Party", "capabilitiesUsing": 5, "capabilities": ["vendor_supplier_risk_mapping", "related_party_network_analysis", "transfer_pricing_detection"], "description": "Foreign supplier profiles, country, repeat patterns, pricing history"},
    {"id": "req_lead_times", "name": "Logistics Lead Time Data", "wcoDomain": "Transport", "capabilitiesUsing": 5, "capabilities": ["lead_time_analytics", "end_to_end_shipment_tracking", "route_optimization"], "description": "Port-to-port, door-to-door lead times, carrier reliability metrics"},
    {"id": "req_scanning_data", "name": "Non-Intrusive Inspection Data", "wcoDomain": "Risk & Control", "capabilitiesUsing": 4, "capabilities": ["smuggling_pattern_detection", "risk_profiling_engine"], "description": "X-ray/scanner results, image analysis, anomaly detection"},
    {"id": "req_auction_data", "name": "Auction & Confiscation Data", "wcoDomain": "Response", "capabilitiesUsing": 3, "capabilities": ["regulatory_compliance_reporting", "revenue_dashboarding"], "description": "Auctioned goods, confiscated items, unclaimed cargo disposals"},
    {"id": "req_edi_messages", "name": "EDI Message Data", "wcoDomain": "Declaration", "capabilitiesUsing": 4, "capabilities": ["mobile_api_channel_adoption", "weboc_system_performance", "data_sharing_framework"], "description": "EDIFACT/XML message volumes, error rates, processing times"},
    {"id": "req_epayment_data", "name": "E-Payment Transaction Data", "wcoDomain": "Financial", "capabilitiesUsing": 5, "capabilities": ["electronic_payment_analytics", "revenue_dashboarding"], "description": "E-payment volumes, bank channels, transaction success rates"},
    {"id": "req_carrier_performance", "name": "Carrier Performance Metrics", "wcoDomain": "Transport", "capabilitiesUsing": 5, "capabilities": ["carrier_performance_analytics", "end_to_end_shipment_tracking"], "description": "On-time delivery, damage rates, manifest accuracy by carrier"},
    {"id": "req_commodity_prices", "name": "International Commodity Prices", "wcoDomain": "Goods", "capabilitiesUsing": 6, "capabilities": ["price_prediction_models", "declared_value_verification", "demand_supply_gap_analysis"], "description": "Global commodity prices for reference — petroleum, metals, agriculture"},
    {"id": "req_regulatory_changes", "name": "Regulatory Change Data", "wcoDomain": "Classification", "capabilitiesUsing": 5, "capabilities": ["early_warning_system", "regulatory_duty_impact", "sro_concession_tracking"], "description": "New SROs, tariff changes, policy notifications, gazette entries"},
    {"id": "req_trader_feedback", "name": "Trader Feedback & Complaints", "wcoDomain": "Response", "capabilitiesUsing": 3, "capabilities": ["trader_communication_outreach", "sla_tracking"], "description": "Trader complaints, feedback surveys, service quality ratings"},
    {"id": "req_anti_smuggling", "name": "Anti-Smuggling Intelligence", "wcoDomain": "Risk & Control", "capabilitiesUsing": 5, "capabilities": ["smuggling_pattern_detection", "controlled_delivery_tracking", "border_intelligence_analytics"], "description": "Smuggling routes, modus operandi, informant data, seizure intelligence"},
    {"id": "req_money_laundering", "name": "Trade-Based Money Laundering Data", "wcoDomain": "Risk & Control", "capabilitiesUsing": 4, "capabilities": ["trade_based_money_laundering", "related_party_network_analysis"], "description": "Suspicious trade patterns, over/under invoicing, shell company indicators"},
    {"id": "req_wco_dm_mapping", "name": "WCO DM Mapping Data", "wcoDomain": "Classification", "capabilitiesUsing": 4, "capabilities": ["wco_dm_conformity_assessment", "code_list_harmonization", "data_sharing_framework"], "description": "National data element to WCO DM element mapping, gap analysis"},
    {"id": "req_master_data", "name": "Master Data Quality", "wcoDomain": "Classification", "capabilitiesUsing": 5, "capabilities": ["master_data_management", "data_quality_scorecarding", "code_list_harmonization"], "description": "Code list versions, reference data updates, harmonization status"},
    {"id": "req_predictive_inputs", "name": "Predictive Analytics Inputs", "wcoDomain": "Declaration", "capabilitiesUsing": 4, "capabilities": ["trade_volume_forecasting", "price_prediction_models", "early_warning_system"], "description": "Feature datasets for ML models — lagged variables, external factors"},
    {"id": "req_automation_metrics", "name": "Automation Level Metrics", "wcoDomain": "Declaration", "capabilitiesUsing": 5, "capabilities": ["weboc_system_performance", "system_modernization_roadmap", "mobile_api_channel_adoption"], "description": "STP rates, auto-assessment rates, electronic submission rates"},
    {"id": "req_energy_imports", "name": "Energy Import Data", "wcoDomain": "Goods", "capabilitiesUsing": 4, "capabilities": ["import_dependency_analysis", "trade_balance_dashboard", "commodity_flow_analysis"], "description": "Petroleum, LNG, coal imports — volumes, values, sourcing countries"},
    {"id": "req_textile_exports", "name": "Textile Export Data", "wcoDomain": "Goods", "capabilitiesUsing": 4, "capabilities": ["export_diversification_metrics", "trade_balance_dashboard", "seasonal_trade_patterns"], "description": "Textile sector exports — yarn, fabric, garments, knitwear by destination"},
]

with open(os.path.join(OUTPUT_DIR, 'dataRequirements.json'), 'w') as f:
    json.dump(REQS, f, indent=2)

print(f"dataRequirements.json: {len(REQS)} requirements")
