#!/usr/bin/env python3
"""Generate dataElements.json for TAIW — 727 WCO DM elements"""
import json, os, random

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'src', 'data', 'taiw')
random.seed(42)

# Element definitions per domain with realistic WCO DM names
ELEMENT_DEFS = {
    "Declaration": {
        "class_default": "Declaration",
        "elements": [
            ("Identification of declaration", "An identifier assigned by customs to the declaration", "Declaration", "an..35", None, "1004"),
            ("Type of declaration", "Code specifying the type of customs declaration", "Declaration", "an..3", "CL_001", "1001"),
            ("Message function code", "Code indicating the function of the declaration message", "Declaration", "an..3", "CL_002", "1225"),
            ("Date of declaration", "Date on which the declaration is made", "Declaration", "an..8", None, "2380"),
            ("Customs office of declaration", "Identity of the customs office where the declaration is lodged", "Declaration", "an..8", None, "3227"),
            ("Previous document reference", "Reference to a previous customs document", "PreviousDocument", "an..35", None, "1004"),
            ("Trader reference (UCR)", "Unique Consignment Reference assigned by the trader", "Declaration", "an..35", None, "1004"),
            ("Amendment reason code", "Code indicating the reason for amending a declaration", "Amendment", "an..3", None, "4441"),
            ("Total packages quantity", "Total number of packages in the declaration", "Declaration", "n..8", None, "7224"),
            ("Total gross mass", "Total gross weight of all goods items in the declaration", "Declaration", "n..16,6", None, "6292"),
            ("Invoice amount", "Total commercial invoice amount", "Declaration", "n..18,2", None, "5004"),
            ("Currency code", "ISO 4217 currency code for the declaration", "Declaration", "a3", "CL_004", "6345"),
            ("Acceptance date and time", "Date and time the declaration was accepted by customs", "Declaration", "an..14", None, "2380"),
            ("Registration number", "Sequential registration number assigned by customs", "Declaration", "an..20", None, "1004"),
            ("Declarant reference number", "Reference number assigned by the declarant", "Declaration", "an..35", None, "1004"),
            ("Specific circumstance indicator", "Code indicating special circumstances of the declaration", "Declaration", "an..3", None, "4441"),
            ("Total statistical value", "Total statistical value of goods in the declaration", "Declaration", "n..18,2", None, "6060"),
            ("Total duty amount", "Total customs duty assessed on the declaration", "Declaration", "n..18,2", None, "5004"),
            ("Number of items", "Total number of goods items in the declaration", "Declaration", "n..5", None, "1050"),
            ("Deferred payment indicator", "Indicates whether duty payment is deferred", "Declaration", "a1", None, "4441"),
            ("Place of declaration", "Location where the declaration is lodged", "Declaration", "an..35", None, "3227"),
            ("Goods declaration purpose code", "Code for the purpose of the goods declaration", "DeclarationGovernment", "an..3", None, "1001"),
            ("Previous procedure code", "Code of the previous customs procedure for the goods", "DeclarationGovernment", "an..4", None, "1001"),
            ("Requested procedure code", "Code of the requested customs procedure", "DeclarationGovernment", "an..4", None, "1001"),
            ("Government agency code", "Code identifying the responsible government agency", "DeclarationGovernment", "an..6", None, "9415"),
            ("Government procedure code", "Code identifying the government customs procedure (CPC)", "DeclarationGovernment", "an..7", None, "1001"),
            ("Additional procedure code", "Code for additional national procedure", "DeclarationGovernment", "an..3", None, "1001"),
            ("Amendment date", "Date on which the declaration amendment is requested", "Amendment", "an..8", None, "2380"),
            ("Amendment sequence number", "Sequential number of the amendment", "Amendment", "n..5", None, "1050"),
            ("Amendment accepted indicator", "Indicates whether the amendment was accepted", "Amendment", "a1", None, "4441"),
            ("Cancellation date", "Date the declaration cancellation was requested", "Cancellation", "an..8", None, "2380"),
            ("Cancellation reason code", "Code indicating the reason for cancellation", "Cancellation", "an..3", None, "4441"),
            ("Cancellation acceptance indicator", "Whether the cancellation request was accepted", "Cancellation", "a1", None, "4441"),
            ("Customs declaration document identifier", "Unique identifier for the customs declaration document", "CustomsDeclarationDocument", "an..35", None, "1004"),
            ("Customs declaration document type", "Type code for the customs declaration document", "CustomsDeclarationDocument", "an..3", None, "1001"),
            ("Simplified declaration indicator", "Indicates whether this is a simplified declaration", "Declaration", "a1", None, "4441"),
            ("Priority processing indicator", "Indicates whether priority processing is requested", "Declaration", "a1", None, "4441"),
            ("Warehouse entry number", "Entry number for warehousing declarations", "Declaration", "an..20", None, "1004"),
            ("Export licence number", "Number of the export licence if applicable", "Declaration", "an..20", None, "1004"),
            ("Import permit number", "Number of the import permit if applicable", "Declaration", "an..20", None, "1004"),
            ("Authentication code", "Electronic signature or authentication code", "Declaration", "an..35", None, "0534"),
            ("Supervising customs office", "Customs office supervising the procedure", "Declaration", "an..8", None, "3227"),
            ("Exit customs office", "Customs office of exit from the territory", "Declaration", "an..8", None, "3227"),
            ("Entry customs office", "Customs office of entry into the territory", "Declaration", "an..8", None, "3227"),
            ("Transit customs office", "Customs office of transit during transport", "Declaration", "an..8", None, "3227"),
            ("Destination customs office", "Customs office at the destination", "Declaration", "an..8", None, "3227"),
            ("Submission channel code", "Code for the channel through which the declaration was submitted", "Declaration", "an..3", None, "3153"),
            ("Representation type code", "Code indicating type of representation (direct/indirect)", "Declaration", "an..3", None, "3039"),
            ("Total CIF value", "Total cost, insurance and freight value", "Declaration", "n..18,2", None, "5004"),
            ("Total FOB value", "Total free on board value", "Declaration", "n..18,2", None, "5004"),
            ("Customs value total", "Total customs value of all items", "Declaration", "n..18,2", None, "5004"),
            ("Declaration version number", "Version number for amended declarations", "Declaration", "n..5", None, "1050"),
            ("Lodgement date time", "Date and time the declaration was electronically lodged", "Declaration", "an..14", None, "2380"),
            ("Release date time", "Date and time goods were released from customs", "Declaration", "an..14", None, "2380"),
            ("Assessment date time", "Date and time duty assessment was completed", "Declaration", "an..14", None, "2380"),
            ("Payment due date", "Date by which duties must be paid", "Declaration", "an..8", None, "2380"),
            ("Out of charge date", "Date goods were cleared out of customs charge", "Declaration", "an..8", None, "2380"),
            ("Customs value method code", "Code indicating the WTO valuation method used", "Declaration", "an..3", None, "5261"),
            ("Trade movement type", "Code for the type of trade movement (import/export/transit)", "Declaration", "an..3", None, "1001"),
            ("Total sales tax amount", "Total sales tax or VAT amount on the declaration", "Declaration", "n..18,2", None, "5004"),
            ("Total regulatory duty amount", "Total regulatory duty assessed", "Declaration", "n..18,2", None, "5004"),
            ("Total additional customs duty amount", "Total additional customs duty", "Declaration", "n..18,2", None, "5004"),
            ("Withholding tax amount", "Advance income tax amount withheld", "Declaration", "n..18,2", None, "5004"),
            ("Federal excise duty amount", "Total federal excise duty", "Declaration", "n..18,2", None, "5004"),
            ("Anti-dumping duty total", "Total anti-dumping duty assessed", "Declaration", "n..18,2", None, "5004"),
            ("Countervailing duty total", "Total countervailing duty assessed", "Declaration", "n..18,2", None, "5004"),
            ("SRO concession reference", "Reference to the SRO providing duty concession", "Declaration", "an..20", None, "1004"),
            ("FTA preference declaration", "Declaration of preferential treatment under FTA", "Declaration", "an..3", None, "4441"),
            ("Examination request indicator", "Indicates whether examination has been requested", "Declaration", "a1", None, "4441"),
            ("Selectivity channel assigned", "Risk channel assigned to the declaration (G/Y/R)", "Declaration", "a1", None, "4441"),
            ("Gate pass number", "Number of the gate pass for goods release", "Declaration", "an..20", None, "1004"),
            ("Examination completion date", "Date examination of goods was completed", "Declaration", "an..8", None, "2380"),
            ("Assessment officer code", "Code identifying the assessing customs officer", "Declaration", "an..10", None, "3039"),
            ("Appraiser officer code", "Code identifying the appraising officer", "Declaration", "an..10", None, "3039"),
            ("Principal appraiser code", "Code identifying the principal appraiser", "Declaration", "an..10", None, "3039"),
            ("First check indicator", "Whether first check (documentary) is complete", "Declaration", "a1", None, "4441"),
            ("Second check indicator", "Whether second check (physical) is complete", "Declaration", "a1", None, "4441"),
            ("WeBOC GD number", "WeBOC system-generated GD number", "Declaration", "an..20", None, "1004"),
            ("IGM reference number", "Import General Manifest reference number", "Declaration", "an..20", None, "1004"),
            ("Index number on IGM", "Line item index on the Import General Manifest", "Declaration", "n..5", None, "1050"),
            ("EGM reference number", "Export General Manifest reference number", "Declaration", "an..20", None, "1004"),
            ("GATT valuation indicator", "Indicates GATT Article VII valuation applicability", "Declaration", "a1", None, "4441"),
            ("Customs station code", "Code of the specific customs station", "Declaration", "an..6", None, "3227"),
            ("Collectorate code", "Code of the customs collectorate", "Declaration", "an..6", None, "3227"),
        ]
    },
    "Consignment": {
        "class_default": "Consignment",
        "elements": [
            ("Consignment identification", "An identifier for a separately identifiable collection of goods", "Consignment", "an..35", None, "1004"),
            ("Carrier assigned identifier", "Identifier assigned by the carrier to the consignment", "Consignment", "an..35", None, "1004"),
            ("Freight charge amount", "Total freight charges for the consignment", "Consignment", "n..18,2", None, "5004"),
            ("Associated transport document identifier", "Reference to the transport document covering the consignment", "AssociatedTransportDocument", "an..35", None, "1004"),
            ("Container indicator", "Indicates whether goods are transported in containers", "Consignment", "a1", None, "4441"),
            ("Consolidation indicator", "Indicates whether the consignment is consolidated", "ConsolidatedConsignment", "a1", None, "4441"),
            ("Total consignment value", "Total declared value of the consignment", "Consignment", "n..18,2", None, "5004"),
            ("Sequence number of consignment", "Sequential number within a multi-consignment declaration", "Consignment", "n..5", None, "1050"),
            ("Reference number of consignment", "Reference number for tracking the consignment", "Consignment", "an..35", None, "1004"),
            ("Consignment item quantity", "Number of items within the consignment", "ConsignmentItem", "n..5", None, "7224"),
            ("Insurance value amount", "Insurance value of the consignment", "Consignment", "n..18,2", None, "5004"),
            ("Insurance currency code", "Currency code for insurance value", "Consignment", "a3", "CL_004", "6345"),
            ("Freight currency code", "Currency of the freight charge", "Consignment", "a3", "CL_004", "6345"),
            ("Loading list reference", "Reference number of the loading list", "Consignment", "an..35", None, "1004"),
            ("Manifest reference number", "Reference to the cargo manifest", "Consignment", "an..35", None, "1004"),
            ("Master bill of lading number", "Number of the master bill of lading", "TransportContractDocument", "an..35", None, "1004"),
            ("House bill of lading number", "Number of the house bill of lading", "TransportContractDocument", "an..35", None, "1004"),
            ("Air waybill number", "Number of the air waybill", "TransportContractDocument", "an..35", None, "1004"),
            ("Master air waybill number", "Number of the master air waybill", "TransportContractDocument", "an..35", None, "1004"),
            ("Transport contract document type", "Type code of the transport contract document", "TransportContractDocument", "an..3", None, "1001"),
            ("Transport contract document date", "Date of issue of the transport contract document", "TransportContractDocument", "an..8", None, "2380"),
            ("Consignment gross mass", "Total gross weight of the consignment", "Consignment", "n..16,6", None, "6292"),
            ("Consignment net mass", "Total net weight of the consignment", "Consignment", "n..16,6", None, "6292"),
            ("Consignment volume", "Total volume of the consignment", "Consignment", "n..16,6", None, "6060"),
            ("Total package count", "Total number of packages in the consignment", "Consignment", "n..8", None, "7224"),
            ("Consignment classification code", "Code classifying the type of consignment", "Consignment", "an..3", None, "7357"),
            ("Place of loading", "Place where goods were loaded onto transport", "Consignment", "an..35", None, "3227"),
            ("Place of unloading", "Place where goods are to be unloaded", "Consignment", "an..35", None, "3227"),
            ("Place of delivery", "Place where goods are to be delivered", "Consignment", "an..35", None, "3227"),
            ("Country of dispatch", "Country from which the goods are dispatched", "Consignment", "a2", "CL_003", "3207"),
            ("Country of destination", "Country to which the goods are destined", "Consignment", "a2", "CL_003", "3207"),
            ("Country of first destination", "First destination country for transit goods", "Consignment", "a2", "CL_003", "3207"),
            ("Transit country code", "Country through which goods transit", "Consignment", "a2", "CL_003", "3207"),
            ("Consolidated cargo indicator", "Indicates less-than-container-load consolidation", "ConsolidatedConsignment", "a1", None, "4441"),
            ("Deconsolidation indicator", "Indicates deconsolidation at destination", "ConsolidatedConsignment", "a1", None, "4441"),
            ("Consignment special instruction", "Special handling instructions for the consignment", "Consignment", "an..256", None, "4440"),
            ("IGM line number", "Line item number on the Import General Manifest", "Consignment", "n..5", None, "1050"),
            ("Sub-line number on IGM", "Sub-line number for split consignments on IGM", "Consignment", "n..3", None, "1050"),
            ("Shipping line code", "Code identifying the shipping line", "Consignment", "an..17", None, "3039"),
            ("Voyage number", "Number identifying the voyage", "Consignment", "an..17", None, "8028"),
            ("Rotation number", "Vessel rotation number at port", "Consignment", "an..10", None, "1004"),
            ("NLC consignment note", "National Logistics Corporation consignment note reference", "Consignment", "an..20", None, "1004"),
            ("Rail wagon number", "Identification of the railway wagon", "Consignment", "an..17", None, "8260"),
            ("Delivery order number", "Number of the delivery order", "Consignment", "an..20", None, "1004"),
            ("Transshipment indicator", "Indicates whether transshipment is planned", "Consignment", "a1", None, "4441"),
            ("Transhipment port code", "UN/LOCODE of the transshipment port", "Consignment", "an..5", None, "3227"),
            ("Consignment remarks", "Free text remarks about the consignment", "Consignment", "an..512", None, "4440"),
            ("Freight payment method", "Code indicating who pays the freight", "Consignment", "an..3", None, "4215"),
            ("Container freight station", "Location of the container freight station", "Consignment", "an..35", None, "3227"),
            ("Estimated arrival date", "Estimated date of arrival at port", "Consignment", "an..8", None, "2380"),
            ("Actual arrival date", "Actual date of arrival at port", "Consignment", "an..8", None, "2380"),
            ("Bill of lading type code", "Type of bill of lading (original/express/seaway)", "TransportContractDocument", "an..3", None, "1001"),
            ("Number of originals", "Number of original B/L copies issued", "TransportContractDocument", "n..2", None, "1050"),
            ("Freight prepaid indicator", "Indicates freight is prepaid", "TransportContractDocument", "a1", None, "4441"),
            ("Freight collect indicator", "Indicates freight is to be collected at destination", "TransportContractDocument", "a1", None, "4441"),
            ("Associated document type code", "Type code of the associated transport document", "AssociatedTransportDocument", "an..3", None, "1001"),
            ("Associated document date", "Date of the associated transport document", "AssociatedTransportDocument", "an..8", None, "2380"),
            ("Associated document reference", "Reference number of the associated document", "AssociatedTransportDocument", "an..35", None, "1004"),
            ("Cargo type classification code", "Code classifying the type of cargo", "Consignment", "an..3", None, "7357"),
            ("CPEC corridor indicator", "Indicates shipment via CPEC corridor", "Consignment", "a1", None, "4441"),
            ("Afghan transit indicator", "Indicates Afghan Transit Trade Agreement goods", "Consignment", "a1", None, "4441"),
            ("Bonded carrier licence number", "Licence number of the bonded carrier", "Consignment", "an..20", None, "1004"),
            ("Customs transit number", "Transit document number (T1/T2/TIR)", "Consignment", "an..20", None, "1004"),
            ("Seal affixation indicator", "Indicates whether customs seals have been affixed", "Consignment", "a1", None, "4441"),
            ("Stuffing location", "Location where container was stuffed", "Consignment", "an..35", None, "3227"),
        ]
    },
    "Goods": {
        "class_default": "GoodsItem",
        "elements": [
            ("Goods description", "Free-text description of the goods", "GoodsItem", "an..512", None, "7002"),
            ("Commodity code (HS)", "Harmonized System code for tariff classification", "Classification", "an..18", "CL_023", "7357"),
            ("Statistical value", "Statistical value of goods for trade statistics", "GoodsItem", "n..18,2", None, "6060"),
            ("Net mass", "Net weight of goods excluding packaging", "GoodsMeasure", "n..16,6", None, "6292"),
            ("Gross mass", "Gross weight including packaging", "GoodsMeasure", "n..16,6", None, "6292"),
            ("Supplementary quantity", "Quantity in supplementary units specified in the tariff", "TariffQuantity", "n..16,6", None, "6060"),
            ("Tariff quantity", "Quantity used for tariff duty calculation", "TariffQuantity", "n..16,6", None, "6060"),
            ("Package type code", "UN/ECE Rec 21 code for the type of package", "Packaging", "an..3", "CL_006", "7065"),
            ("Number of packages", "Number of packages for the goods item", "Packaging", "n..8", None, "7224"),
            ("Marks and numbers", "Shipping marks and numbers on the packages", "Packaging", "an..512", None, "7102"),
            ("Country of origin code", "ISO country code of the origin of goods", "GoodsItem", "a2", "CL_003", "3239"),
            ("Preferential origin country", "Country qualifying for preferential tariff treatment", "GoodsItem", "a2", "CL_003", "3239"),
            ("Dangerous goods class", "UN/ADR class of dangerous goods", "DangerousGoods", "an..4", None, "8351"),
            ("UN dangerous goods number", "United Nations dangerous goods identification number", "DangerousGoods", "an..4", None, "8078"),
            ("Goods item number", "Sequential line item number within the declaration", "GoodsItem", "n..5", None, "1050"),
            ("Commodity code type", "Type of commodity classification system (HS/ECCN/CUS)", "Classification", "an..3", None, "7143"),
            ("National tariff line code", "National extension of HS code (8-digit Pakistan tariff)", "Classification", "an..18", None, "7357"),
            ("Additional tariff code", "Additional tariff classification code", "Classification", "an..4", None, "7357"),
            ("Preference code", "Code indicating the preferential duty rate applicable", "Classification", "an..6", None, "5273"),
            ("Quota order number", "Reference to a tariff quota allocation", "Classification", "an..20", None, "1004"),
            ("Anti-dumping duty indicator", "Indicates anti-dumping duty applicability", "Classification", "a1", None, "4441"),
            ("Goods measure unit code", "Unit of measure for the goods quantity", "GoodsMeasure", "an..3", None, "6411"),
            ("Goods volume", "Volume of the goods in cubic meters", "GoodsMeasure", "n..16,6", None, "6060"),
            ("Supplementary unit code", "Code for the supplementary unit of measure", "TariffQuantity", "an..3", None, "6411"),
            ("Dangerous goods flash point", "Flash point temperature of dangerous goods", "DangerousGoods", "n..6,1", None, "7419"),
            ("Dangerous goods packing group", "Packing group for dangerous goods (I/II/III)", "DangerousGoods", "an..3", None, "8339"),
            ("Emergency contact number", "Emergency contact for dangerous goods", "DangerousGoods", "an..35", None, "3148"),
            ("Packaging quantity", "Number of inner packages within outer packaging", "Packaging", "n..8", None, "7224"),
            ("Packaging material code", "Code for the material of the packaging", "Packaging", "an..3", None, "7065"),
            ("Package dimensions", "Dimensions of the package (L×W×H)", "Packaging", "an..35", None, "6060"),
            ("Additional information code", "Coded additional information about the goods", "AdditionalInformation", "an..5", None, "4441"),
            ("Additional information text", "Free-text additional information about the goods", "AdditionalInformation", "an..512", None, "4440"),
            ("Previous document type code", "Type of the previous customs document", "PreviousDocument", "an..3", None, "1001"),
            ("Previous document identifier", "Reference number of the previous document", "PreviousDocument", "an..35", None, "1004"),
            ("Previous document line item", "Line item number on the previous document", "PreviousDocument", "n..5", None, "1050"),
            ("Item CIF value", "Cost, insurance and freight value per item", "GoodsItem", "n..18,2", None, "5004"),
            ("Item FOB value", "Free on board value per item", "GoodsItem", "n..18,2", None, "5004"),
            ("Item customs value", "Customs value per item for duty calculation", "GoodsItem", "n..18,2", None, "5004"),
            ("Item duty amount", "Total duty amount for the goods item", "GoodsItem", "n..18,2", None, "5004"),
            ("Item sales tax amount", "Sales tax for the goods item", "GoodsItem", "n..18,2", None, "5004"),
            ("Item regulatory duty amount", "Regulatory duty for the goods item", "GoodsItem", "n..18,2", None, "5004"),
            ("Item withholding tax amount", "Withholding tax for the goods item", "GoodsItem", "n..18,2", None, "5004"),
            ("SRO number", "Statutory Regulatory Order granting concession", "GoodsItem", "an..20", None, "1004"),
            ("SRO serial number", "Serial number within the SRO", "GoodsItem", "n..5", None, "1050"),
            ("Concession certificate number", "Certificate number for the SRO concession", "GoodsItem", "an..35", None, "1004"),
            ("Unit price", "Price per unit of the goods", "GoodsItem", "n..18,6", None, "5004"),
            ("Quantity invoiced", "Quantity as stated on the commercial invoice", "GoodsItem", "n..16,6", None, "6060"),
            ("HS chapter code", "Two-digit HS chapter number", "Classification", "an..2", None, "7357"),
            ("HS heading code", "Four-digit HS heading number", "Classification", "an..4", None, "7357"),
            ("HS subheading code", "Six-digit HS subheading number", "Classification", "an..6", None, "7357"),
            ("PCT heading code", "Pakistan Customs Tariff heading code", "Classification", "an..12", None, "7357"),
            ("Brand name", "Brand or trade name of the goods", "GoodsItem", "an..70", None, "7008"),
            ("Model number", "Model or catalogue number of the goods", "GoodsItem", "an..35", None, "7008"),
            ("Technical specifications", "Technical specifications of the goods", "GoodsItem", "an..512", None, "4440"),
            ("Country of last processing", "Country where the goods were last processed", "GoodsItem", "a2", "CL_003", "3239"),
            ("Dual-use indicator", "Indicates goods are on the dual-use control list", "GoodsItem", "a1", None, "4441"),
            ("IPR indicator", "Indicates intellectual property rights relevance", "GoodsItem", "a1", None, "4441"),
            ("Valuation adjustment code", "Code for type of valuation adjustment applied", "GoodsItem", "an..3", None, "5261"),
            ("Valuation adjustment amount", "Amount of valuation adjustment", "GoodsItem", "n..18,2", None, "5004"),
            ("Royalty/licence fee indicator", "Indicates royalties or licence fees are payable", "GoodsItem", "a1", None, "4441"),
            ("Related party indicator", "Indicates buyer and seller are related parties", "GoodsItem", "a1", None, "4441"),
            ("Price influence indicator", "Indicates relationship influenced the transaction value", "GoodsItem", "a1", None, "4441"),
            ("Condition of sale restriction", "Describes conditions or restrictions on the sale", "GoodsItem", "an..256", None, "4440"),
            ("Proceeds of resale indicator", "Indicates proceeds of subsequent resale accrue to seller", "GoodsItem", "a1", None, "4441"),
            ("Goods condition code", "Condition of the goods (new/used/damaged)", "GoodsItem", "an..3", None, "7001"),
            ("Local clearing agent code", "Code of the local clearing agent handling the item", "GoodsItem", "an..17", None, "3039"),
            ("Examination result code", "Result of physical examination of the goods item", "GoodsItem", "an..3", None, "4441"),
            ("Lab test indicator", "Indicates whether lab testing is required", "GoodsItem", "a1", None, "4441"),
            ("Lab test result", "Result of laboratory testing", "GoodsItem", "an..256", None, "4440"),
            ("Value ruling reference", "Reference to a customs value ruling", "GoodsItem", "an..20", None, "1004"),
        ]
    },
    "Transport": {
        "class_default": "TransportMeans",
        "elements": [
            ("Transport means identification", "Identifier of the transport means (IMO, reg number)", "TransportMeans", "an..35", None, "8260"),
            ("Transport means nationality", "Country of registration of the transport means", "TransportMeans", "a2", "CL_003", "8281"),
            ("Mode of transport at border", "Mode of transport at the customs border crossing", "BorderTransportMeans", "an..2", "CL_005", "8067"),
            ("Inland mode of transport", "Mode of transport within the customs territory", "TransitTransportMeans", "an..2", "CL_005", "8067"),
            ("Container identification", "Identification number of the transport container", "TransportEquipment", "an..17", None, "8260"),
            ("Seal number", "Number of the seal affixed to transport equipment", "Seal", "an..35", None, "9308"),
            ("Container size and type code", "ISO 6346 code for container size and type", "TransportEquipment", "an..4", "CL_007", "8155"),
            ("Equipment identification number", "Identification of other transport equipment", "TransportEquipment", "an..17", None, "8260"),
            ("Voyage/flight number", "Number identifying the voyage or flight", "TransportMeans", "an..17", None, "8028"),
            ("Transport means type code", "Code for the type of transport means", "TransportMeans", "an..4", None, "8179"),
            ("Transport means name", "Name of the vessel, aircraft, or vehicle", "TransportMeans", "an..35", None, "8212"),
            ("Vessel IMO number", "International Maritime Organization number", "BorderTransportMeans", "n..7", None, "8260"),
            ("Aircraft registration", "Aircraft registration number", "BorderTransportMeans", "an..35", None, "8260"),
            ("Vehicle registration plate", "Registration plate number of the road vehicle", "BorderTransportMeans", "an..35", None, "8260"),
            ("Rail wagon number", "Identification number of the railway wagon", "TransitTransportMeans", "an..17", None, "8260"),
            ("Container status code", "Status of the container (full/empty/LCL)", "TransportEquipment", "an..3", None, "8169"),
            ("Container tare weight", "Empty weight of the container", "TransportEquipment", "n..16,6", None, "6292"),
            ("Container maximum gross weight", "Maximum gross weight capacity", "TransportEquipment", "n..16,6", None, "6292"),
            ("Seal type code", "Code indicating the type of seal", "Seal", "an..3", None, "9302"),
            ("Seal condition code", "Code indicating the condition of the seal", "Seal", "an..3", None, "9302"),
            ("Sealing party code", "Code identifying the party that affixed the seal", "Seal", "an..17", None, "3039"),
            ("Itinerary routing", "Planned routing of the transport", "Itinerary", "an..512", None, "8028"),
            ("Country of routing code", "Country codes along the transport route", "Itinerary", "a2", "CL_003", "3207"),
            ("Estimated departure date", "Estimated date of departure", "TransportEvent", "an..8", None, "2380"),
            ("Actual departure date", "Actual date of departure", "TransportEvent", "an..8", None, "2380"),
            ("Estimated arrival date at border", "Estimated date of arrival at customs border", "TransportEvent", "an..8", None, "2380"),
            ("Actual arrival date at border", "Actual date of arrival at customs border", "TransportEvent", "an..8", None, "2380"),
            ("Arrival transport means identification", "ID of the transport means on arrival", "ArrivalTransportMeans", "an..35", None, "8260"),
            ("Departure transport means identification", "ID of the transport means on departure", "DepartureTransportMeans", "an..35", None, "8260"),
            ("Mode of transport code at departure", "Mode of transport at departure", "DepartureTransportMeans", "an..2", "CL_005", "8067"),
            ("Mode of transport code at arrival", "Mode of transport at arrival", "ArrivalTransportMeans", "an..2", "CL_005", "8067"),
            ("Container temperature setting", "Required temperature for refrigerated containers", "TransportEquipment", "n..6,1", None, "6060"),
            ("Container humidity setting", "Required humidity for controlled atmosphere containers", "TransportEquipment", "n..3", None, "6060"),
            ("Container ventilation setting", "Ventilation setting for the container", "TransportEquipment", "n..3", None, "6060"),
            ("Equipment type qualifier", "Qualifier for the type of equipment", "TransportEquipment", "an..3", None, "8053"),
            ("Number of seals", "Total number of seals affixed", "TransportEquipment", "n..5", None, "9308"),
            ("GPS tracking identifier", "GPS tracking device identifier", "TransportEquipment", "an..35", None, "8260"),
            ("Driver licence number", "Licence number of the truck driver", "TransportMeans", "an..35", None, "8260"),
            ("Driver CNIC number", "National ID of the driver (Pakistan-specific)", "TransportMeans", "an..15", None, "3039"),
            ("Vehicle fitness certificate", "Fitness certificate number of the road vehicle", "TransportMeans", "an..20", None, "1004"),
            ("NLC tracking number", "National Logistics Corporation tracking reference", "TransportMeans", "an..20", None, "1004"),
            ("Cross-border transport document", "Document for cross-border transport (TIR/ATTA)", "TransportMeans", "an..35", None, "1004"),
            ("Transport agent code", "Code of the transport agent or forwarder", "TransportMeans", "an..17", None, "3039"),
            ("Port of loading code", "UN/LOCODE of the port of loading", "TransportEvent", "an..5", None, "3227"),
            ("Port of discharge code", "UN/LOCODE of the port of discharge", "TransportEvent", "an..5", None, "3227"),
            ("Port of transshipment code", "UN/LOCODE of the transshipment port", "TransportEvent", "an..5", None, "3227"),
            ("Border crossing point code", "Code of the land border crossing point", "TransportEvent", "an..5", None, "3227"),
            ("Terminal code", "Code identifying the port terminal", "TransportEvent", "an..6", None, "3227"),
            ("Berth number", "Berth number at the port terminal", "TransportEvent", "an..5", None, "3227"),
            ("Container yard code", "Code of the container yard", "TransportEquipment", "an..6", None, "3227"),
            ("Dwell time hours", "Hours the container has been at the terminal", "TransportEquipment", "n..8", None, "6060"),
            ("CPEC route identifier", "Identifier for the specific CPEC corridor route", "Itinerary", "an..10", None, "8028"),
            ("Karakoram Highway indicator", "Indicates transport via Karakoram Highway", "Itinerary", "a1", None, "4441"),
            ("Gwadar port indicator", "Indicates goods transiting through Gwadar port", "Itinerary", "a1", None, "4441"),
            ("Afghan transit flag", "Indicates goods in Afghan transit under ATTA", "TransportMeans", "a1", None, "4441"),
        ]
    },
}

ELEMENT_DEFS_2 = {
    "Party": {
        "class_default": "Party",
        "elements": [
            ("Party name", "Name of the trade party", "Party", "an..70", None, "3036"),
            ("Party identifier", "Unique identifier for the party (e.g., NTN, STRN)", "Party", "an..35", None, "3039"),
            ("Party function code", "Code indicating the role of the party", "Party", "an..3", None, "3035"),
            ("Street and number", "Street address including house/building number", "Party", "an..70", None, "3042"),
            ("City name", "Name of the city", "Party", "an..35", None, "3164"),
            ("Postcode identification", "Postal code", "Party", "an..9", None, "3251"),
            ("Country code", "ISO country code of the party", "Party", "a2", "CL_003", "3207"),
            ("Communication number", "Telephone, fax, or email of the party", "Party", "an..512", None, "3148"),
            ("Contact person name", "Name of the contact person", "Party", "an..35", None, "3412"),
            ("TIN/NTN number", "Tax Identification Number (Pakistan NTN)", "Party", "an..20", None, "3039"),
            ("DUNS number", "Dun & Bradstreet identifier", "Party", "an..13", None, "3039"),
            ("AEO authorization number", "Authorized Economic Operator authorization identifier", "Party", "an..35", None, "3039"),
            ("Agent identifier", "Identifier of the customs agent or broker", "Agent", "an..35", None, "3039"),
            ("Agent representative type", "Type of representation (direct/indirect)", "Agent", "an..3", None, "3035"),
            ("Agent licence number", "Licence number of the customs agent", "Agent", "an..20", None, "1004"),
            ("Buyer name", "Name of the buyer in the trade transaction", "Buyer", "an..70", None, "3036"),
            ("Buyer identifier", "Identifier of the buyer", "Buyer", "an..35", None, "3039"),
            ("Seller name", "Name of the seller", "Seller", "an..70", None, "3036"),
            ("Seller identifier", "Identifier of the seller", "Seller", "an..35", None, "3039"),
            ("Consignor name", "Name of the consignor (shipper)", "Consignor", "an..70", None, "3036"),
            ("Consignor identifier", "Identifier of the consignor", "Consignor", "an..35", None, "3039"),
            ("Consignee name", "Name of the consignee (receiver)", "Consignee", "an..70", None, "3036"),
            ("Consignee identifier", "Identifier of the consignee", "Consignee", "an..35", None, "3039"),
            ("Declarant name", "Name of the declarant", "Declarant", "an..70", None, "3036"),
            ("Declarant identifier", "Identifier of the declarant (NTN in Pakistan)", "Declarant", "an..35", None, "3039"),
            ("Carrier name", "Name of the carrier", "Carrier", "an..70", None, "3036"),
            ("Carrier identifier", "Identifier of the carrier (shipping line code, airline code)", "Carrier", "an..35", None, "3039"),
            ("Customs broker name", "Name of the customs broker", "CustomsBroker", "an..70", None, "3036"),
            ("Customs broker identifier", "Identifier of the customs broker", "CustomsBroker", "an..35", None, "3039"),
            ("Customs broker licence number", "Licence number of the customs broker", "CustomsBroker", "an..20", None, "1004"),
            ("Importer name", "Name of the importer of record", "Importer", "an..70", None, "3036"),
            ("Importer identifier", "Identifier of the importer", "Importer", "an..35", None, "3039"),
            ("Exporter name", "Name of the exporter", "Exporter", "an..70", None, "3036"),
            ("Exporter identifier", "Identifier of the exporter", "Exporter", "an..35", None, "3039"),
            ("Manufacturer name", "Name of the manufacturer of the goods", "Manufacturer", "an..70", None, "3036"),
            ("Manufacturer identifier", "Identifier of the manufacturer", "Manufacturer", "an..35", None, "3039"),
            ("Manufacturer address", "Address of the manufacturer", "Manufacturer", "an..256", None, "3042"),
            ("Notify party name", "Name of the party to be notified", "NotifyParty", "an..70", None, "3036"),
            ("Notify party identifier", "Identifier of the notify party", "NotifyParty", "an..35", None, "3039"),
            ("Freight forwarder name", "Name of the freight forwarder", "FreightForwarder", "an..70", None, "3036"),
            ("Freight forwarder identifier", "Identifier of the freight forwarder", "FreightForwarder", "an..35", None, "3039"),
            ("Warehouse keeper name", "Name of the warehouse operator", "WarehouseKeeper", "an..70", None, "3036"),
            ("Warehouse keeper identifier", "Identifier of the warehouse operator", "WarehouseKeeper", "an..35", None, "3039"),
            ("Party CNIC number", "Computerized National Identity Card number", "Party", "an..15", None, "3039"),
            ("Party STRN", "Sales Tax Registration Number", "Party", "an..13", None, "3039"),
            ("Party email address", "Email address of the party", "Party", "an..256", None, "3148"),
            ("Party phone number", "Phone number of the party", "Party", "an..20", None, "3148"),
            ("Registered address", "Registered office address", "Party", "an..256", None, "3042"),
            ("Province/state code", "Province or state code of the party address", "Party", "an..9", None, "3229"),
            ("WeBOC user identifier", "User ID in WeBOC system", "Party", "an..20", None, "3039"),
        ]
    },
    "Location": {
        "class_default": "Location",
        "elements": [
            ("Location identifier (UN/LOCODE)", "UN/LOCODE identifying the location", "Location", "an..5", None, "3227"),
            ("Location function code", "Code indicating the function of the location", "Location", "an..3", None, "3227"),
            ("Country code of location", "ISO country code of the location", "Location", "a2", "CL_003", "3207"),
            ("Country sub-entity code", "Province/state code within the country", "Location", "an..9", None, "3229"),
            ("Loading location name", "Name of the place of loading", "LoadingLocation", "an..256", None, "3036"),
            ("Loading location UN/LOCODE", "UN/LOCODE of the loading location", "LoadingLocation", "an..5", None, "3227"),
            ("Unloading location name", "Name of the place of unloading", "UnloadingLocation", "an..256", None, "3036"),
            ("Unloading location UN/LOCODE", "UN/LOCODE of the unloading location", "UnloadingLocation", "an..5", None, "3227"),
            ("Place of delivery name", "Name of the delivery location", "Location", "an..256", None, "3036"),
            ("Port of discharge name", "Name of the port of discharge", "Location", "an..256", None, "3036"),
            ("Port of discharge UN/LOCODE", "UN/LOCODE of the port of discharge", "Location", "an..5", None, "3227"),
            ("First port of entry name", "Name of the first port of entry", "EntryPort", "an..256", None, "3036"),
            ("First port of entry UN/LOCODE", "UN/LOCODE of the first port of entry", "EntryPort", "an..5", None, "3227"),
            ("Exit port name", "Name of the exit port", "ExitPort", "an..256", None, "3036"),
            ("Exit port UN/LOCODE", "UN/LOCODE of the exit port", "ExitPort", "an..5", None, "3227"),
            ("Customs office code", "Code identifying the customs office", "CustomsOffice", "an..8", None, "3227"),
            ("Customs office name", "Name of the customs office", "CustomsOffice", "an..70", None, "3036"),
            ("Destination country code", "ISO code of the destination country", "DestinationCountry", "a2", "CL_003", "3207"),
            ("Destination country name", "Name of the destination country", "DestinationCountry", "an..35", None, "3036"),
            ("Port of loading name", "Name of the port of loading", "LoadingLocation", "an..256", None, "3036"),
            ("Port of loading UN/LOCODE", "UN/LOCODE of the port of loading", "LoadingLocation", "an..5", None, "3227"),
            ("Place of acceptance name", "Place where goods are accepted for transport", "Location", "an..256", None, "3036"),
            ("Place of acceptance code", "Code for the place of acceptance", "Location", "an..5", None, "3227"),
            ("Region code", "Code for the economic region or trade zone", "Location", "an..9", None, "3229"),
            ("SEZ identifier", "Special Economic Zone identifier (CPEC SEZs)", "Location", "an..10", None, "3227"),
            ("Free zone identifier", "Identifier for the free zone", "Location", "an..10", None, "3227"),
            ("Dry port identifier", "Identifier for the inland dry port", "Location", "an..10", None, "3227"),
            ("Collectorate name", "Name of the customs collectorate", "CustomsOffice", "an..70", None, "3036"),
            ("Customs station name", "Name of the customs station", "CustomsOffice", "an..70", None, "3036"),
            ("Warehouse location code", "Code for the bonded warehouse location", "Location", "an..10", None, "3227"),
            ("GPS latitude", "Latitude coordinate of the location", "Location", "an..12", None, "6060"),
            ("GPS longitude", "Longitude coordinate of the location", "Location", "an..12", None, "6060"),
            ("Pakistan port code", "FBR-assigned port code for Pakistan", "Location", "an..6", None, "3227"),
            ("Gwadar zone code", "Zone code within Gwadar Free Zone", "Location", "an..5", None, "3227"),
            ("CPEC SEZ name", "Name of the CPEC Special Economic Zone", "Location", "an..70", None, "3036"),
            ("Border crossing name", "Name of the land border crossing", "Location", "an..70", None, "3036"),
            ("Terminal operator code", "Code of the terminal operating company", "Location", "an..17", None, "3039"),
            ("Berth/gate number", "Specific berth or gate number at port/airport", "Location", "an..5", None, "3227"),
            ("Container yard location", "Location identifier of the container yard", "Location", "an..35", None, "3227"),
            ("Examination hall code", "Code of the customs examination hall", "Location", "an..6", None, "3227"),
        ]
    },
    "Financial": {
        "class_default": "CustomsValuation",
        "elements": [
            ("Customs value", "Value determined under WTO Agreement on Customs Valuation", "CustomsValuation", "n..18,2", None, "5004"),
            ("Value declared for customs", "Value as declared by the importer", "CustomsValuation", "n..18,2", None, "5004"),
            ("Duty/tax/fee type code", "Code identifying the type of duty, tax, or fee", "DutyTaxFee", "an..3", None, "5153"),
            ("Duty/tax/fee amount", "Monetary amount of the assessed duty, tax, or fee", "DutyTaxFee", "n..18,2", None, "5004"),
            ("Duty/tax/fee rate", "Rate percentage of the duty, tax, or fee", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Payment method code", "Code indicating the method of duty payment", "Payment", "an..3", None, "4461"),
            ("Guarantee type code", "Code for the type of financial guarantee", "ObligationGuarantee", "an..3", None, "4441"),
            ("Guarantee reference number", "Reference number of the guarantee", "ObligationGuarantee", "an..35", None, "1004"),
            ("Guarantee amount", "Monetary amount of the guarantee", "ObligationGuarantee", "n..18,2", None, "5004"),
            ("Exchange rate", "Currency exchange rate applied", "ExchangeRate", "n..12,5", None, "5402"),
            ("Currency code for duties", "Currency in which duties are assessed", "DutyTaxFee", "a3", "CL_004", "6345"),
            ("Total taxes paid amount", "Total amount of all duties and taxes paid", "Payment", "n..18,2", None, "5004"),
            ("Valuation method code", "WTO valuation method code (1-6)", "CustomsValuation", "an..3", None, "5261"),
            ("Transaction value", "Price actually paid or payable", "CustomsValuation", "n..18,2", None, "5004"),
            ("Insurance cost", "Insurance cost to be added to customs value", "CustomsValuation", "n..18,2", None, "5004"),
            ("Freight cost", "Freight cost to be added to customs value", "CustomsValuation", "n..18,2", None, "5004"),
            ("Adjustment amount", "Valuation adjustment amount (additions/deductions)", "CustomsValuation", "n..18,2", None, "5004"),
            ("Royalty/licence fee amount", "Amount of royalties or licence fees", "CustomsValuation", "n..18,2", None, "5004"),
            ("Customs duty rate", "Rate of customs duty applied", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Regulatory duty rate", "Rate of regulatory duty applied (Pakistan-specific)", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Additional customs duty rate", "Rate of additional customs duty", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Sales tax rate", "Rate of sales tax (18% standard in Pakistan)", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Withholding tax rate", "Rate of advance income tax withheld", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Federal excise duty rate", "Rate of federal excise duty", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Anti-dumping duty rate", "Rate of anti-dumping duty", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Countervailing duty rate", "Rate of countervailing duty", "DutyTaxFee", "n..7,3", None, "5278"),
            ("Total duty liability", "Total duty liability for the declaration", "Payment", "n..18,2", None, "5004"),
            ("Payment receipt number", "Receipt number for duty payment", "Payment", "an..35", None, "1004"),
            ("Payment date", "Date of duty payment", "Payment", "an..8", None, "2380"),
            ("Payment channel code", "Channel through which payment was made (online/bank/POS)", "Payment", "an..3", None, "4461"),
            ("Bank name", "Name of the bank for payment/guarantee", "BankAccount", "an..70", None, "3036"),
            ("Bank account number", "Bank account number", "BankAccount", "an..35", None, "3194"),
            ("Bank branch code", "Branch code of the bank", "BankAccount", "an..11", None, "3433"),
            ("LC number", "Letter of credit number", "TradeFinanceDocument", "an..35", None, "1004"),
            ("LC amount", "Amount of the letter of credit", "TradeFinanceDocument", "n..18,2", None, "5004"),
            ("LC expiry date", "Expiry date of the letter of credit", "TradeFinanceDocument", "an..8", None, "2380"),
            ("Accounting entry identifier", "Unique identifier for the accounting entry", "AccountingEntry", "an..35", None, "1004"),
            ("Accounting entry date", "Date of the accounting entry", "AccountingEntry", "an..8", None, "2380"),
            ("Refund amount", "Amount of duty refund", "Payment", "n..18,2", None, "5004"),
            ("Refund reference number", "Reference number for the refund", "Payment", "an..35", None, "1004"),
            ("Drawback amount", "Amount of duty drawback claimed", "Payment", "n..18,2", None, "5004"),
            ("PKR exchange rate", "Exchange rate to Pakistani Rupee (SBP rate)", "ExchangeRate", "n..12,5", None, "5402"),
            ("Exchange rate date", "Date for which the exchange rate applies", "ExchangeRate", "an..8", None, "2380"),
            ("Guarantee validity period", "Period for which the guarantee is valid", "ObligationGuarantee", "an..35", None, "2380"),
            ("Bond number", "Customs bond number", "ObligationGuarantee", "an..35", None, "1004"),
        ]
    },
    "Document": {
        "class_default": "AdditionalDocument",
        "elements": [
            ("Additional document type code", "Code for the type of additional document", "AdditionalDocument", "an..3", None, "1001"),
            ("Document reference number", "Reference number of the document", "AdditionalDocument", "an..35", None, "1004"),
            ("Document date", "Date of issuance of the document", "AdditionalDocument", "an..8", None, "2380"),
            ("Document status code", "Code indicating the status of the document", "AdditionalDocument", "an..3", None, "1373"),
            ("Document issuing authority", "Name of the authority that issued the document", "AdditionalDocument", "an..70", None, "3036"),
            ("Line item number on document", "Reference to a line item on the document", "AdditionalDocument", "n..5", None, "1050"),
            ("Attached document binary", "Base64-encoded binary content of an attached document", "AdditionalDocument", "an..unlimited", None, "7008"),
            ("Certificate type code", "Type of certificate (origin, health, conformity)", "Certificate", "an..3", None, "1001"),
            ("Certificate number", "Number of the certificate", "Certificate", "an..35", None, "1004"),
            ("Certificate date of issue", "Date the certificate was issued", "Certificate", "an..8", None, "2380"),
            ("Certificate expiry date", "Expiry date of the certificate", "Certificate", "an..8", None, "2380"),
            ("Certificate issuing authority", "Authority that issued the certificate", "Certificate", "an..70", None, "3036"),
            ("Licence type code", "Type of import/export licence", "License", "an..3", None, "1001"),
            ("Licence number", "Number of the licence", "License", "an..35", None, "1004"),
            ("Licence validity date", "Validity period of the licence", "License", "an..8", None, "2380"),
            ("Permit type code", "Type of regulatory permit", "Permit", "an..3", None, "1001"),
            ("Permit number", "Number of the permit", "Permit", "an..35", None, "1004"),
            ("Permit issuing OGA", "Other Government Agency that issued the permit", "Permit", "an..70", None, "3036"),
            ("Commercial invoice number", "Number of the commercial invoice", "Invoice", "an..35", None, "1004"),
            ("Commercial invoice date", "Date of the commercial invoice", "Invoice", "an..8", None, "2380"),
            ("Commercial invoice amount", "Total amount on the commercial invoice", "Invoice", "n..18,2", None, "5004"),
            ("Packing list number", "Number of the packing list", "PackingList", "an..35", None, "1004"),
            ("Bill of lading number", "Number of the bill of lading", "BillOfLading", "an..35", None, "1004"),
            ("Bill of lading date", "Date of the bill of lading", "BillOfLading", "an..8", None, "2380"),
            ("Bill of lading type", "Type of bill of lading", "BillOfLading", "an..3", None, "1001"),
            ("Air waybill number (document)", "Number of the air waybill", "AirWaybill", "an..35", None, "1004"),
            ("Air waybill date", "Date of the air waybill", "AirWaybill", "an..8", None, "2380"),
            ("Insurance policy number", "Number of the cargo insurance policy", "InsuranceDocument", "an..35", None, "1004"),
            ("Insurance company name", "Name of the insurance company", "InsuranceDocument", "an..70", None, "3036"),
            ("PSW document reference", "Pakistan Single Window document reference", "AdditionalDocument", "an..35", None, "1004"),
            ("OGA clearance reference", "OGA clearance reference number from PSW", "AdditionalDocument", "an..35", None, "1004"),
            ("Phytosanitary certificate number", "DPP phytosanitary certificate number", "Certificate", "an..35", None, "1004"),
            ("Drug regulatory certificate", "DRAP certificate for pharmaceutical imports", "Certificate", "an..35", None, "1004"),
            ("PSQCA certificate number", "Pakistan Standards quality certificate", "Certificate", "an..35", None, "1004"),
            ("Radiation certificate number", "PNRA radiation safety certificate", "Certificate", "an..35", None, "1004"),
        ]
    },
    "Classification": {
        "class_default": "HarmonizedSystem",
        "elements": [
            ("Commodity classification code (HS6)", "Six-digit HS code for commodity classification", "HarmonizedSystem", "an..6", "CL_023", "7357"),
            ("Commodity classification type", "Type of classification system used (HS/ECCN/CUS)", "HarmonizedSystem", "an..3", None, "7143"),
            ("National tariff line code", "National extension beyond HS (8+ digits)", "NationalTariffLine", "an..18", None, "7357"),
            ("Additional tariff code", "Additional tariff code for national specifics", "NationalTariffLine", "an..4", None, "7357"),
            ("Preference code", "Code indicating preferential tariff treatment", "PreferenceCode", "an..6", None, "5273"),
            ("Quota order number", "Reference to a tariff quota", "QuotaAllocation", "an..20", None, "1004"),
            ("Anti-dumping duty indicator", "Whether anti-dumping measures apply", "NationalTariffLine", "a1", None, "4441"),
            ("HS version year", "Year version of the HS nomenclature", "HarmonizedSystem", "an..4", None, "7143"),
            ("HS chapter description", "Description of the HS chapter", "HarmonizedSystem", "an..256", None, "7002"),
            ("HS heading description", "Description of the HS heading", "HarmonizedSystem", "an..256", None, "7002"),
            ("HS subheading description", "Description of the HS subheading", "HarmonizedSystem", "an..256", None, "7002"),
            ("National tariff description", "Description at the national tariff level", "NationalTariffLine", "an..256", None, "7002"),
            ("Statutory duty rate", "Statutory customs duty rate per tariff", "NationalTariffLine", "n..7,3", None, "5278"),
            ("Applied duty rate", "Actual duty rate applied (may differ due to SRO)", "NationalTariffLine", "n..7,3", None, "5278"),
            ("Preference certificate reference", "Reference to the preferential origin certificate", "PreferenceCode", "an..35", None, "1004"),
            ("FTA code", "Code of the applicable free trade agreement", "PreferenceCode", "an..10", None, "5273"),
            ("Quota balance", "Remaining quota allocation available", "QuotaAllocation", "n..18,2", None, "6060"),
            ("Quota period", "Period for which the quota applies", "QuotaAllocation", "an..17", None, "2380"),
            ("Import restriction code", "Code of the applicable import restriction", "Restriction", "an..3", None, "4441"),
            ("Export control code", "Export control classification (strategic goods)", "Restriction", "an..10", None, "4441"),
            ("Prohibited goods indicator", "Indicates goods are on the prohibited list", "Restriction", "a1", None, "4441"),
            ("Restricted goods indicator", "Indicates goods are on the restricted list", "Restriction", "a1", None, "4441"),
            ("SRO applicability code", "Code of the applicable SRO for concessionary duty", "NationalTariffLine", "an..10", None, "1004"),
            ("Fifth Schedule applicability", "Applicability under Fifth Schedule of Customs Act", "NationalTariffLine", "a1", None, "4441"),
            ("Customs Act section reference", "Reference to the relevant Customs Act section", "NationalTariffLine", "an..10", None, "1004"),
            ("ATIC classification", "Afghanistan-Transit International Customs classification", "NationalTariffLine", "an..10", None, "7357"),
            ("Binding tariff information ref", "Reference to binding tariff ruling", "HarmonizedSystem", "an..35", None, "1004"),
            ("Classification ruling date", "Date of the classification ruling", "HarmonizedSystem", "an..8", None, "2380"),
            ("PCT statistical suffix", "Pakistan Customs Tariff statistical suffix", "NationalTariffLine", "an..4", None, "7357"),
            ("Regulatory duty SRO reference", "SRO reference for regulatory duty", "NationalTariffLine", "an..20", None, "1004"),
        ]
    },
    "Risk & Control": {
        "class_default": "RiskAssessment",
        "elements": [
            ("Examination type code", "Code for the type of customs examination", "ExaminationNotice", "an..3", None, "4441"),
            ("Examination result code", "Code indicating the outcome of examination", "ExaminationResult", "an..3", None, "4441"),
            ("Seal number (control)", "Number of the seal for customs control", "RiskAssessment", "an..35", None, "9308"),
            ("Seal condition code (control)", "Condition of the seal upon examination", "RiskAssessment", "an..3", None, "9302"),
            ("Government procedure code (control)", "Customs procedure code for goods control", "GovernmentProcedure", "an..7", None, "1001"),
            ("Risk assessment indicator", "Code indicating the risk level of the declaration", "RiskAssessment", "an..3", None, "4441"),
            ("Selectivity channel code", "Risk channel assigned (G=Green, Y=Yellow, R=Red)", "Selectivity", "a1", None, "4441"),
            ("Examination location code", "Location where examination is to be performed", "ExaminationNotice", "an..35", None, "3227"),
            ("Risk score value", "Numerical risk score assigned by the system", "RiskAssessment", "n..5", None, "6060"),
            ("Risk rule identifier", "ID of the risk rule that triggered selection", "Selectivity", "an..20", None, "1004"),
            ("Risk category code", "Category of risk identified", "RiskAssessment", "an..3", None, "4441"),
            ("Intelligence reference", "Reference to intelligence information", "RiskAssessment", "an..35", None, "1004"),
            ("Examination officer code", "Code of the examining officer", "ExaminationNotice", "an..10", None, "3039"),
            ("Examination date", "Date of the examination", "ExaminationNotice", "an..8", None, "2380"),
            ("Examination start time", "Start time of the examination", "ExaminationNotice", "an..4", None, "2380"),
            ("Examination end time", "End time of the examination", "ExaminationResult", "an..4", None, "2380"),
            ("Discrepancy indicator", "Indicates whether discrepancies were found", "ExaminationResult", "a1", None, "4441"),
            ("Discrepancy description", "Description of discrepancies found", "ExaminationResult", "an..512", None, "4440"),
            ("Seizure indicator", "Indicates whether goods were seized", "ExaminationResult", "a1", None, "4441"),
            ("Seizure report reference", "Reference to the seizure report", "ExaminationResult", "an..35", None, "1004"),
            ("Penalty assessment indicator", "Indicates whether a penalty was assessed", "RiskAssessment", "a1", None, "4441"),
            ("Penalty amount", "Amount of penalty assessed", "RiskAssessment", "n..18,2", None, "5004"),
            ("Post-clearance audit indicator", "Indicates selection for post-clearance audit", "RiskAssessment", "a1", None, "4441"),
            ("NTC alert indicator", "National Targeting Centre alert flag", "RiskAssessment", "a1", None, "4441"),
            ("Trader risk category", "Risk category assigned to the trader", "Selectivity", "an..3", None, "4441"),
        ]
    },
    "Origin": {
        "class_default": "CertificateOfOrigin",
        "elements": [
            ("Country of origin code (origin)", "ISO code of the country where goods originated", "CertificateOfOrigin", "a2", "CL_003", "3239"),
            ("Preferential treatment code", "Code for the type of preferential treatment claimed", "PreferentialTreatment", "an..3", None, "5273"),
            ("Origin criterion code", "Code indicating which origin criterion is satisfied", "RulesOfOrigin", "an..3", None, "5273"),
            ("Certificate of origin number", "Number of the certificate of origin", "CertificateOfOrigin", "an..35", None, "1004"),
            ("Certificate of origin date", "Date of issue of the certificate of origin", "CertificateOfOrigin", "an..8", None, "2380"),
            ("Origin declaration reference", "Reference number of the origin self-declaration", "OriginDeclaration", "an..35", None, "1004"),
            ("Regional value content percentage", "Percentage of regional value content", "RegionalValueContent", "n..5,2", None, "5482"),
            ("Change in tariff classification indicator", "Indicates CTC origin criterion is met", "RulesOfOrigin", "a1", None, "4441"),
            ("FTA agreement code", "Code of the applicable free trade agreement", "PreferentialTreatment", "an..10", None, "5273"),
            ("FTA preference rate", "Preferential duty rate under the FTA", "PreferentialTreatment", "n..7,3", None, "5278"),
            ("Certificate of origin issuing body", "Organization that issued the certificate", "CertificateOfOrigin", "an..70", None, "3036"),
            ("Certificate of origin expiry date", "Expiry date of the certificate of origin", "CertificateOfOrigin", "an..8", None, "2380"),
            ("Origin verification status", "Status of origin verification (pending/verified/rejected)", "CertificateOfOrigin", "an..3", None, "4441"),
            ("Cumulation type code", "Type of cumulation applied (bilateral/diagonal/full)", "CumulationRule", "an..3", None, "5273"),
            ("Cumulation partner country", "Partner country for cumulation", "CumulationRule", "a2", "CL_003", "3207"),
            ("Wholly obtained indicator", "Indicates goods are wholly obtained in the origin country", "RulesOfOrigin", "a1", None, "4441"),
            ("Sufficient processing indicator", "Indicates goods underwent sufficient processing", "RulesOfOrigin", "a1", None, "4441"),
            ("De minimis tolerance indicator", "Indicates de minimis tolerance is applied", "RulesOfOrigin", "a1", None, "4441"),
            ("Product-specific rule reference", "Reference to product-specific origin rule", "RulesOfOrigin", "an..35", None, "1004"),
            ("Origin declaration text", "Text of the origin self-declaration", "OriginDeclaration", "an..512", None, "4440"),
            ("Approved exporter authorization", "Authorization number of the approved exporter", "OriginDeclaration", "an..35", None, "3039"),
            ("Manufacturer declaration indicator", "Whether manufacturer declaration accompanies the CO", "CertificateOfOrigin", "a1", None, "4441"),
            ("Back-to-back CO indicator", "Indicates a back-to-back certificate of origin", "CertificateOfOrigin", "a1", None, "4441"),
            ("Third-country invoicing indicator", "Indicates invoice issued by a third country party", "CertificateOfOrigin", "a1", None, "4441"),
            ("GSP Plus eligibility indicator", "Indicates eligibility for EU GSP+ preference", "PreferentialTreatment", "a1", None, "4441"),
            ("CPFTA-II preference indicator", "Indicates China-Pakistan FTA Phase 2 preference", "PreferentialTreatment", "a1", None, "4441"),
            ("SAFTA preference indicator", "Indicates SAFTA preferential treatment", "PreferentialTreatment", "a1", None, "4441"),
            ("D-8 PTA preference indicator", "Indicates D-8 preferential tariff treatment", "PreferentialTreatment", "a1", None, "4441"),
            ("ECO TPA preference indicator", "Indicates ECO trade preferential agreement", "PreferentialTreatment", "a1", None, "4441"),
            ("Regional value content method", "Method used to calculate RVC (build-up/build-down)", "RegionalValueContent", "an..3", None, "5261"),
        ]
    },
    "Warehouse": {
        "class_default": "Warehouse",
        "elements": [
            ("Warehouse identifier", "Unique identifier for the bonded warehouse", "Warehouse", "an..35", None, "3227"),
            ("Warehouse type code", "Code indicating the type of warehouse", "Warehouse", "an..3", None, "3227"),
            ("Bonded warehouse type", "Type of bonded warehouse (public/private/special)", "CustomsBondedArea", "an..3", None, "3227"),
            ("Storage period days", "Number of days goods may be stored", "Warehouse", "n..5", None, "6060"),
            ("Warehouse entry number", "Entry number for goods entering the warehouse", "Warehouse", "an..35", None, "1004"),
            ("Free zone identifier", "Identifier for the free trade zone", "FreeZone", "an..10", None, "3227"),
            ("Temporary storage declaration ref", "Reference to temporary storage declaration", "TemporaryStorage", "an..35", None, "1004"),
            ("Warehouse stock quantity", "Current quantity of goods in the warehouse", "Warehouse", "n..16,6", None, "6060"),
            ("Warehouse stock value", "Current value of goods in the warehouse", "Warehouse", "n..18,2", None, "5004"),
            ("Warehouse licence number", "Licence number of the warehouse operator", "Warehouse", "an..35", None, "1004"),
            ("Free zone operator code", "Code of the free zone operator", "FreeZone", "an..17", None, "3039"),
            ("Free zone activity type", "Type of activity in the free zone (manufacturing/trading/storage)", "FreeZone", "an..3", None, "4441"),
            ("Temporary storage period", "Maximum period for temporary storage (days)", "TemporaryStorage", "n..3", None, "6060"),
            ("Temporary storage location", "Location of temporary storage facility", "TemporaryStorage", "an..35", None, "3227"),
            ("Inward processing authorization", "Authorization number for inward processing", "InwardProcessing", "an..35", None, "1004"),
            ("Inward processing period", "Authorized period for inward processing", "InwardProcessing", "n..5", None, "6060"),
            ("Outward processing authorization", "Authorization number for outward processing", "OutwardProcessing", "an..35", None, "1004"),
            ("Outward processing period", "Authorized period for outward processing", "OutwardProcessing", "n..5", None, "6060"),
            ("Bonded manufacturing licence", "Licence for manufacturing in bond", "CustomsBondedArea", "an..35", None, "1004"),
            ("EFS authorization number", "Export Facilitation Scheme authorization", "InwardProcessing", "an..35", None, "1004"),
            ("DTRE licence number", "Duty & Tax Remission for Exports licence", "InwardProcessing", "an..35", None, "1004"),
            ("Manufacturing bond number", "Bond number for bonded manufacturing", "CustomsBondedArea", "an..35", None, "1004"),
            ("Warehousing date", "Date goods were placed in the warehouse", "Warehouse", "an..8", None, "2380"),
            ("Ex-bond date", "Date goods were released from the warehouse", "Warehouse", "an..8", None, "2380"),
            ("Stock rotation indicator", "Indicates FIFO/LIFO stock rotation method", "Warehouse", "an..3", None, "4441"),
        ]
    },
    "E-Commerce": {
        "class_default": "ECommerceItem",
        "elements": [
            ("De minimis value", "Value threshold for simplified clearance", "DeMinimisDeclaration", "n..18,2", None, "5004"),
            ("E-commerce indicator", "Indicates goods sold through e-commerce", "ECommerceItem", "a1", None, "4441"),
            ("Platform identifier", "Identifier of the e-commerce platform", "ECommerceItem", "an..35", None, "3039"),
            ("Buyer/seller marketplace ID", "Marketplace account ID of buyer or seller", "ECommerceItem", "an..35", None, "3039"),
            ("Return goods indicator", "Indicates return of previously purchased goods", "ReturnGoods", "a1", None, "4441"),
            ("Simplified declaration indicator (e-comm)", "Indicates simplified e-commerce declaration", "SimplifiedDeclaration", "a1", None, "4441"),
            ("Unique shipment reference (e-comm)", "Unique reference for the e-commerce shipment", "ECommerceItem", "an..35", None, "1004"),
            ("Platform name", "Name of the e-commerce platform", "ECommerceItem", "an..70", None, "3036"),
            ("Order number", "E-commerce order number", "ECommerceItem", "an..35", None, "1004"),
            ("Order date", "Date of the e-commerce order", "ECommerceItem", "an..8", None, "2380"),
            ("Payment method (e-comm)", "Payment method used for the online purchase", "ECommerceItem", "an..3", None, "4461"),
            ("URL of goods listing", "URL of the product listing on the platform", "ECommerceItem", "an..512", None, "7008"),
            ("Postal item number", "Tracking number for postal shipments", "PostalItem", "an..35", None, "1004"),
            ("Postal service provider", "Name of the postal service", "PostalItem", "an..70", None, "3036"),
            ("Courier tracking number", "Tracking number for courier shipments", "CourierShipment", "an..35", None, "1004"),
            ("Courier company name", "Name of the courier company", "CourierShipment", "an..70", None, "3036"),
            ("Return reason code", "Code indicating reason for return", "ReturnGoods", "an..3", None, "4441"),
            ("Original export declaration ref", "Reference to the original export declaration", "ReturnGoods", "an..35", None, "1004"),
            ("Simplified procedure type", "Type of simplified customs procedure used", "SimplifiedDeclaration", "an..3", None, "1001"),
            ("De minimis threshold currency", "Currency of the de minimis threshold", "DeMinimisDeclaration", "a3", "CL_004", "6345"),
            ("Low-value consignment indicator", "Indicates a low-value consignment below threshold", "DeMinimisDeclaration", "a1", None, "4441"),
            ("Informal entry indicator", "Indicates informal entry for low-value goods", "DeMinimisDeclaration", "a1", None, "4441"),
        ]
    },
    "Response": {
        "class_default": "Response",
        "elements": [
            ("Decision code", "Code indicating the customs decision (accept/reject/hold)", "DecisionNotification", "an..3", None, "4441"),
            ("Response date", "Date of the customs response", "Response", "an..8", None, "2380"),
            ("Release notification code", "Code authorizing release of goods", "ReleaseNotification", "an..3", None, "4441"),
            ("Query code", "Code indicating the type of customs query", "QueryNotification", "an..3", None, "4441"),
            ("Error code", "Code identifying the error in the declaration", "ErrorNotification", "an..5", None, "9321"),
            ("Penalty code", "Code for the type of penalty assessed", "PenaltyAssessment", "an..3", None, "4441"),
            ("Amendment accepted indicator (resp)", "Indicates whether amendment was accepted", "Response", "a1", None, "4441"),
            ("Refund reference (resp)", "Reference number for a duty refund", "Response", "an..35", None, "1004"),
            ("Decision notification date", "Date the decision notification was issued", "DecisionNotification", "an..8", None, "2380"),
            ("Decision reason text", "Explanation for the customs decision", "DecisionNotification", "an..512", None, "4440"),
            ("Release date and time", "Date and time goods were released", "ReleaseNotification", "an..14", None, "2380"),
            ("Release type code", "Type of release (unconditional/conditional/partial)", "ReleaseNotification", "an..3", None, "4441"),
            ("Query response deadline", "Deadline for responding to the customs query", "QueryNotification", "an..8", None, "2380"),
            ("Query description text", "Description of the information requested", "QueryNotification", "an..512", None, "4440"),
            ("Error description text", "Description of the error found", "ErrorNotification", "an..512", None, "4440"),
            ("Error severity code", "Severity of the error (warning/error/fatal)", "ErrorNotification", "an..3", None, "4441"),
            ("Penalty amount (resp)", "Monetary amount of the penalty", "PenaltyAssessment", "n..18,2", None, "5004"),
            ("Penalty section reference", "Reference to the legal section for penalty", "PenaltyAssessment", "an..35", None, "1004"),
            ("Penalty payment deadline", "Deadline for paying the penalty", "PenaltyAssessment", "an..8", None, "2380"),
            ("Appeal indicator", "Indicates whether appeal has been filed", "PenaltyAssessment", "a1", None, "4441"),
            ("Gate pass issued indicator", "Indicates gate pass has been issued", "ReleaseNotification", "a1", None, "4441"),
            ("Gate pass number (resp)", "Number of the gate pass issued", "ReleaseNotification", "an..20", None, "1004"),
            ("Out of charge indicator", "Indicates goods are out of customs charge", "ReleaseNotification", "a1", None, "4441"),
            ("Adjudication reference", "Reference to adjudication proceedings", "PenaltyAssessment", "an..35", None, "1004"),
            ("Show cause notice number", "Number of the show cause notice issued", "PenaltyAssessment", "an..35", None, "1004"),
        ]
    },
}

def build_elements():
    elements = []
    idx = 1
    all_ips = ["GoodsDeclaration", "CargoDeclaration", "Transit", "AEI", "LicensePermitCertificate",
               "CertificateOfOrigin", "PhytosanitaryCertificate", "VeterinaryCertificate",
               "CustomsBond", "WarehouseDeclaration", "FreeZoneDeclaration", "TemporaryAdmission",
               "PostalECommerce", "PassengerDeclaration", "ReExportDeclaration", "DrawbackClaim",
               "ConveyanceReport", "GOVCBR", "ATACarnet", "BookingReservation",
               "DeclarationBIP", "ResponseBIP", "CrossBorderMovementBIP"]

    for domain, spec in {**ELEMENT_DEFS, **ELEMENT_DEFS_2}.items():
        for name, defn, cls, dtype, code_list, edifact in spec["elements"]:
            # Assign IPs based on domain
            if domain == "Declaration":
                ips = ["GoodsDeclaration", "CargoDeclaration", "Transit"]
            elif domain == "Consignment":
                ips = ["CargoDeclaration", "GoodsDeclaration", "ConveyanceReport"]
            elif domain == "Goods":
                ips = ["GoodsDeclaration", "Transit", "WarehouseDeclaration"]
            elif domain == "Transport":
                ips = ["CargoDeclaration", "ConveyanceReport", "Transit"]
            elif domain == "Party":
                ips = ["GoodsDeclaration", "CargoDeclaration"]
            elif domain == "Location":
                ips = ["GoodsDeclaration", "CargoDeclaration", "ConveyanceReport"]
            elif domain == "Financial":
                ips = ["GoodsDeclaration", "CustomsBond", "DrawbackClaim"]
            elif domain == "Document":
                ips = ["GoodsDeclaration", "LicensePermitCertificate", "CertificateOfOrigin"]
            elif domain == "Classification":
                ips = ["GoodsDeclaration", "Transit"]
            elif domain == "Risk & Control":
                ips = ["GoodsDeclaration", "GOVCBR"]
            elif domain == "Origin":
                ips = ["GoodsDeclaration", "CertificateOfOrigin"]
            elif domain == "Warehouse":
                ips = ["WarehouseDeclaration", "FreeZoneDeclaration", "TemporaryAdmission"]
            elif domain == "E-Commerce":
                ips = ["PostalECommerce", "GoodsDeclaration"]
            elif domain == "Response":
                ips = ["ResponseBIP", "GoodsDeclaration"]
            else:
                ips = ["GoodsDeclaration"]

            # Add some randomness to IPs
            if random.random() > 0.6:
                extra = random.choice([ip for ip in all_ips if ip not in ips])
                ips = ips + [extra]

            elements.append({
                "id": f"{idx:03d}",
                "name": name,
                "definition": defn,
                "class": cls,
                "domain": domain,
                "dataType": dtype,
                "codeList": code_list,
                "informationPackages": ips[:4],
                "format": dtype,
                "unEdifactTag": edifact
            })
            idx += 1

    return elements

elements = build_elements()

with open(os.path.join(OUTPUT_DIR, 'dataElements.json'), 'w') as f:
    json.dump(elements, f, indent=2)

print(f"dataElements.json: {len(elements)} elements")

# Count per domain
from collections import Counter
domain_counts = Counter(e["domain"] for e in elements)
for d, c in sorted(domain_counts.items(), key=lambda x: -x[1]):
    print(f"  {d}: {c}")
